import type { Gloss } from './glossary-types'

/** Quranic lemmas ranked 801–1050 by frequency. See glossary-types.ts for conventions. */
export const WORD_GLOSSES_800: readonly Gloss[] = [
  ['جِنَّة', 'jinlar; jinnilik', 'джинны; одержимость', 'jinn; madness'],
  ['حاقَ', 'o‘rab olmoq, boshiga tushmoq', 'постигать, окружать', 'to encompass, to befall'],
  ['حِجارَة', 'toshlar', 'камни', 'stones'],
  ['خَطِيئَة', 'xato, gunoh', 'грех, проступок', 'sin, wrongdoing'],
  ['خَيْرَة', 'yaxshi (ayol); tanlov', 'благая; выбор', 'good (fem.); choice'],
  ['دَم', 'qon', 'кровь', 'blood'],
  ['رِجْس', 'nopoklik, palidlik', 'скверна', 'filth, abomination'],
  ['رِسالَة', 'risolat, xabar', 'послание', 'message'],
  ['رَواسِي', 'mustahkam tog‘lar', 'незыблемые горы', 'firm mountains'],
  ['زَرْع', 'ekin', 'посев', 'crops, tillage'],
  ['سَرِيع', 'tez', 'быстрый', 'swift'],
  ['سَعْي', 'harakat, intilish', 'усердие', 'striving, effort'],
  ['سُورَة', 'sura', 'сура', 'sura, chapter'],
  ['شَفِيع', 'shafoatchi', 'заступник', 'intercessor'],
  ['شَكُور', 'ko‘p shukr qiluvchi', 'благодарный', 'most grateful'],
  ['صَدَّقَ', 'tasdiqlamoq', 'подтверждать', 'to confirm, to believe'],
  ['صَرَّفْ', 'turlicha bayon qilmoq', 'разъяснять по-разному', 'to diversify, to explain variously'],
  ['صُور', 'sur (karnay)', 'труба', 'trumpet, horn'],
  ['ضَرّ', 'zarar', 'вред', 'harm'],
  ['طَلَّقَ', 'taloq qilmoq', 'разводиться', 'to divorce'],
  ['طُور', 'Tur tog‘i', 'гора Тур', 'Mount Tur'],
  ['ظَهَرَ', 'zohir bo‘lmoq, ustun kelmoq', 'проявляться, одолевать', 'to appear, to prevail'],
  ['عِجْل', 'buzoq', 'телец', 'calf'],
  ['عُذْ', 'panoh so‘ramoq', 'искать прибежища', 'to seek refuge'],
  ['عَشِيّ', 'kechqurun', 'вечер', 'evening'],
  ['فِئَة', 'guruh, jamoa', 'отряд, группа', 'group, band'],
  ['فَسَقَ', 'itoatdan chiqmoq', 'быть нечестивым', 'to defiantly disobey'],
  ['فَطَرَ', 'yaratmoq, yormoq', 'сотворить', 'to originate, to bring into being'],
  ['قَتْل', 'o‘ldirish', 'убийство', 'killing'],
  ['كَي', 'toki, ...ishi uchun', 'чтобы', 'so that'],
  ['كَيْل', 'o‘lchov (don uchun)', 'мера', 'measure'],
  ['لِباس', 'kiyim, libos', 'одежда', 'clothing, garment'],
  ['لَهْو', 'ermak, o‘yin-kulgi', 'забава', 'amusement, diversion'],
  ['مِائَة', 'yuz', 'сто', 'hundred'],
  ['مُحْضَر', 'hozir qilingan', 'приведённый', 'brought forth'],
  ['مُخْتَلِف', 'turli xil, har xil', 'различный', 'differing, various'],
  ['مَدْيَن', 'Madyan', 'Мадьян', 'Madyan'],
  ['مَرَّ', 'o‘tmoq', 'проходить', 'to pass by'],
  ['مَرِيض', 'kasal', 'больной', 'sick'],
  ['مُسْتَقَرّ', 'qaror joyi, turar joy', 'место пребывания', 'place of settlement'],
  ['مُصِيبَة', 'musibat, balo', 'бедствие', 'calamity, misfortune'],
  ['مَغْرِب', 'g‘arb, botish joyi', 'запад', 'west, place of sunset'],
  ['مُقِيم', 'doimiy, barpo qiluvchi', 'постоянный, пребывающий', 'lasting, establishing'],
  ['نَبَذَ', 'uloqtirmoq, tashlab yubormoq', 'отбрасывать', 'to cast away'],
  ['نَزَعَ', 'sug‘urib olmoq, tortib olmoq', 'вырывать', 'to pull out, to strip away'],
  ['هُود', 'Hud', 'Худ', 'Hud'],
  ['والِدَي', 'ota-ona', 'родители', 'parents'],
  ['يَصِلُ', 'ulamoq, yetkazmoq', 'соединять, достигать', 'to join, to reach'],
  ['يُولِجُ', 'kiritmoq (biri ichiga)', 'вводить', 'to cause to enter, to merge'],
  ['آتِي', 'keluvchi', 'приходящий', 'coming'],
  ['آن', 'qaynoq, yetgan', 'кипящий, наступивший', 'boiling, at hand'],
  ['آوَى', 'panoh bermoq', 'давать приют', 'to shelter'],
  ['أَذًى', 'ozor, aziyat', 'вред, обида', 'harm, hurt'],
  ['أَرْبَعَة', 'to‘rt', 'четыре', 'four'],
  ['أَساطِير', 'afsonalar, ertaklar', 'сказания, легенды', 'legends, fables'],
  ['أَضَلّ', 'ko‘proq adashgan', 'более заблудший', 'more astray'],
  ['أَعْلَى', 'eng oliy', 'высочайший', 'most high'],
  ['أَقْبَلَ', 'yuzlanmoq, kelmoq', 'приближаться, обращаться', 'to come forward, to turn toward'],
  ['أَمْلَى', 'muhlat bermoq; diktovka qilmoq', 'давать отсрочку; диктовать', 'to grant respite; to dictate'],
  ['أَيَّدَ', 'quvvatlamoq, madad bermoq', 'поддерживать', 'to strengthen, to support'],
  ['إِفْك', 'uydirma, bo‘hton', 'клевета, ложь', 'slander, falsehood'],
  ['اجْتَنَبُ', 'chetlanmoq, saqlanmoq', 'избегать', 'to avoid, to shun'],
  ['ارْتابَ', 'shubhalanmoq', 'сомневаться', 'to doubt'],
  ['اطْمَأَنَّ', 'xotirjam bo‘lmoq', 'успокаиваться', 'to be at peace, to be assured'],
  ['انطَلَقَ', 'yo‘lga tushmoq', 'отправляться', 'to set out'],
  ['بَشِير', 'xushxabar beruvchi', 'благовестник', 'bringer of good tidings'],
  ['تَبارَكَ', 'barakotli, ulug‘ bo‘lmoq', 'быть благословенным', 'to be blessed, exalted'],
  ['تَبِعَ', 'ergashmoq', 'следовать', 'to follow'],
  ['تِجارَة', 'savdo, tijorat', 'торговля', 'trade, commerce'],
  ['تَذْكِرَة', 'eslatma, ibrat', 'напоминание', 'reminder'],
  ['جانِب', 'yon, taraf', 'сторона', 'side'],
  ['جُلُود', 'terilar', 'кожа', 'skins'],
  ['حُبّ', 'sevgi, muhabbat', 'любовь', 'love'],
  ['حَجّ', 'haj', 'хадж', 'pilgrimage'],
  ['خاضُ', 'botmoq, behuda gapga sho‘ng‘imoq', 'погружаться в пустословие', 'to engage in vain talk'],
  ['خَبِيث', 'nopok, yomon', 'скверный', 'impure, evil'],
  ['خَلِيفَة', 'xalifa, o‘rinbosar', 'наместник', 'successor, vicegerent'],
  ['رِجْز', 'azob; nopoklik', 'кара; скверна', 'punishment; filth'],
  ['رَقَبَة', 'bo‘yin; qul', 'шея; раб', 'neck; slave'],
  ['رَكِبَ', 'minmoq', 'садиться верхом', 'to ride, to embark'],
  ['رَمَى', 'otmoq, tashlamoq', 'бросать', 'to throw'],
  ['سَبَب', 'sabab; arqon, yo‘l', 'причина; путь', 'cause; means, rope'],
  ['سَحاب', 'bulut', 'облако', 'clouds'],
  ['سَوْء', 'yomonlik', 'зло', 'evil'],
  ['صِيام', 'ro‘za', 'пост', 'fasting'],
  ['ضَرّاء', 'qiyinchilik, musibat', 'бедствие, нужда', 'adversity, hardship'],
  ['ضَلالَة', 'zalolat, adashish', 'заблуждение', 'misguidance'],
  ['طُغْيان', 'tug‘yon, haddan oshish', 'бесчинство', 'transgression'],
  ['طَهَّرَ', 'poklamoq', 'очищать', 'to purify'],
  ['ظَلَّ', 'kun bo‘yi qilmoq, bo‘lib qolmoq', 'пребывать, становиться', 'to remain, to become'],
  ['عام', 'yil', 'год', 'year'],
  ['عِبادَت', 'ibodat', 'поклонение', 'worship'],
  ['عُنُق', 'bo‘yin', 'шея', 'neck'],
  ['عِوَج', 'egrilik, qiyshiqlik', 'кривизна', 'crookedness'],
  ['غُرُور', 'aldov, mag‘rurlik', 'обольщение', 'delusion, deception'],
  ['غِلّ', 'kek, adovat', 'злоба', 'rancour'],
  ['غَلِيظ', 'qattiq, dag‘al', 'суровый, грубый', 'harsh, severe'],
  ['فاعِل', 'qiluvchi', 'делающий', 'doer'],
  ['فَرَضَ', 'farz qilmoq, belgilamoq', 'предписывать', 'to ordain, to prescribe'],
  ['فَرَّقُ', 'ajratmoq, bo‘lmoq', 'разделять', 'to separate, to divide'],
  ['فَصْل', 'ajratish, hukm', 'разделение, решение', 'decision, separation'],
  ['قَذَفَ', 'otmoq, tashlamoq; tuhmat qilmoq', 'бросать; клеветать', 'to cast; to slander'],
  ['قَرار', 'qarorgoh, turar joy', 'место пребывания', 'resting place'],
  ['كَأَنْ', 'go‘yo', 'как будто', 'as though'],
  ['لَغْو', 'bekorchi gap', 'пустословие', 'idle talk'],
  ['لَوْن', 'rang', 'цвет', 'colour'],
  ['مَآب', 'qaytar joy', 'место возвращения', 'place of return'],
  ['مُبَشِّر', 'xushxabar beruvchi', 'благовествующий', 'bearer of glad tidings'],
  ['مَبْعُوث', 'tiriltiriladigan', 'воскрешаемый', 'raised up, resurrected'],
  ['مَتَى', 'qachon', 'когда', 'when'],
  ['مُحِيط', 'qamrab oluvchi', 'объемлющий', 'encompassing'],
  ['مُخْلَص', 'tanlangan, xolis qilingan', 'избранный, искренний', 'chosen, purified'],
  ['مَوْعِظَة', 'nasihat, pand', 'наставление', 'admonition'],
  ['نَبات', 'o‘simlik', 'растение', 'plant, vegetation'],
  ['هُنالِك', 'o‘sha yerda, o‘shanda', 'там, тогда', 'there, at that point'],
  ['واسِع', 'keng qamrovli, keng', 'объемлющий, щедрый', 'all-encompassing, vast'],
  ['وَلَدَ', 'tug‘moq', 'рождать', 'to beget, to give birth'],
  ['يُؤاخِذُ', 'jazoga tortmoq', 'взыскивать, наказывать', 'to take to task'],
  ['يَتَساءَلُ', 'bir-biridan so‘rashmoq', 'расспрашивать друг друга', 'to question one another'],
  ['يُسارِعُ', 'shoshilmoq', 'спешить', 'to hasten'],
  ['يَسْتَحْىِۦ', 'uyalmoq; tirik qoldirmoq', 'стыдиться; оставлять в живых', 'to feel shame; to spare alive'],
  ['يُضاعِفُ', 'ikki barobar qilmoq', 'умножать', 'to multiply'],
  ['يَقْبَلُ', 'qabul qilmoq', 'принимать', 'to accept'],
  ['يَلْعَبْ', 'o‘ynamoq', 'играть', 'to play'],
  ['يَنطِقُ', 'so‘zlamoq', 'говорить', 'to speak'],
  ['يَهُود', 'yahudiylar', 'иудеи', 'Jews'],
  ['أَبْيَض', 'oq', 'белый', 'white'],
  ['أُجِيبَت', 'javob berilmoq, ijobat qilinmoq', 'быть отвеченным', 'to be answered'],
  ['أَسْقَيْ', 'suv bermoq', 'поить', 'to give to drink'],
  ['أَشُدّ', 'balog‘at, kuch yoshi', 'зрелость, расцвет сил', 'full strength, maturity'],
  ['أَظْهَرَ', 'zohir qilmoq, g‘olib qilmoq', 'проявлять, давать превосходство', 'to make manifest, to make prevail'],
  ['أَعْطَى', 'bermoq, ato qilmoq', 'давать', 'to give'],
  ['أَغْوَيْ', 'yo‘ldan urmoq', 'сбивать с пути', 'to lead astray'],
  ['إِسْلام', 'islom, taslim bo‘lish', 'ислам, покорность', 'Islam, submission'],
  ['ابْتَلَى', 'sinamoq', 'испытывать', 'to test'],
  ['اخْتَصَمُ', 'nizolashmoq', 'препираться', 'to dispute with one another'],
  ['ارْتَدَّ', 'orqaga qaytmoq, dindan qaytmoq', 'отступать, отрекаться', 'to turn back, to apostatise'],
  ['ازْدادُ', 'ziyoda bo‘lmoq', 'увеличиваться', 'to increase'],
  ['اسْتَضْعَفُ', 'zaif deb bilmoq, ezmoq', 'считать слабым, притеснять', 'to deem weak, to oppress'],
  ['اشْتَهَتْ', 'orzu qilmoq, ishtiyoq bildirmoq', 'желать', 'to desire'],
  ['بارَكَ', 'baraka bermoq', 'благословлять', 'to bless'],
  ['بِرّ', 'yaxshilik, taqvo', 'благочестие', 'righteousness'],
  ['بُرْهان', 'burhon, aniq dalil', 'доказательство', 'proof, evidence'],
  ['تَزَكَّى', 'poklanmoq', 'очищаться', 'to purify oneself'],
  ['تَعالَ', 'kel! (buyruq)', 'иди сюда!', 'come!'],
  ['تَفَرَّقَ', 'bo‘linib ketmoq', 'разделяться', 'to split up'],
  ['ثَلاث', 'uch', 'три', 'three'],
  ['ثِياب', 'kiyimlar', 'одежды', 'garments'],
  ['جَدِيد', 'yangi', 'новый', 'new'],
  ['جَنب', 'yon, biqin', 'бок', 'side'],
  ['خَزائِن', 'xazinalar', 'сокровищницы', 'treasuries'],
  [
    'خَسَفَ',
    'yerga yutdirmoq; tutilmoq',
    'заставлять поглотить землёй; затмеваться',
    'to cause to sink; to be eclipsed'
  ],
  ['خَشْيَة', 'qo‘rquv, hayiqish', 'страх, благоговение', 'fear, awe'],
  ['خَفَّفَ', 'yengillashtirmoq', 'облегчать', 'to lighten'],
  ['خِلال', 'orasida, ichida', 'между, среди', 'through, among'],
  ['دَمَّرَ', 'vayron qilmoq', 'уничтожать', 'to destroy'],
  ['ذَهَب', 'oltin', 'золото', 'gold'],
  ['راكِع', 'ruku qiluvchi', 'кланяющийся', 'one bowing'],
  ['راوَدُ', 'ko‘ndirmoqchi bo‘lmoq, yo‘ldan urmoqchi bo‘lmoq', 'соблазнять', 'to seek to seduce'],
  ['زالَت', 'yo‘qolmoq, siljimoq', 'исчезать, сдвигаться', 'to cease, to move away'],
  ['سَمَّى', 'nom qo‘ymoq, atamoq', 'называть', 'to name'],
  ['شِمال', 'chap tomon; shimol', 'левая сторона; север', 'left side; north'],
  ['صاعِقَة', 'chaqmoq, momaqaldiroq zarbasi', 'молния, удар грома', 'thunderbolt'],
  ['صُحُف', 'sahifalar', 'свитки', 'scriptures, scrolls'],
  ['صَوْت', 'ovoz', 'голос', 'voice, sound'],
  ['ضَعِيف', 'zaif', 'слабый', 'weak'],
  ['طاغُوت', 'tog‘ut, botil ma’bud', 'тагут, идол', 'false deity, tyrant'],
  ['طافَ', 'tavof qilmoq, aylanmoq', 'обходить кругом', 'to circumambulate'],
  ['ظاهِر', 'zohir, oshkora; ustun', 'явный; преобладающий', 'apparent; prevailing'],
  ['عَجِبُ', 'hayron bo‘lmoq', 'удивляться', 'to wonder, to marvel'],
  ['عُدْوان', 'tajovuz, dushmanlik', 'вражда, агрессия', 'aggression, transgression'],
  ['عَقِب', 'tovon, iz; ort', 'пятка, след', 'heel, trace'],
  ['فَرْج', 'avrat; yoriq', 'срамное место; расщелина', 'private part; gap'],
  ['قانِت', 'itoatgo‘y, qunut qiluvchi', 'покорный', 'devoutly obedient'],
  ['قَدَم', 'oyoq, qadam', 'нога, стопа', 'foot'],
  ['قَرِين', 'hamroh, yaqin', 'спутник, товарищ', 'companion'],
  ['كَبُرَ', 'katta bo‘lmoq, og‘ir kelmoq', 'быть великим, тяготить', 'to be great, to be hard'],
  ['كَفَّ', 'to‘xtatmoq, qaytarmoq', 'удерживать', 'to restrain, to withhold'],
  ['كِيدُ', 'hiyla qilmoq', 'строить козни', 'to plot'],
  ['لَعِب', 'o‘yin', 'игра', 'play'],
  ['لَيْلَة', 'kecha (bir kecha)', 'ночь', 'night'],
  ['مُبارَك', 'muborak, barakotli', 'благословенный', 'blessed'],
  ['مُتَّكِئ', 'yonboshlagan', 'возлежащий', 'reclining'],
  ['مِثْقال', 'og‘irlik o‘lchovi, misqol', 'вес, мера', 'weight, measure'],
  ['مُحْصَنَة', 'iffatli, turmush qurgan ayol', 'целомудренная, замужняя', 'chaste, married woman'],
  ['مُدْبِر', 'orqasiga qaytuvchi', 'отступающий', 'one turning back'],
  ['مُشْفِق', 'qo‘rquvchi, mehribon', 'испытывающий трепет', 'apprehensive, compassionate'],
  ['مُقَرَّب', 'yaqin qilingan', 'приближённый', 'brought near'],
  ['مَنافِع', 'manfaatlar, foydalar', 'выгоды, польза', 'benefits'],
  ['مَوَدَّة', 'mehr, muhabbat', 'привязанность', 'affection'],
  ['مِيقات', 'belgilangan vaqt yoki joy', 'назначенный срок', 'appointed time or place'],
  ['نُزُل', 'mehmondorchilik, tayyor ziyofat', 'угощение, приём', 'hospitality, lodging'],
  ['نَفَرَ', 'chiqmoq, otlanmoq', 'выступать в поход', 'to go forth'],
  ['هَمَّ', 'qasd qilmoq, niyat qilmoq', 'намереваться', 'to intend, to resolve'],
  ['هَوَى', 'qulamoq, tushmoq', 'падать', 'to fall'],
  ['وَصِيَّة', 'vasiyat', 'завещание', 'bequest, will'],
  ['يَئِسَ', 'noumid bo‘lmoq', 'отчаиваться', 'to despair'],
  ['يَطْمَعُ', 'tama qilmoq, umid qilmoq', 'жаждать, надеяться', 'to covet, to hope'],
  ['يَقِين', 'yaqin, aniq ishonch', 'убеждённость', 'certainty'],
  ['يَمّ', 'dengiz', 'море', 'sea'],
  ['يَنتَظِرُ', 'kutmoq', 'ожидать', 'to wait, to await'],
  ['يَهْبِطُ', 'tushmoq, pastga enmoq', 'спускаться', 'to descend'],
  ['أَبْقَى', 'ko‘proq boqiy, doimiyroq', 'более вечный', 'more lasting'],
  ['أَبَوان', 'ota-ona', 'родители', 'parents'],
  ['أَثِيم', 'gunohkor', 'грешный', 'sinful'],
  ['أَرْبَع', 'to‘rt', 'четыре', 'four'],
  ['أَشْهَدَ', 'guvoh qilmoq', 'делать свидетелем', 'to make witness'],
  ['أَصِيل', 'kechqurun', 'вечер', 'late afternoon, evening'],
  ['أَفاضَ', 'oqib chiqmoq, qaytmoq (Arafotdan)', 'устремляться, изливаться', 'to pour forth, to depart in throngs'],
  ['أُكُل', 'meva, hosil', 'плоды, урожай', 'produce, fruit'],
  ['أُمْطِرَتْ', 'yomg‘ir yog‘dirilmoq', 'быть осыпанным дождём', 'to be rained upon'],
  ['أَنسَى', 'unuttirmoq', 'заставлять забыть', 'to cause to forget'],
  ['أَهْدَى', 'to‘g‘riroq yo‘lda', 'более верно ведомый', 'better guided'],
  ['إِخْوَة', 'aka-ukalar', 'братья', 'brothers'],
  ['إِصْلاح', 'isloh, tuzatish', 'исправление, примирение', 'reconciliation, reform'],
  ['اثْنَتَيْن', 'ikki (ayol)', 'две', 'two (fem.)'],
  ['اخْتِلاف', 'ixtilof, farq', 'различие, разногласие', 'difference, alternation'],
  ['اضْطُرَّ', 'majbur bo‘lmoq', 'быть вынужденным', 'to be compelled'],
  ['اعْتَزَلَ', 'chetlanmoq, ajralmoq', 'отдаляться', 'to withdraw, to keep away'],
  ['افْتَدَى', 'fidya bermoq, evaz to‘lamoq', 'откупаться', 'to ransom oneself'],
  ['الْتَقَى', 'uchrashmoq, to‘qnashmoq', 'встречаться', 'to meet, to encounter'],
  ['انتَصَرَ', 'yordam olmoq, intiqom olmoq', 'побеждать, мстить', 'to be helped, to avenge'],
  ['بَصِيرَة', 'basirat, ichki ko‘rish', 'прозорливость', 'insight'],
  ['بُعْد', 'uzoqlik; halokat', 'отдалённость; гибель', 'distance; ruin'],
  ['بَعْل', 'Ba’l (but); er', 'Баал; муж', 'Baal; husband'],
  ['بُكْرَة', 'ertalab', 'утро', 'morning'],
  ['بُنْيان', 'bino, imorat', 'здание, строение', 'building, structure'],
  ['بَيْع', 'savdo, oldi-sotdi', 'торговля', 'trade, sale'],
  ['تَبْدِيل', 'o‘zgartirish', 'изменение, замена', 'alteration, change'],
  ['تَنازَعُ', 'tortishmoq, nizolashmoq', 'препираться', 'to dispute among themselves'],
  ['تَنَزَّلَتْ', 'tushmoq, nozil bo‘lmoq', 'нисходить', 'to descend'],
  ['تَوْبَة', 'tavba', 'покаяние', 'repentance'],
  ['جانّ', 'jin', 'джинн', 'jinn'],
  ['جَمِيل', 'go‘zal, chiroyli', 'прекрасный', 'beautiful, gracious'],
  ['جَناح', 'qanot; gunoh, ayb', 'крыло; вина', 'wing; blame'],
  ['جَهْر', 'oshkoralik, baland ovoz', 'громкость, открытость', 'openness, loudness'],
  ['حَبّ', 'don, urug‘', 'зерно', 'grain, seed'],
  ['حَبْل', 'arqon, rishta', 'верёвка, связь', 'rope, bond'],
  ['حِجاب', 'parda, to‘siq', 'завеса', 'veil, barrier'],
  ['حُجَّة', 'hujjat, dalil', 'довод', 'argument, proof'],
  ['حَسْرَة', 'afsus, hasrat', 'сожаление', 'regret, grief'],
  ['حَضَرَ', 'hozir bo‘lmoq, yetib kelmoq', 'присутствовать, наступать', 'to be present, to attend'],
  ['حَظّ', 'ulush, nasiba', 'доля', 'share, portion'],
  ['حَفِظَ', 'saqlamoq, yod olmoq', 'хранить, беречь', 'to preserve, to guard'],
  ['حَمْل', 'yuk; homiladorlik', 'ноша; беременность', 'load; pregnancy'],
  ['حَىَّ', 'tirik bo‘lmoq, yashamoq', 'жить', 'to live'],
  ['دامُ', 'davom etmoq', 'длиться', 'to last, to continue'],
  ['دَلَّ', 'ko‘rsatmoq, dalolat qilmoq', 'указывать', 'to point out, to guide to'],
  ['ذِلَّة', 'xorlik, tubanlik', 'унижение', 'humiliation'],
  ['رُءْيا', 'tush, ko‘rish', 'сон, видение', 'dream, vision']
] as const
