import type { Gloss } from './glossary-types'

/** Quranic lemmas ranked 1051–1300 by frequency. See glossary-types.ts for conventions. */
export const WORD_GLOSSES_1050: readonly Gloss[] = [
  ['رِبا', 'ribo, sudxo‘rlik', 'ростовщичество', 'usury, interest'],
  ['زُبُر', 'kitoblar, sahifalar', 'писания', 'scriptures, books'],
  ['زَكَرِيّا', 'Zakariyo', 'Закария', 'Zechariah'],
  ['سائِل', 'so‘rovchi, tilanchi', 'просящий', 'one who asks, beggar'],
  ['سابِق', 'oldinda boruvchi, o‘zuvchi', 'опережающий', 'foremost, one who precedes'],
  ['سِتَّة', 'olti', 'шесть', 'six'],
  ['سَفَر', 'safar', 'путешествие', 'journey'],
  ['سَفِيه', 'aqlsiz, safeh', 'глупец', 'foolish, feeble-minded'],
  ['سَنَة', 'yil', 'год', 'year'],
  ['سَوْءَة', 'avrat; yomon holat', 'нагота; скверна', 'nakedness, shameful state'],
  ['سِيقَ', 'haydalmoq', 'быть погоняемым', 'to be driven'],
  ['شاقُّ', 'qarshilik qilmoq, ajralmoq', 'противиться', 'to oppose, to defy'],
  ['شَجَر', 'daraxtlar', 'деревья', 'trees'],
  ['شِقاق', 'nizo, qarama-qarshilik', 'раскол, вражда', 'schism, opposition'],
  ['صَفّ', 'saf, qator', 'ряд', 'row, rank'],
  ['ضاقَ', 'tor bo‘lmoq, siqilmoq', 'быть стеснённым', 'to be constricted, to be distressed'],
  ['ضَحِكَتْ', 'kulmoq', 'смеяться', 'to laugh'],
  ['طَلَعَ', 'chiqmoq (quyosh); ko‘z tashlamoq', 'восходить; заглядывать', 'to rise; to look upon'],
  ['عاكِف', 'e’tikofda turuvchi, berilgan', 'пребывающий, преданный', 'devoted, secluded in worship'],
  ['عَدَّ', 'sanamoq', 'считать', 'to count'],
  ['عَشْر', 'o‘n', 'десять', 'ten'],
  ['عُمُر', 'umr', 'жизнь, век', 'lifetime'],
  ['عَمِيَ', 'ko‘r bo‘lmoq', 'слепнуть', 'to be blind'],
  ['غابِر', 'orqada qolgan, halok bo‘lguvchi', 'оставшийся позади', 'one who lags behind'],
  ['فَحْشاء', 'fahsh, uyatsizlik', 'мерзость', 'immorality'],
  ['فُرْقان', 'furqon, haq bilan botilni ajratuvchi', 'различение', 'criterion, distinguisher'],
  ['قاعِد', 'o‘tirgan, qolib ketgan', 'сидящий, отсиживающийся', 'one sitting, staying behind'],
  ['قِبْلَة', 'qibla, yo‘nalish', 'кибла, направление', 'prayer direction'],
  ['قَدْر', 'qadr, o‘lchov, taqdir', 'мера, предопределение', 'measure, decree'],
  ['كَأَيِّن', 'qancha ko‘p', 'сколь много', 'how many'],
  ['كارِه', 'yoqtirmaydigan', 'испытывающий отвращение', 'unwilling, averse'],
  ['كُبْرَى', 'eng katta (ayol shakli)', 'величайшая', 'greatest (fem.)'],
  ['كَبِيرَة', 'katta gunoh; katta (ayol)', 'великий грех; большая', 'great sin; great (fem.)'],
  ['لَطِيف', 'latif, nozik bilguvchi', 'проницательный, добрый', 'subtle, most kind'],
  ['مُتَكَبِّر', 'kibrlanuvchi; Mutakabbir', 'высокомерный; Превознесённый', 'arrogant; the Supreme'],
  ['مُرِيب', 'shubhaga soluvchi', 'вызывающий сомнение', 'disquieting, causing doubt'],
  ['مَطَر', 'yomg‘ir', 'дождь', 'rain'],
  ['مَفْعُول', 'bajarilgan, amalga oshgan', 'исполненный', 'accomplished, done'],
  ['مُنِيب', 'tavba bilan qaytuvchi', 'обращающийся с покаянием', 'one turning in repentance'],
  ['مُهاجِر', 'muhojir, hijrat qiluvchi', 'переселенец', 'emigrant'],
  ['مِهاد', 'to‘shak, beshik', 'ложе, колыбель', 'bed, resting place'],
  ['ناقَة', 'tuya (urg‘ochi)', 'верблюдица', 'she-camel'],
  ['نَخِيل', 'xurmo daraxtlari', 'финиковые пальмы', 'date palms'],
  ['نِصْف', 'yarim', 'половина', 'half'],
  ['هاد', 'hidoyat qiluvchi', 'ведущий', 'guide'],
  ['هَدْي', 'qurbonlik (haj)', 'жертвенное животное', 'sacrificial offering'],
  ['واد', 'vodiy, jarlik', 'долина', 'valley'],
  ['وارِث', 'meros oluvchi, voris', 'наследник', 'inheritor'],
  ['وَلِيد', 'chaqaloq, bola', 'ребёнок, младенец', 'child, infant'],
  ['يَزِرُ', 'yuk ko‘tarmoq (gunoh)', 'нести бремя', 'to bear a burden'],
  ['يَسْتَبْشِرُ', 'xursand bo‘lmoq', 'радоваться вести', 'to rejoice at good news'],
  ['يُسْر', 'osonlik', 'лёгкость', 'ease'],
  ['يَعْمَهُ', 'sarson bo‘lmoq, adashib yurmoq', 'блуждать', 'to wander blindly'],
  ['يُكَلِّفُ', 'yuklamoq, majbur qilmoq', 'возлагать бремя', 'to burden, to charge'],
  ['يُنقَصُ', 'kamaytirilmoq', 'быть уменьшенным', 'to be diminished'],
  ['أَبْكَم', 'soqov', 'немой', 'mute'],
  ['أَخْذ', 'olish, tutish (jazo)', 'хватка, взятие', 'seizure, grip'],
  ['أَدْرَكَ', 'yetib olmoq, anglamoq', 'настигать, постигать', 'to overtake, to comprehend'],
  ['أَسْرَفَ', 'isrof qilmoq, haddan oshmoq', 'излишествовать', 'to be excessive'],
  ['أَسْرَى', 'kechasi yurgizmoq', 'вести ночью', 'to travel by night'],
  ['أَسْفَل', 'eng past', 'нижайший', 'lowest'],
  ['أَقْرَضُ', 'qarz bermoq', 'давать в долг', 'to lend'],
  ['أُمْنِيَّت', 'orzu, umid', 'мечта, желание', 'wish, longing'],
  ['أُمِّيّ', 'ummiy, savodsiz', 'неграмотный', 'unlettered'],
  ['أُنثَيَيْن', 'ikki urg‘ochi', 'две самки', 'two females'],
  ['أَنداد', 'tenglar, sheriklar', 'равные, сотоварищи', 'equals, rivals'],
  ['أَوّاب', 'ko‘p qaytuvchi, tavbakor', 'постоянно обращающийся', 'oft-returning'],
  ['أَيّان', 'qachon', 'когда', 'when'],
  ['إِخْراج', 'chiqarish, quvish', 'изгнание', 'expulsion, driving out'],
  ['اسْتَمْتَعَ', 'bahramand bo‘lmoq', 'наслаждаться', 'to enjoy'],
  ['انتَقَمْ', 'intiqom olmoq', 'мстить', 'to take revenge'],
  ['باءَ', 'qaytmoq (yuk bilan)', 'навлекать на себя', 'to incur, to return with'],
  ['بالِغ', 'yetuvchi, yetkazuvchi', 'достигающий', 'reaching, attaining'],
  ['بايَعْ', 'bay’at bermoq', 'присягать', 'to pledge allegiance'],
  ['بَقَرَة', 'sigir', 'корова', 'cow'],
  ['بَلاء', 'sinov, balo', 'испытание', 'trial'],
  ['بَلَّغْ', 'yetkazmoq', 'доводить, передавать', 'to convey, to deliver'],
  ['بُهْتان', 'bo‘hton', 'клевета', 'slander'],
  ['بَوَّأَ', 'joylashtirmoq', 'поселять', 'to settle, to establish'],
  ['تَحِيَّة', 'salom, tabrik', 'приветствие', 'greeting'],
  ['تَصَدَّقَ', 'sadaqa bermoq', 'подавать милостыню', 'to give charity'],
  ['ثُقِفُ', 'topmoq, duch kelmoq', 'заставать, настигать', 'to come upon, to overtake'],
  ['ثَقَل', 'og‘irlik, yuk', 'тяжесть', 'burden, weight'],
  ['ثُلُث', 'uchdan bir', 'треть', 'a third'],
  ['جاعِل', 'qiluvchi, qo‘yuvchi', 'делающий', 'one who makes, appoints'],
  ['حَدِيد', 'temir', 'железо', 'iron'],
  ['حَلال', 'halol', 'дозволенное', 'lawful'],
  ['حُلُم', 'tush; balog‘at', 'сон; зрелость', 'dream; puberty'],
  ['خَبِيثَة', 'nopok (ayol shakli)', 'скверная', 'impure (fem.)'],
  ['خِلاف', 'qarshilik, orqa', 'противоположность', 'opposition, contrary'],
  ['خَلاق', 'ulush, nasiba', 'доля', 'share, portion'],
  ['خُلْد', 'abadiylik', 'вечность', 'eternity'],
  ['خَمْر', 'may, ichkilik', 'вино', 'wine, intoxicant'],
  ['خِيفَة', 'qo‘rquv', 'страх', 'fear'],
  ['دَعْوَة', 'da’vat, chaqiriq', 'призыв', 'call, invitation'],
  ['ذَرَأَ', 'yaratmoq, ko‘paytirmoq', 'создавать, размножать', 'to create, to multiply'],
  ['ذَرَّة', 'zarra', 'пылинка, атом', 'atom, speck'],
  ['راحِم', 'rahm qiluvchi', 'милующий', 'merciful one'],
  ['رازِق', 'rizq beruvchi', 'наделяющий уделом', 'provider'],
  ['رَجِيم', 'quvilgan, la’natlangan', 'побиваемый, проклятый', 'accursed, outcast'],
  ['رُشْد', 'to‘g‘ri yo‘l, kamolot', 'праведность, зрелость', 'right guidance, maturity'],
  ['زاغَ', 'og‘moq, burilib ketmoq', 'уклоняться', 'to deviate, to swerve'],
  ['سَبْت', 'shanba', 'суббота', 'Sabbath'],
  ['سِجْن', 'qamoqxona', 'тюрьма', 'prison'],
  ['سُجُود', 'sajda qiluvchilar; sajda', 'земные поклоны', 'prostration, those prostrating'],
  ['سُرُر', 'so‘rilar, taxtlar', 'ложа', 'couches'],
  ['سَعَة', 'kenglik, farovonlik', 'простор, достаток', 'ampleness, capacity'],
  ['سَكِينَة', 'sakina, xotirjamlik', 'спокойствие', 'tranquillity'],
  ['سَلَّمَ', 'salom bermoq, topshirmoq', 'приветствовать, вручать', 'to greet, to submit'],
  ['سِيما', 'belgi, alomat', 'признак', 'mark, sign'],
  ['شَدَدْ', 'mustahkamlamoq, qattiq qilmoq', 'укреплять', 'to strengthen, to harden'],
  ['ضُحًى', 'choshgoh, tush payti', 'утро, полдень', 'forenoon'],
  ['طاغي', 'tug‘yon qiluvchi', 'бесчинствующий', 'transgressor'],
  ['طَرْف', 'ko‘z, nigoh; chet', 'взгляд; край', 'glance, eye; edge'],
  ['ظاهَرُ', 'yordamlashmoq; zihor qilmoq', 'помогать друг другу', 'to back one another'],
  ['ظُلَّة', 'soyabon, bulut', 'сень, туча', 'canopy, shade'],
  ['ظَهِير', 'yordamchi, madadkor', 'помощник', 'supporter, backer'],
  ['عاقَبَ', 'jazolamoq, o‘ch olmoq', 'наказывать', 'to punish, to retaliate'],
  ['عِبْرَة', 'ibrat', 'назидание', 'lesson, admonition'],
  ['عَداوَة', 'adovat, dushmanlik', 'вражда', 'enmity'],
  ['عَدَد', 'son, sanoq', 'число', 'number'],
  ['عَرَض', 'o‘tkinchi matoh', 'мирские блага', 'transient gain, worldly goods'],
  ['عُقْبَى', 'oqibat, natija', 'исход', 'final outcome'],
  ['عَلا', 'baland bo‘lmoq, ustun kelmoq', 'возвышаться', 'to be high, to exalt oneself'],
  ['عَهِدَ', 'ahd olmoq, buyurmoq', 'заключать завет', 'to make a covenant, to enjoin'],
  ['غاوي', 'yo‘ldan adashgan', 'заблудший', 'deviant, errant'],
  ['غَضِبَ', 'g‘azablanmoq', 'гневаться', 'to be angry'],
  ['غَمّ', 'g‘am, tashvish', 'печаль', 'grief, distress'],
  ['غَيْظ', 'qattiq g‘azab', 'ярость', 'rage, fury'],
  ['فاطِر', 'yaratuvchi, yo‘qdan bor qiluvchi', 'Творец', 'Originator, Creator'],
  ['فَجْر', 'tong, bomdod', 'заря', 'dawn'],
  ['فُجِّرَتْ', 'yorilmoq, otilib chiqmoq', 'быть исторгнутым', 'to be made to gush forth'],
  ['فَرَّتْ', 'qochmoq', 'убегать', 'to flee'],
  ['فَرِح', 'shodlanuvchi, mag‘rur', 'ликующий', 'exultant'],
  ['فَرِيضَة', 'farz, belgilangan ulush', 'предписание, доля', 'obligation, ordained share'],
  ['فِضَّة', 'kumush', 'серебро', 'silver'],
  ['قائِل', 'aytuvchi, so‘zlovchi', 'говорящий', 'speaker'],
  ['قَبْر', 'qabr', 'могила', 'grave'],
  ['قَرْض', 'qarz', 'заём', 'loan'],
  ['قَصَص', 'qissa, hikoya', 'повествование', 'narrative, story'],
  ['قَلَّبُ', 'ag‘darmoq, aylantirmoq', 'переворачивать', 'to turn about'],
  ['قَمِيص', 'ko‘ylak', 'рубаха', 'shirt'],
  ['قَهّار', 'Qahhor, hamma narsani bo‘ysundiruvchi', 'Всепокоряющий', 'the Irresistible, Subduer'],
  ['كَأْس', 'qadah, kosa', 'чаша', 'cup'],
  ['كاتِب', 'yozuvchi, kotib', 'писец', 'scribe, writer'],
  ['كِبَر', 'qarilik, katta yosh', 'старость', 'old age'],
  ['كَرَّة', 'qaytish, yana bir bor', 'возвращение, ещё раз', 'return, another turn'],
  ['كَنز', 'xazina', 'клад, сокровище', 'treasure'],
  ['كَهْف', 'g‘or', 'пещера', 'cave'],
  ['لُؤْلُؤ', 'marvarid', 'жемчуг', 'pearls'],
  ['لَقَّى', 'talqin qilmoq, o‘rgatmoq', 'внушать, преподносить', 'to impart, to receive'],
  ['مُبَيِّنَة', 'ochiq-oydin (ayol shakli)', 'явная', 'clear, manifest (fem.)'],
  ['مُتَشابِه', 'bir-biriga o‘xshash, mutashobih', 'схожий, иносказательный', 'resembling, allegorical'],
  ['مُدَّكِر', 'ibrat oluvchi, eslovchi', 'внимающий', 'one who takes heed'],
  ['مَرَدّ', 'qaytish, qaytarish', 'возвращение', 'return, averting'],
  ['مُسْتَكْبِر', 'kibrlanuvchi', 'высокомерный', 'arrogant one'],
  ['مُعْتَدي', 'haddan oshuvchi', 'преступающий', 'transgressor'],
  ['مَعْدُودَة', 'sanoqli, ozgina', 'исчисленные', 'numbered, few'],
  ['مَقْت', 'qattiq nafrat', 'отвращение, ненависть', 'abhorrence, hatred'],
  ['مُلِئَتْ', 'to‘ldirilmoq', 'быть наполненным', 'to be filled'],
  ['مَنّ', 'ne’mat; minnat', 'манна; милость', 'manna; favour'],
  ['مُنتَظِر', 'kutuvchi', 'ожидающий', 'one waiting'],
  ['مُنظَر', 'muhlat berilgan', 'получивший отсрочку', 'one given respite'],
  ['مُنِير', 'nur sochuvchi, yorituvchi', 'освещающий', 'illuminating'],
  ['مَوْج', 'to‘lqin', 'волна', 'waves'],
  ['مَيْتَة', 'o‘lik, o‘lgan hayvon', 'мертвечина', 'dead animal, carrion'],
  ['مِيعاد', 'belgilangan vaqt', 'назначенный срок', 'appointed time'],
  ['ناصِح', 'nasihatgo‘y, xayrixoh', 'искренний советчик', 'sincere adviser'],
  ['نَزَلَ', 'tushmoq, nozil bo‘lmoq', 'нисходить', 'to descend'],
  ['نَقَضَتْ', 'buzmoq (ahdni)', 'нарушать', 'to break, to undo'],
  ['نَكَثَ', 'ahdni buzmoq', 'нарушать клятву', 'to break a pledge'],
  ['هامان', 'Homon', 'Хаман', 'Haman'],
  ['واقِع', 'sodir bo‘luvchi, tushuvchi', 'происходящий', 'befalling, inevitable'],
  ['وَحْد', 'yolg‘iz, yakka', 'один, единолично', 'alone'],
  ['وَحْى', 'vahiy', 'откровение', 'revelation'],
  ['وَسِعَ', 'qamramoq, kengaytirmoq', 'объемлять', 'to encompass, to extend to'],
  ['وَعِيد', 'tahdid, ogohlantirish', 'угроза', 'threat, warning'],
  ['وَقْر', 'og‘irlik (quloqda), karlik', 'глухота', 'deafness, heaviness in the ear'],
  ['يَتَمَنَّ', 'orzu qilmoq', 'желать', 'to wish for'],
  ['يُجِيرُ', 'panoh bermoq, himoya qilmoq', 'давать защиту', 'to grant protection'],
  ['يَخْفَى', 'yashirin bo‘lmoq', 'быть скрытым', 'to be hidden'],
  ['يَسْتَأْخِرُ', 'kechikmoq, orqada qolmoq', 'откладывать, задерживаться', 'to delay, to fall behind'],
  ['يَسْتَفْتُ', 'fatvo so‘ramoq', 'просить разъяснения', 'to ask for a ruling'],
  ['يَصْفَحُ', 'kechirmoq, yuz o‘girmoq', 'прощать, отворачиваться', 'to pardon, to overlook'],
  ['يَنۢبَغِي', 'loyiq bo‘lmoq, to‘g‘ri kelmoq', 'подобать', 'to be fitting, to behove'],
  ['آثَرَ', 'afzal ko‘rmoq', 'предпочитать', 'to prefer'],
  ['آنَسَ', 'sezmoq, ko‘rmoq', 'заметить, ощутить', 'to perceive, to notice'],
  ['أَبْلَغُ', 'yetkazmoq', 'доводить', 'to convey'],
  ['أَثارُ', 'qo‘zg‘atmoq, haydab yurmoq', 'вздымать, поднимать', 'to stir up'],
  ['أَجْرَمُ', 'jinoyat qilmoq, gunoh qilmoq', 'грешить', 'to commit crime, to sin'],
  ['أَحْصَنَتْ', 'saqlamoq, iffatli bo‘lmoq', 'оберегать, быть целомудренной', 'to guard, to be chaste'],
  ['أَرائِك', 'so‘rilar, taxtlar', 'ложа', 'couches, thrones'],
  ['أَرْضَعَتْ', 'emizmoq', 'кормить грудью', 'to suckle'],
  ['أَساءَ', 'yomonlik qilmoq', 'творить зло', 'to do evil'],
  ['أَساوِر', 'bilaguzuklar', 'браслеты', 'bracelets'],
  ['أَسْباط', 'asbotlar, qabilalar', 'колена (Израиля)', 'tribes (of Israel)'],
  ['أَسْكَن', 'joylashtirmoq, yashatmoq', 'поселять', 'to settle, to house'],
  ['أَصْنام', 'butlar, sanamlar', 'идолы', 'idols'],
  ['أُكْرِهَ', 'majbur qilinmoq', 'быть принуждённым', 'to be compelled'],
  ['أَلَّفَ', 'jamlamoq, ulfat qilmoq', 'сближать, объединять', 'to unite, to bring together'],
  ['أَمْن', 'omonlik, xavfsizlik', 'безопасность', 'security, safety'],
  ['أَوْصا', 'vasiyat qilmoq, buyurmoq', 'завещать, наставлять', 'to enjoin, to bequeath'],
  ['أَوْقَدُ', 'yoqmoq (olov)', 'разжигать', 'to kindle'],
  ['أَوَى', 'panoh topmoq', 'находить приют', 'to take refuge'],
  ['اسْتَبَقَ', 'musobaqalashmoq, poyga qilmoq', 'состязаться', 'to race, to compete'],
  ['اسْتَخْلَفَ', 'o‘rinbosar qilmoq', 'делать преемником', 'to make a successor'],
  ['اعْتَصَمُ', 'mahkam ushlamoq', 'крепко держаться', 'to hold fast'],
  ['اقْتَرَبَ', 'yaqinlashmoq', 'приближаться', 'to draw near'],
  ['اكْتَسَبَ', 'kasb qilmoq, orttirmoq', 'приобретать', 'to earn, to acquire'],
  ['اللَّهُمَّ', 'Allohim!', 'О Аллах!', 'O Allah'],
  ['امْرِئ', 'kishi, odam', 'человек', 'person, man'],
  ['انشَقَّ', 'yorilmoq', 'раскалываться', 'to split asunder'],
  ['اهْجُرْ', 'tark etmoq, uzoqlashmoq', 'оставлять, сторониться', 'to forsake, to shun'],
  ['بَثَّ', 'sochmoq, tarqatmoq', 'рассеивать', 'to scatter, to spread'],
  ['بَرَزَ', 'chiqmoq, namoyon bo‘lmoq', 'выходить, представать', 'to come forth, to appear'],
  ['بَرْق', 'chaqmoq', 'молния', 'lightning'],
  ['بِضاعَة', 'mol, savdo buyumi', 'товар', 'merchandise, goods'],
  ['بَطَشْ', 'zarba bermoq, qattiq tutmoq', 'хватать с силой', 'to seize violently'],
  ['بَغْضاء', 'nafrat, adovat', 'ненависть', 'hatred'],
  ['بَكَتْ', 'yig‘lamoq', 'плакать', 'to weep'],
  ['بَلْدَة', 'shahar, yurt', 'город, местность', 'town, land'],
  ['تَبَرَّأَ', 'voz kechmoq, xoli bo‘lmoq', 'отрекаться', 'to disown, to dissociate'],
  ['تَحْرِير', 'ozod qilish', 'освобождение', 'freeing, emancipation'],
  ['تِسْع', 'to‘qqiz', 'девять', 'nine'],
  ['تَطَهَّرْ', 'poklanmoq', 'очищаться', 'to purify oneself'],
  ['تَعْثَ', 'buzg‘unchilik qilmoq', 'бесчинствовать', 'to spread corruption'],
  ['تَفْصِيل', 'batafsil bayon', 'подробное разъяснение', 'detailed explanation'],
  ['تَقْدِير', 'o‘lchov, taqdir belgilash', 'предопределение', 'determination, decree'],
  ['تَقَرَّ', 'qaror topmoq, quvonmoq (ko‘z)', 'находить покой', 'to be comforted, to settle'],
  ['تَقَطَّعَ', 'bo‘linib ketmoq, uzilmoq', 'разрываться', 'to be cut off, to split'],
  ['تَقَلُّب', 'aylanish, harakat', 'перемещение', 'moving about, fluctuation'],
  ['تَواصَ', 'bir-biriga vasiyat qilmoq', 'заповедовать друг другу', 'to enjoin one another'],
  ['ثَقِيل', 'og‘ir', 'тяжёлый', 'heavy'],
  ['ثَمَر', 'mevalar, hosil', 'плоды', 'fruit'],
  ['جاثِم', 'cho‘kkalab qolgan, halok bo‘lgan', 'поверженный ниц', 'lying prostrate, fallen'],
  ['جَرَم', 'shubhasiz, albatta', 'несомненно', 'no doubt, surely'],
  ['جَهْد', 'kuch, imkon', 'усилие', 'utmost effort'],
  ['جَهَرَ', 'baland ovozda aytmoq', 'говорить громко', 'to speak aloud'],
  ['جَواب', 'javob', 'ответ', 'answer'],
  ['حاكِم', 'hukm qiluvchi, hokim', 'судья', 'judge, ruler'],
  ['حَبَّة', 'don, urug‘', 'зерно', 'grain, seed'],
  ['حِجْر', 'to‘siq; aql; taqiq', 'преграда; разум', 'barrier; understanding; forbidden'],
  ['حَرِيق', 'yong‘in, olov', 'пожар, пламя', 'burning fire'],
  ['حِلّ', 'halol; yashash joyi', 'дозволенное; местопребывание', 'lawful; dwelling'],
  ['حِمار', 'eshak', 'осёл', 'donkey'],
  ['حُمِّلَ', 'yuklatilmoq', 'быть нагруженным', 'to be laden with'],
  ['حَوارِيّ', 'havoriy, sodiq shogird', 'апостол, ученик', 'disciple'],
  ['حُوت', 'baliq', 'рыба, кит', 'fish, whale'],
  ['خاطِئ', 'xato qiluvchi, gunohkor', 'грешник', 'sinner, one in error'],
  ['خالِصَة', 'xolis, sof (ayol shakli)', 'исключительная, чистая', 'exclusive, pure (fem.)']
] as const
