import type { Gloss } from './glossary-types'

/** Quranic lemmas ranked 300–549 by frequency. See glossary-types.ts for conventions. */
export const WORD_GLOSSES_300: readonly Gloss[] = [
  ['سُلْطان', 'hujjat, dalil; hokimiyat', 'довод; власть', 'authority, proof'],
  ['صَدَّ', 'to‘smoq, qaytarmoq', 'отвращать, препятствовать', 'to turn away, to hinder'],
  ['عَصا', 'hassa, tayoq', 'посох', 'staff, stick'],
  ['فاسِق', 'fosiq, itoatsiz', 'нечестивец', 'defiantly disobedient'],
  ['كُفْر', 'kufr, inkor', 'неверие', 'disbelief'],
  ['مُسْتَقِيم', 'to‘g‘ri, mustaqim', 'прямой', 'straight'],
  ['نَجَّى', 'qutqarmoq', 'спасать', 'to save, to deliver'],
  ['نَعَم', 'chorva mollari', 'скот', 'cattle, livestock'],
  ['يَحْزُن', 'g‘amgin qilmoq', 'печалить', 'to grieve'],
  ['أَحْسَن', 'eng go‘zal, yaxshiroq', 'наилучший', 'best, most beautiful'],
  ['ذاقُ', 'tatib ko‘rmoq', 'вкушать', 'to taste'],
  ['رَدَّ', 'qaytarmoq', 'возвращать, отвергать', 'to return, to reject'],
  ['أُمّ', 'ona; asos', 'мать; основа', 'mother; source'],
  ['إِثْم', 'gunoh', 'грех', 'sin'],
  ['اخْتَلَفَ', 'ixtilof qilmoq, farq qilmoq', 'расходиться во мнениях', 'to differ, to dispute'],
  ['اسْتَوَى', 'barobar bo‘lmoq; qaror topmoq', 'быть равным; утвердиться', 'to be equal; to establish'],
  ['بَيَّنُ', 'bayon qilmoq, ochiq qilmoq', 'разъяснять', 'to make clear'],
  ['حِين', 'vaqt, muddat', 'время, срок', 'time, period'],
  ['ذَهَبَ', 'ketmoq', 'уходить', 'to go, to depart'],
  ['سَجَدَ', 'sajda qilmoq', 'падать ниц', 'to prostrate'],
  ['مَتاع', 'foyda, matoh, o‘tkinchi ne’mat', 'пользование, блага', 'enjoyment, provision'],
  ['مُرْسَل', 'yuborilgan, elchi', 'посланный', 'sent one, messenger'],
  ['نَسِيَ', 'unutmoq', 'забывать', 'to forget'],
  ['نَصِير', 'yordamchi', 'помощник', 'helper'],
  ['آلاء', 'ne’matlar', 'блага, милости', 'favours, bounties'],
  ['ابْتَغَى', 'izlamoq, talab qilmoq', 'искать, стремиться', 'to seek'],
  ['فِتْنَة', 'fitna, sinov', 'испытание, смута', 'trial, tribulation'],
  ['مَرْيَم', 'Maryam', 'Марьям', 'Mary'],
  ['حَرام', 'harom, taqiqlangan; muqaddas', 'запретный; священный', 'forbidden; sacred'],
  ['شَمْس', 'quyosh', 'солнце', 'sun'],
  ['فَرِيق', 'guruh, firqa', 'группа, партия', 'group, party'],
  ['قامَ', 'turmoq, qoim bo‘lmoq', 'вставать', 'to stand, to rise'],
  ['كَذِب', 'yolg‘on', 'ложь', 'lie, falsehood'],
  ['كَلّا', 'yo‘q, aslo!', 'нет же!', 'nay, by no means'],
  ['أَعْرَضَ', 'yuz o‘girmoq', 'отворачиваться', 'to turn away'],
  ['خاسِر', 'ziyon ko‘ruvchi', 'потерпевший убыток', 'loser'],
  ['ذُرِّيَّة', 'zurriyot, nasl', 'потомство', 'offspring, progeny'],
  ['زَكاة', 'zakot; poklanish', 'закят, очищение', 'zakat, purification'],
  ['عاقِبَة', 'oqibat, natija', 'конец, исход', 'outcome, end'],
  ['كاذِب', 'yolg‘onchi', 'лжец', 'liar'],
  ['كَفَى', 'kifoya qilmoq, yetarli bo‘lmoq', 'быть достаточным', 'to suffice'],
  ['نَهَى', 'qaytarmoq, man qilmoq', 'запрещать', 'to forbid'],
  ['أَشَدّ', 'eng qattiq, kuchliroq', 'сильнее, суровее', 'more severe, stronger'],
  ['إِذًا', 'unda, u holda', 'тогда', 'then, in that case'],
  ['حَسَنَة', 'yaxshilik, savob', 'доброе дело', 'good deed'],
  ['حَيْث', 'qayerda, qayerdaki', 'где, откуда', 'where, wherever'],
  ['كَأَنّ', 'go‘yo, xuddi', 'как будто', 'as if'],
  ['نَفَعَ', 'foyda bermoq', 'приносить пользу', 'to benefit'],
  ['واحِدَة', 'yagona, bitta (ayol)', 'одна', 'one, single (fem.)'],
  ['حُكْم', 'hukm, hikmat', 'решение, мудрость', 'judgement, wisdom'],
  ['ساءَ', 'yomon bo‘lmoq, xafa qilmoq', 'быть скверным', 'to be evil, to grieve'],
  ['شَرّ', 'yomonlik, sharr', 'зло', 'evil'],
  ['طَيِّبَة', 'pok, yaxshi (ayol)', 'благая, чистая', 'good, pure (fem.)'],
  ['عاد', 'Od qavmi', 'адиты', 'Aad (a people)'],
  ['عَسَى', 'shoyad, balki', 'быть может', 'perhaps, it may be'],
  ['قُوَّة', 'quvvat, kuch', 'сила', 'strength, power'],
  ['كَرِيم', 'karamli, ulug‘', 'благородный, щедрый', 'noble, generous'],
  ['لَبِثَ', 'turmoq, qolmoq', 'оставаться', 'to remain, to stay'],
  ['مَلَأ', 'kattalar, ashroflar', 'знать, вожди', 'chiefs, eminent ones'],
  ['واحِد', 'yagona, bir', 'один, единственный', 'one, single'],
  ['وَلَّى', 'yuz o‘girmoq, orqasiga qaytmoq', 'отворачиваться', 'to turn away'],
  ['أَبْصَرَ', 'ko‘rmoq, ko‘rsatmoq', 'видеть, показывать', 'to see, to make see'],
  ['جُند', 'lashkar, qo‘shin', 'войско', 'army, host'],
  ['رَجُل', 'erkak, kishi', 'мужчина', 'man'],
  ['رِيح', 'shamol', 'ветер', 'wind'],
  ['عَرْش', 'arsh, taxt', 'трон', 'throne'],
  ['عَهْد', 'ahd, va’da', 'завет, договор', 'covenant, pledge'],
  ['نَبَأ', 'xabar', 'весть', 'news, tidings'],
  ['أَبَدًا', 'abadiy, hech qachon', 'вечно, никогда', 'forever, never'],
  ['أَصْبَحَ', 'tongni qarshilamoq; bo‘lib qolmoq', 'наступать утром; становиться', 'to become, to be in the morning'],
  ['أَصْلَحَ', 'isloh qilmoq, tuzatmoq', 'исправлять', 'to set right, to reform'],
  ['أَغْنَتْ', 'foyda bermoq, boy qilmoq', 'избавлять, обогащать', 'to avail, to enrich'],
  ['أَنَّى', 'qanday, qayerdan', 'как, откуда', 'how, whence'],
  ['اسْتَجابَ', 'javob bermoq, ijobat qilmoq', 'отвечать, внимать', 'to respond, to answer'],
  ['حَدِيث', 'so‘z, hikoya, xabar', 'речь, повествование', 'speech, narration'],
  ['رِجال', 'erkaklar', 'мужчины', 'men'],
  ['رَحِمَ', 'rahm qilmoq', 'миловать', 'to have mercy'],
  ['سِحْر', 'sehr', 'колдовство', 'magic, sorcery'],
  ['مُؤْمِنَة', 'mo‘mina (ayol)', 'верующая', 'believing woman'],
  ['مَسْجِد', 'masjid, sajda joyi', 'мечеть', 'mosque, place of prostration'],
  ['مَصِير', 'qaytar joy, oqibat', 'исход, место возвращения', 'destination, final return'],
  ['مَغْفِرَة', 'mag‘firat, kechirim', 'прощение', 'forgiveness'],
  ['أَفْلَحَ', 'najot topmoq, yutmoq', 'преуспевать', 'to succeed, to prosper'],
  ['باب', 'eshik, darvoza', 'дверь, врата', 'door, gate'],
  ['جاهَدَ', 'jihod qilmoq, harakat qilmoq', 'усердствовать, бороться', 'to strive, to struggle'],
  ['سَواء', 'barobar, teng; to‘g‘ri', 'равный; ровный', 'equal; even'],
  ['عَفا', 'afv etmoq, kechirmoq', 'прощать', 'to pardon'],
  ['غافِل', 'g‘ofil, beparvo', 'беспечный', 'heedless'],
  ['قَدَّمَ', 'oldinga surmoq, taqdim qilmoq', 'выдвигать, представлять', 'to put forward, to send ahead'],
  ['قَمَر', 'oy', 'луна', 'moon'],
  ['لُوط', 'Lut', 'Лут', 'Lot'],
  ['مَكان', 'joy, makon', 'место', 'place'],
  ['مُنافِق', 'munofiq', 'лицемер', 'hypocrite'],
  ['يُوسُف', 'Yusuf', 'Юсуф', 'Joseph'],
  ['آل', 'oila, avlod', 'семья, род', 'family, house of'],
  ['أَجْمَع', 'hammasi, barchasi', 'все вместе', 'all together'],
  ['امْرَأَت', 'ayol, xotin', 'женщина, жена', 'woman, wife'],
  ['باطِل', 'botil, yolg‘on', 'ложь, тщета', 'falsehood, vanity'],
  ['ثَمُود', 'Samud qavmi', 'самудяне', 'Thamud (a people)'],
  ['جَحِيم', 'jahim, do‘zax olovi', 'адский огонь', 'blazing fire, Hellfire'],
  ['خَوْف', 'qo‘rquv', 'страх', 'fear'],
  ['زَيَّنَ', 'bezamoq, chiroyli ko‘rsatmoq', 'украшать', 'to adorn, to make attractive'],
  ['شَهادَة', 'guvohlik, shahodat', 'свидетельство', 'testimony, witnessing'],
  ['قَرِيب', 'yaqin', 'близкий', 'near, close'],
  ['كَيْد', 'hiyla, makr', 'козни, хитрость', 'plot, scheme'],
  ['ماذا', 'nima', 'что', 'what'],
  ['آدَم', 'Odam', 'Адам', 'Adam'],
  ['بَأْس', 'kuch; azob, balo', 'мощь; бедствие', 'might; hardship'],
  ['بَعِيد', 'uzoq', 'далёкий', 'far, distant'],
  ['بَغَى', 'haddan oshmoq, zulm qilmoq', 'притеснять, преступать', 'to transgress, to oppress'],
  ['جادَلُ', 'bahslashmoq, tortishmoq', 'спорить', 'to dispute, to argue'],
  ['جُناح', 'gunoh, ayb', 'грех, вина', 'blame, sin'],
  ['خَلا', 'o‘tmoq, bo‘sh qolmoq', 'проходить, оставаться наедине', 'to pass away, to be alone'],
  ['عِيسَى', 'Iso', 'Иса', 'Jesus'],
  ['قَدَرَ', 'qodir bo‘lmoq, o‘lchamoq', 'мочь, определять меру', 'to be able, to measure out'],
  ['لِسان', 'til (a’zo va nutq)', 'язык', 'tongue, language'],
  ['مِيثاق', 'mustahkam ahd', 'завет, договор', 'firm covenant'],
  ['يَشْعُرُ', 'sezmoq, tuymoq', 'чувствовать, осознавать', 'to perceive, to sense'],
  ['أَكْبَر', 'kattaroq, eng ulug‘', 'больший, величайший', 'greater, greatest'],
  ['أُنثَى', 'urg‘ochi, ayol', 'женщина, самка', 'female'],
  ['إِيّا', 'faqat senga (ta’kid olmoshi)', 'только Тебя (местоимение)', 'you alone (emphatic pronoun)'],
  ['تَوَفَّى', 'jonini olmoq, to‘liq olmoq', 'упокоить, забрать', 'to take in full, to cause to die'],
  ['حَيّ', 'tirik', 'живой', 'living, alive'],
  ['طائِفَة', 'toifa, guruh', 'группа', 'group, party'],
  ['طَعام', 'taom, ovqat', 'еда, пища', 'food'],
  ['غَنِيّ', 'boy, behojat', 'богатый, самодостаточный', 'rich, self-sufficient'],
  ['كادَ', 'yaqin bo‘lmoq, oz qolmoq', 'быть близким к', 'to be about to, to almost'],
  ['لِقاء', 'uchrashuv, mulaqot', 'встреча', 'meeting, encounter'],
  ['وَراء', 'orqasida, keyin', 'позади, за', 'behind, beyond'],
  ['وَكِيل', 'vakil, ishonchli homiy', 'попечитель', 'trustee, guardian'],
  ['أَذِنَ', 'izn bermoq, ruxsat bermoq', 'позволять', 'to permit'],
  ['أَنجَى', 'qutqarmoq', 'спасать', 'to save, to rescue'],
  ['إِمّا', 'yo, agar', 'либо, если', 'either, if'],
  ['بَدَّلَ', 'almashtirmoq, o‘zgartirmoq', 'заменять', 'to change, to replace'],
  ['ذِكْرَى', 'eslatma, ibrat', 'напоминание', 'reminder'],
  ['ساجِد', 'sajda qiluvchi', 'падающий ниц', 'one prostrating'],
  ['سَبْع', 'yetti', 'семь', 'seven'],
  ['ظُلُمَة', 'zulmat, qorong‘ulik', 'тьма', 'darkness'],
  ['فَتَنُ', 'sinamoq, fitnaga solmoq', 'испытывать, искушать', 'to test, to tempt'],
  ['فُلْك', 'kema', 'корабль', 'ship'],
  ['قَرْن', 'avlod, asr', 'поколение, век', 'generation, era'],
  ['لَعَنَ', 'la’natlamoq', 'проклинать', 'to curse'],
  ['مِسْكِين', 'miskin, kambag‘al', 'бедняк', 'poor person, needy'],
  ['يَتِيم', 'yetim', 'сирота', 'orphan'],
  ['أَذاقَ', 'tattirmoq', 'давать вкусить', 'to make taste'],
  ['أَسْلَمَ', 'taslim bo‘lmoq, islom qabul qilmoq', 'предаться, принять ислам', 'to submit, to accept Islam'],
  ['بَرّ', 'yaxshilik, taqvo; quruqlik', 'благочестие; суша', 'righteousness; land'],
  ['بَلَى', 'yo‘q, aksincha (tasdiq)', 'нет же, напротив', 'yes indeed, rather'],
  ['جَمَعَ', 'to‘plamoq', 'собирать', 'to gather'],
  ['جِنّ', 'jinlar', 'джинны', 'jinn'],
  ['خَلْف', 'orqasida, keyin', 'позади, после', 'behind, after'],
  ['دُعاء', 'duo, chaqiriq', 'мольба, зов', 'supplication, call'],
  ['رَفَعَ', 'ko‘tarmoq', 'поднимать', 'to raise'],
  ['ساحِر', 'sehrgar', 'колдун', 'magician'],
  ['سَخَّرَ', 'bo‘ysundirmoq, xizmatga solmoq', 'подчинять', 'to subject, to make serve'],
  ['سَمْع', 'eshitish, quloq', 'слух', 'hearing'],
  ['لَدَى', 'yonida, huzurida', 'у, при', 'with, at'],
  ['مَأْوَى', 'boshpana, maskan', 'убежище, обитель', 'refuge, abode'],
  ['مَكَرَ', 'makr qilmoq, hiyla ishlatmoq', 'строить козни', 'to plot, to scheme'],
  ['نَصْر', 'yordam, g‘alaba', 'помощь, победа', 'help, victory'],
  ['وَهَبَ', 'hadya qilmoq, bermoq', 'даровать', 'to grant, to bestow'],
  ['يَرْجُوا۟', 'umid qilmoq', 'надеяться', 'to hope for'],
  ['أَحْسَنَ', 'yaxshilik qilmoq, chiroyli qilmoq', 'делать добро', 'to do good, to perfect'],
  ['أَعْمَى', 'ko‘r', 'слепой', 'blind'],
  ['أَماتَ', 'o‘ldirmoq', 'умерщвлять', 'to cause to die'],
  ['اسْتُهْزِئَ', 'masxara qilinmoq', 'быть осмеянным', 'to be mocked'],
  ['اشْتَرَى', 'sotib olmoq, almashmoq', 'покупать, вымéнивать', 'to buy, to exchange'],
  ['حَسَن', 'yaxshi, go‘zal', 'хороший, прекрасный', 'good, fair'],
  ['رُوح', 'ruh', 'дух', 'spirit'],
  ['شاهِد', 'guvoh', 'свидетель', 'witness'],
  ['شَهْر', 'oy (kalendar)', 'месяц', 'month'],
  ['ظَنّ', 'gumon, taxmin', 'предположение', 'assumption, conjecture'],
  ['كَتَمَ', 'yashirmoq', 'скрывать', 'to conceal'],
  ['كَم', 'nechta, qancha', 'сколько', 'how many'],
  ['مُسَمًّى', 'belgilangan, nomlangan', 'назначенный', 'specified, appointed'],
  ['مَشَ', 'yurmoq', 'ходить', 'to walk'],
  ['مُفْسِد', 'buzg‘unchi, fasod qiluvchi', 'сеющий нечестие', 'corrupter'],
  ['مُكَذِّب', 'yolg‘onga chiqaruvchi', 'считающий ложью', 'denier'],
  ['نَصِيب', 'ulush, nasiba', 'доля', 'share, portion'],
  ['وَضَعَ', 'qo‘ymoq, tushirmoq', 'класть, снимать', 'to place, to lay down'],
  ['أَحَلَّ', 'halol qilmoq, ruxsat bermoq', 'дозволять', 'to make lawful'],
  ['أَعَدَّ', 'tayyorlamoq', 'готовить', 'to prepare'],
  ['أَقْسَمُ', 'qasam ichmoq', 'клясться', 'to swear an oath'],
  ['أَمِنَ', 'omon bo‘lmoq, xotirjam bo‘lmoq', 'быть в безопасности', 'to be safe, to feel secure'],
  ['أَنشَأَ', 'paydo qilmoq, bunyod etmoq', 'создавать, взращивать', 'to bring into being'],
  ['أَوْفَى', 'to‘liqroq, ahdga vafo qiluvchi', 'наиболее верный', 'most faithful, fulfilling'],
  ['بَلَوْ', 'sinamoq', 'испытывать', 'to test, to try'],
  ['حِزْب', 'guruh, hizb', 'партия, группа', 'party, faction'],
  ['حَقَّ', 'haq bo‘lmoq, sodir bo‘lmoq', 'оказаться истиной, сбыться', 'to be justified, to come true'],
  ['حِكْمَة', 'hikmat', 'мудрость', 'wisdom'],
  ['حَمِيم', 'qaynoq suv; yaqin do‘st', 'кипяток; близкий друг', 'scalding water; close friend'],
  ['سَبَقَ', 'o‘zib ketmoq, oldin bo‘lmoq', 'опережать', 'to precede, to outstrip'],
  ['سَعَى', 'harakat qilmoq, yugurmoq', 'стремиться', 'to strive, to hasten'],
  ['صابِر', 'sabrli', 'терпеливый', 'patient one'],
  ['ظُلْم', 'zulm', 'несправедливость', 'injustice, wrongdoing'],
  ['عَرَفَ', 'tanimoq, bilmoq', 'знать, узнавать', 'to know, to recognise'],
  ['عِقاب', 'jazo', 'наказание', 'penalty, punishment'],
  ['قَصَّ', 'hikoya qilmoq', 'рассказывать', 'to relate, to narrate'],
  ['كَلَّمَ', 'gapirmoq, so‘zlashmoq', 'говорить с', 'to speak to'],
  ['مَرَّة', 'marta, safar', 'раз', 'time, occasion'],
  ['هارُون', 'Horun', 'Харун', 'Aaron'],
  ['أَقْرَب', 'yaqinroq', 'ближе', 'nearer'],
  ['أَيْن', 'qayerda', 'где', 'where'],
  ['اسْتَعْجَلَ', 'shoshiltirmoq, tezlashtirishni so‘ramoq', 'торопить', 'to hasten, to seek to hurry'],
  ['زِينَة', 'ziynat, bezak', 'украшение', 'adornment'],
  ['شَجَرَة', 'daraxt', 'дерево', 'tree'],
  ['ضُرّ', 'zarar, ziyon', 'вред', 'harm, adversity'],
  ['طَيْر', 'qush', 'птица', 'bird'],
  ['فَوْز', 'yutuq, muvaffaqiyat', 'успех, победа', 'success, triumph'],
  ['مُصَدِّق', 'tasdiqlovchi', 'подтверждающий', 'confirming'],
  ['مُعْرِض', 'yuz o‘giruvchi', 'отворачивающийся', 'one turning away'],
  ['مَكْر', 'makr, hiyla', 'козни', 'plot, scheming'],
  ['نَفَخَ', 'puflamoq', 'дуть', 'to blow'],
  ['يَضُرَّ', 'zarar yetkazmoq', 'вредить', 'to harm'],
  ['يَفْقَهُ', 'chuqur tushunmoq', 'постигать', 'to comprehend'],
  ['أُخْفِيَ', 'yashirilmoq', 'быть скрытым', 'to be hidden'],
  ['أُذُن', 'quloq', 'ухо', 'ear'],
  ['أَسَرَّ', 'sir tutmoq, pichirlamoq', 'таить, шептать', 'to conceal, to whisper'],
  ['أُعِيدُ', 'qaytarmoq', 'возвращать', 'to bring back, to repeat'],
  ['أَمْسَكَ', 'ushlab turmoq, tutmoq', 'удерживать', 'to hold, to withhold'],
  ['إِنس', 'insonlar', 'люди', 'mankind'],
  ['تَبَيَّنَ', 'ravshan bo‘lmoq', 'становиться ясным', 'to become clear'],
  ['تَوْراة', 'Tavrot', 'Тора', 'Torah'],
  ['دابَّة', 'jonivor, hayvon', 'животное, тварь', 'creature, beast'],
  ['دُبُر', 'orqa, ort', 'спина, тыл', 'back, rear'],
  ['دَرَجَة', 'daraja', 'степень', 'degree, rank'],
  ['ذَكَر', 'erkak', 'мужчина, самец', 'male'],
  ['ذُكِّرَ', 'eslatilmoq', 'быть напомненным', 'to be reminded'],
  ['رَأْس', 'bosh', 'голова', 'head'],
  ['رَيْب', 'shubha', 'сомнение', 'doubt'],
  ['عادَ', 'qaytmoq', 'возвращаться', 'to return'],
  ['عالِم', 'bilguvchi, olim', 'знающий', 'knower, learned'],
  ['لَدُن', 'huzuridan, tomonidan', 'от, со стороны', 'from (the presence of)'],
  ['مَتَّعْ', 'bahramand qilmoq, foydalantirmoq', 'наделять благами', 'to grant enjoyment'],
  ['مُنكَر', 'munkar, yomon ish', 'порицаемое', 'wrong, reprehensible'],
  ['مَوْلَى', 'homiy, xo‘jayin, do‘st', 'покровитель, господин', 'protector, master'],
  ['نِعْمَ', 'naqadar yaxshi', 'как прекрасно', 'excellent is'],
  ['وَفَّى', 'to‘liq bermoq, ado etmoq', 'воздавать сполна', 'to pay in full'],
  ['أَحاطَ', 'qamrab olmoq', 'охватывать', 'to encompass'],
  ['أَدْرَى', 'bildirmoq, xabar bermoq', 'давать знать', 'to make known'],
  ['أُغْرِقُ', 'g‘arq qilinmoq', 'быть потопленным', 'to be drowned'],
  ['أَنْعَمَ', 'ne’mat bermoq', 'даровать милость', 'to bestow favour'],
  ['أَهْواء', 'havoyi nafslar, mayl', 'страсти, прихоти', 'desires, whims'],
  ['إِسْحاق', 'Ishoq', 'Исхак', 'Isaac'],
  ['انقَلَبَ', 'qaytmoq, ag‘darilmoq', 'возвращаться, переворачиваться', 'to return, to be turned about'],
  ['بَطْن', 'qorin, ich', 'живот, чрево', 'belly, womb'],
  ['بِنْت', 'qiz', 'дочь', 'daughter'],
  ['تَأْوِيل', 'ta’vil, sharh', 'толкование', 'interpretation'],
  ['تُراب', 'tuproq', 'земля, прах', 'dust, earth'],
  ['تَقْوَى', 'taqvo', 'богобоязненность', 'God-consciousness, piety']
] as const
