import type { Gloss } from './glossary-types'

/** Quranic lemmas ranked 1301-1800 by frequency. See glossary-types.ts for conventions. */
export const WORD_GLOSSES_1300: readonly Gloss[] = [
  ['خانُ', 'xiyonat qilmoq', 'изменять, предавать', 'to betray'],
  ['خاوِيَة', 'bo‘m-bo‘sh, vayron', 'пустая, разрушенная', 'empty, fallen down'],
  ['خَتَمَ', 'muhrlamoq', 'запечатывать', 'to seal'],
  ['خُرُوج', 'chiqish', 'выход', 'going out, exit'],
  ['خَصِيم', 'nizolashuvchi, raqib', 'спорщик, противник', 'disputant, adversary'],
  ['خُضْر', 'yashillar', 'зелёные', 'green ones'],
  ['خَطْب', 'ish, holat', 'дело, обстоятельство', 'matter, affair'],
  ['خُطُوَة', 'qadam', 'шаг', 'footstep'],
  ['خَلَفَ', 'ortidan kelmoq, o‘rin bosmoq', 'приходить на смену', 'to succeed, come after'],
  ['خِنزِير', 'cho‘chqa', 'свинья', 'pig, swine'],
  ['خَيْل', 'otlar', 'кони', 'horses'],
  ['دَرَسُ', 'o‘rganmoq, o‘qimoq', 'изучать', 'to study'],
  ['دَفَعْ', 'qaytarmoq, itarmoq', 'отражать, отталкивать', 'to repel, push back'],
  ['دَيْن', 'qarz', 'долг', 'debt'],
  ['ذُبِحَ', 'so‘yilmoq', 'быть зарезанным', 'to be slaughtered'],
  ['رَجَمْ', 'toshbo‘ron qilmoq', 'побивать камнями', 'to stone'],
  ['رَشَد', 'to‘g‘ri yo‘l, hidoyat', 'правильный путь', 'right guidance'],
  ['رُعْب', 'qo‘rquv, dahshat', 'ужас, страх', 'terror, dread'],
  ['رَقِيب', 'kuzatuvchi, nazoratchi', 'наблюдатель, страж', 'watcher, guardian'],
  ['زُوِّجَتْ', 'juftlashtirilmoq', 'быть соединённым в пары', 'to be paired'],
  ['زَيْتُون', 'zaytun', 'олива', 'olive'],
  ['سَلَفَ', 'o‘tib ketmoq (avval)', 'миновать, предшествовать', 'to have passed before'],
  ['سَلَم', 'taslim bo‘lish, sulh', 'мир, покорность', 'peace, submission'],
  ['سَوِيّ', 'tekis, benuqson', 'ровный, здоровый', 'sound, even'],
  ['سُيِّرَتْ', 'yurgizilmoq, ko‘chirilmoq', 'быть приведённым в движение', 'to be set in motion'],
  ['شارِب', 'ichuvchi', 'пьющий', 'drinker'],
  ['شاعِر', 'shoir', 'поэт', 'poet'],
  ['شُحّ', 'baxillik, ziqnalik', 'скупость', 'greed, stinginess'],
  ['شَرَحَ', 'kengaytirmoq, ochmoq', 'раскрывать, расширять', 'to expand, open up'],
  ['شِرْك', 'shirk, sherik qo‘shish', 'многобожие', 'associating partners with God'],
  ['شَطْر', 'tomon, yo‘nalish', 'сторона, направление', 'direction'],
  ['صاغِر', 'xor, past', 'униженный', 'humbled, lowly'],
  ['صُبْح', 'tong, subh', 'утро, рассвет', 'morning, dawn'],
  ['صِدِّيق', 'o‘ta rostgo‘y, siddiq', 'правдивейший', 'most truthful'],
  ['صَيْد', 'ov', 'охота, добыча', 'game, hunting'],
  ['ضَيْف', 'mehmon', 'гость', 'guest'],
  ['طائِر', 'qush; qismat', 'птица; знамение', 'bird; omen'],
  ['طَرَف', 'chekka, tomon', 'край, сторона', 'end, side'],
  ['طَرِيقَة', 'yo‘l, tariqa', 'путь', 'way, path'],
  ['طَعِمُ', 'yemoq, tatib ko‘rmoq', 'есть, вкушать', 'to eat, taste'],
  ['طُمِسَتْ', 'o‘chirilmoq', 'быть стёртым', 'to be effaced'],
  ['ظَلّام', 'o‘ta zolim', 'крайне несправедливый', 'utterly unjust'],
  ['عَتَ', 'kibrlanmoq, haddan oshmoq', 'превозноситься', 'to be insolent'],
  ['عَجَب', 'hayrat, ajablanish', 'удивление', 'wonder, amazement'],
  ['عَجَّلَ', 'shoshiltirmoq', 'торопить', 'to hasten'],
  ['عَجِلَ', 'shoshilmoq', 'спешить', 'to be hasty'],
  ['عَزْم', 'qat’iyat, azm', 'решимость', 'determination, resolve'],
  ['عُسْر', 'qiyinchilik', 'трудность', 'hardship'],
  ['عَطاء', 'ato, in’om', 'дар', 'gift, bestowal'],
  ['عَفُوّ', 'ko‘p kechiruvchi', 'много прощающий', 'much-pardoning'],
  ['عَقَرَ', 'so‘ymoq, oyog‘ini kesmoq', 'подрезать поджилки, зарезать', 'to hamstring, slaughter'],
  ['عَلَقَة', 'laxta qon, ilashgan narsa', 'сгусток крови', 'clinging clot'],
  ['غَد', 'erta, ertaga', 'завтра', 'tomorrow'],
  ['غُدُوّ', 'ertalab', 'утро', 'morning'],
  ['غُرْفَة', 'xona, yuqori maskan', 'горница', 'lofty chamber'],
  ['غَفّار', 'ko‘p mag‘firat qiluvchi', 'много прощающий', 'oft-forgiving'],
  ['غَفْلَة', 'g‘aflat, beparvolik', 'беспечность', 'heedlessness'],
  ['غَلَّ', 'kishanlamoq; xiyonat qilmoq', 'заковывать; утаивать', 'to shackle; to defraud'],
  ['فَرَّط', 'e’tiborsiz qoldirmoq', 'упускать, пренебрегать', 'to neglect'],
  ['فَرَقْ', 'ajratmoq, yormoq', 'разделять', 'to part, divide'],
  ['فَصَلَ', 'ajratmoq, yo‘lga chiqmoq', 'отделять, выступать', 'to separate, set out'],
  ['فَوْج', 'guruh, to‘da', 'группа, толпа', 'group, troop'],
  ['قارِعَة', 'urib turuvchi falokat, qiyomat', 'поражающее бедствие', 'the striking calamity'],
  ['قائِمَة', 'turuvchi, tik', 'стоящая', 'standing'],
  ['قَبَضْ', 'ushlamoq, tortmoq', 'хватать, сжимать', 'to grasp, seize'],
  ['قَرَّبَ', 'yaqinlashtirmoq', 'приближать', 'to bring near'],
  ['قَيِّم', 'to‘g‘ri, barqaror', 'правильный, устойчивый', 'upright, established'],
  ['كافَّة', 'hammasi, barchasi', 'все, целиком', 'all together'],
  ['كَذّاب', 'o‘ta yolg‘onchi', 'отъявленный лжец', 'great liar'],
  ['كَرْه', 'istamaslik, majburlik', 'нежелание, принуждение', 'dislike, compulsion'],
  ['كَفّار', 'o‘ta noshukur, kofir', 'неблагодарный, неверный', 'ungrateful disbeliever'],
  ['كَلْب', 'it', 'собака', 'dog'],
  ['كَوْكَب', 'yulduz, sayyora', 'звезда', 'star, planet'],
  ['لَوْح', 'lavh, taxta', 'скрижаль, доска', 'tablet, board'],
  ['مُبْطِل', 'botilga ergashuvchi', 'приверженец лжи', 'one who follows falsehood'],
  ['مُتْرَف', 'hashamatga botgan, erkatoy', 'изнеженный роскошью', 'affluent, luxury-spoiled'],
  ['مَحِيص', 'qochib qutulish joyi', 'убежище, спасение', 'escape, refuge'],
  ['مُخْرَج', 'chiqarilgan; chiqish joyi', 'выведенный; выход', 'brought out; exit'],
  ['مَرْضات', 'rozilik', 'благоволение', 'good pleasure'],
  ['مِرْيَة', 'shubha', 'сомнение', 'doubt'],
  ['مُسْتَضْعَف', 'zaif sanalgan, ezilgan', 'угнетённый', 'oppressed, deemed weak'],
  ['مَسْئُول', 'mas’ul, so‘raladigan', 'ответственный', 'answerable, questioned'],
  ['مُشْرِكَة', 'mushrika ayol', 'многобожница', 'idolatress'],
  ['مُصْبِح', 'tongga kiruvchi', 'встречающий утро', 'entering upon morning'],
  ['مِصْر', 'Misr; shahar', 'Египет; город', 'Egypt; a city'],
  ['مُصْلِح', 'isloh qiluvchi, tuzatuvchi', 'исправляющий', 'reformer, one who sets right'],
  ['مُطَهَّرَة', 'poklangan', 'очищенная', 'purified'],
  ['مَكانَت', 'o‘rin, maqom', 'место, положение', 'place, position'],
  ['مُكْرَم', 'ulug‘langan, izzatli', 'почитаемый', 'honoured'],
  ['مَلُوم', 'malomat qilingan', 'порицаемый', 'blameworthy'],
  ['مُنافِقَة', 'munofiqa ayol', 'лицемерка', 'hypocrite woman'],
  ['مُنذَر', 'ogohlantirilgan', 'предупреждённый', 'one warned'],
  ['مُنزِل', 'nozil qiluvchi', 'ниспосылающий', 'one who sends down'],
  ['مَهْد', 'beshik, tekis maskan', 'колыбель, ложе', 'cradle, resting place'],
  ['مُهْلِك', 'halok qiluvchi', 'губящий', 'destroyer'],
  ['مُوقِن', 'qat’iy ishonuvchi', 'убеждённый', 'one certain in faith'],
  ['مَيْت', 'o‘lik', 'мёртвый', 'dead'],
  ['نادِم', 'pushaymon', 'сожалеющий', 'regretful'],
  ['ناظِر', 'qaraydigan, kutuvchi', 'смотрящий', 'looking, beholding'],
  ['نُبُوَّة', 'payg‘ambarlik', 'пророчество', 'prophethood'],
  ['نُشُور', 'tirilish', 'воскрешение', 'resurrection'],
  ['نَصَحُ', 'nasihat qilmoq', 'искренне советовать', 'to advise sincerely'],
  ['نُفُور', 'nafrat, qochish', 'отвращение, бегство', 'aversion, flight'],
  ['نِكاح', 'nikoh', 'брак', 'marriage'],
  ['نَكِير', 'inkor, jazo', 'отрицание, кара', 'rejection, punishment'],
  ['هَلَكَ', 'halok bo‘lmoq', 'погибать', 'to perish'],
  ['وازِرَة', 'yuk ko‘taruvchi (jon)', 'несущая ношу', 'bearer of burden'],
  ['وُسْع', 'imkoniyat, qudrat', 'возможность', 'capacity'],
  ['وَهَنَ', 'zaiflashmoq', 'слабеть', 'to weaken'],
  ['يَبْخَسْ', 'kamaytirmoq, kam bermoq', 'убавлять', 'to diminish, shortchange'],
  ['يَجْهَلُ', 'johillik qilmoq', 'быть невежественным', 'to be ignorant'],
  ['يَحْيَى', 'Yahyo', 'Яхья (Иоанн)', 'John (Yahya)'],
  ['يَرْكَعُ', 'ruku qilmoq, egilmoq', 'совершать поясной поклон', 'to bow down'],
  ['يَرْهَقُ', 'qoplamoq, bosmoq', 'покрывать, настигать', 'to cover, oppress'],
  ['يَشْفَعُ', 'shafoat qilmoq', 'заступаться', 'to intercede'],
  ['يَعْتَذِرُ', 'uzr aytmoq', 'оправдываться', 'to make excuses'],
  ['يَعْرُجُ', 'ko‘tarilmoq', 'восходить', 'to ascend'],
  ['يُعَمَّرُ', 'uzoq umr berilmoq', 'получать долгую жизнь', 'to be granted long life'],
  ['يُفْتِي', 'fatvo bermoq, hukm aytmoq', 'выносить решение', 'to give a ruling'],
  ['يَمْتَرُ', 'shubhalanmoq', 'сомневаться', 'to doubt'],
  ['يُؤَدِّ', 'ado etmoq, topshirmoq', 'отдавать, исполнять', 'to render, fulfil'],
  ['أَجْمَعُ', 'to‘plamoq, kelishmoq', 'собирать, сговариваться', 'to gather, resolve together'],
  ['أَحْبار', 'ulamolar, ahborlar', 'книжники, учёные', 'rabbis, scholars'],
  ['أَحْبَطَ', 'behuda ketkazmoq', 'делать тщетным', 'to render worthless'],
  ['اخْتارَ', 'tanlamoq', 'выбирать', 'to choose'],
  ['أَخْسَر', 'eng ko‘p ziyon ko‘ruvchi', 'самый убыточный', 'greatest loser'],
  ['أَدْبَرَ', 'orqaga qaytmoq, yuz o‘girmoq', 'отворачиваться', 'to turn away'],
  ['أَذِلَّة', 'xorlar, pastkashlar', 'униженные', 'humble ones'],
  ['ارْتَقِبْ', 'kutmoq, kuzatmoq', 'ожидать, наблюдать', 'to watch, await'],
  ['أَرْحَم', 'eng rahmli', 'милосерднейший', 'most merciful'],
  ['أَرْذَل', 'eng past, tuban', 'самый жалкий', 'most abject'],
  ['أَزْكَى', 'eng pok', 'чище всего', 'purest'],
  ['أُزْلِفَتْ', 'yaqinlashtirilmoq', 'быть приближённым', 'to be brought near'],
  ['إِسْتَبْرَق', 'qalin shoyi, istabraq', 'плотная парча', 'thick brocade'],
  ['اسْتَحَبُّ', 'afzal ko‘rmoq', 'предпочитать', 'to prefer'],
  ['اسْتَخْرَجَ', 'chiqarib olmoq', 'извлекать', 'to extract'],
  ['اسْتَعِذْ', 'panoh so‘ramoq', 'искать защиты', 'to seek refuge'],
  ['اسْتَعِينُ', 'yordam so‘ramoq', 'просить помощи', 'to seek help'],
  ['اسْتَغاثَ', 'najot so‘ramoq', 'взывать о помощи', 'to cry for help'],
  ['اسْتَغْنَى', 'behojat bo‘lmoq', 'обходиться без', 'to be free of need'],
  ['أَسْلِحَت', 'qurollar', 'оружие', 'weapons'],
  ['أَسِير', 'asir', 'пленник', 'captive'],
  ['أَصَرُّ', 'qaysarlik qilmoq', 'упорствовать', 'to persist'],
  ['أُصْلِي', 'olovga kiritmoq', 'ввергать в огонь', 'to burn, cast into fire'],
  ['أَطْهَر', 'eng pok', 'чище', 'purer'],
  ['أُغْشِيَتْ', 'qoplanmoq', 'быть покрытым', 'to be covered'],
  ['اقْتَتَلَ', 'jang qilmoq', 'сражаться', 'to fight one another'],
  ['اقْتَرَفْ', 'orttirmoq (gunoh)', 'совершать, приобретать', 'to commit, earn'],
  ['أَقْرَرْ', 'iqror bo‘lmoq; qaror toptirmoq', 'признавать; утверждать', 'to affirm; to settle'],
  ['أَقْوَم', 'eng to‘g‘ri', 'самый правильный', 'most upright'],
  ['أَكْرَمَ', 'ikrom qilmoq, hurmatlamoq', 'почитать', 'to honour'],
  ['أَكْل', 'yeyish; meva', 'еда; плод', 'eating; produce'],
  ['أَكِنَّة', 'pardalar, qoplamalar', 'покровы', 'coverings'],
  ['أَكْواب', 'kubaklar, qadahlar', 'кубки', 'goblets'],
  ['أَلْحَقْ', 'qo‘shmoq, yetkazmoq', 'присоединять', 'to join, attach'],
  ['أَلْهَى', 'chalg‘itmoq', 'отвлекать', 'to distract'],
  ['أَمانَة', 'omonat', 'доверенное, аманат', 'trust'],
  ['أَمَد', 'muddat, oraliq', 'срок', 'term, span'],
  ['أَمْس', 'kecha (o‘tgan kun)', 'вчера', 'yesterday'],
  ['أَنۢبَأَ', 'xabar bermoq', 'сообщать', 'to inform'],
  ['انتِقام', 'intiqom', 'возмездие', 'retribution'],
  ['أَنقَذَ', 'qutqarmoq', 'спасать', 'to rescue'],
  ['اهْتَزَّتْ', 'tebranmoq, jonlanmoq', 'колыхаться', 'to stir, quiver'],
  ['أُهِلَّ', '(nomi) baland aytilmoq', 'быть посвящённым при заклании', 'to be offered with invocation'],
  ['أَيْكَة', 'chakalak, o‘rmon', 'роща', 'thicket, wood'],
  ['أَيُّوب', 'Ayyub', 'Айюб (Иов)', 'Job (Ayyub)'],
  ['بَأْساء', 'qattiqchilik, musibat', 'бедствие, нужда', 'adversity'],
  ['باسِط', 'yoyuvchi, cho‘zuvchi', 'простирающий', 'one who stretches out'],
  ['باقِيَة', 'qoluvchi, boqiy', 'остающаяся', 'remaining, lasting'],
  ['بال', 'hol, ahvol; xayol', 'состояние; ум', 'state, condition; mind'],
  ['بُرُوج', 'burjlar, qal’alar', 'созвездия, башни', 'constellations, towers'],
  ['بَعْث', 'tirilish, yuborish', 'воскрешение', 'resurrection, sending'],
  ['بَيَّتَ', 'tunda reja tuzmoq', 'замышлять ночью', 'to plot by night'],
  ['تَأْسَ', 'qayg‘urmoq', 'горевать', 'to grieve'],
  ['تَشابَهَ', 'o‘xshash bo‘lmoq', 'быть похожим', 'to resemble one another'],
  ['تَقِيّ', 'taqvodor', 'богобоязненный', 'God-fearing'],
  ['تَلَقَّى', 'qabul qilmoq, qarshi olmoq', 'принимать', 'to receive'],
  ['تَمَّ', 'tugallanmoq, kamolga yetmoq', 'завершаться', 'to be completed'],
  ['تَمارَ', 'bahslashmoq, shubhalanmoq', 'препираться', 'to dispute'],
  ['تَناجَيْ', 'yashirin so‘zlashmoq', 'тайно беседовать', 'to converse secretly'],
  ['ثُبُور', 'halokat, o‘lim', 'погибель', 'destruction'],
  ['ثَقُلَتْ', 'og‘ir bo‘lmoq', 'становиться тяжёлым', 'to be heavy'],
  ['ثَمّ', 'u yerda', 'там', 'there'],
  ['ثَمانِيَة', 'sakkiz', 'восемь', 'eight'],
  ['جاهِلِيَّة', 'johiliyat', 'язычество, невежество', 'ignorance (pre-Islamic)'],
  ['جاوَزَ', 'o‘tmoq, kesib o‘tmoq', 'переходить', 'to cross over'],
  ['جَسَد', 'jasad, tan', 'тело', 'body'],
  ['جُنُب', 'junub; uzoq', 'осквернённый; далёкий', 'ritually impure; distant'],
  ['جِهاد', 'jihod, kurash', 'усердие, джихад', 'striving, struggle'],
  ['جَهالَة', 'johillik', 'невежество', 'ignorance'],
  ['جُوع', 'ochlik', 'голод', 'hunger'],
  ['حاصِب', 'tosh yog‘diruvchi bo‘ron', 'ураган с камнями', 'storm of stones'],
  ['حَرْب', 'urush', 'война', 'war'],
  ['حَسِيب', 'hisob qiluvchi, yetarli', 'ведущий счёт', 'reckoner, sufficient'],
  ['حَصِيد', 'o‘rilgan ekin', 'сжатое', 'harvested crop'],
  ['حُلُّ', 'bezanmoq', 'украшаться', 'to be adorned'],
  ['حِلْيَة', 'bezak, taqinchoq', 'украшение', 'ornament'],
  ['حُور', 'hur qizlar', 'гурии', 'fair companions (houris)'],
  ['حَيَّ', 'tirik bo‘lmoq, yashamoq', 'жить', 'to live'],
  ['خابَ', 'noumid bo‘lmoq', 'терпеть неудачу', 'to fail, be disappointed'],
  ['خَرَقَ', 'teshmoq, yormoq', 'продырявливать', 'to tear, pierce'],
  ['خَزَنَت', 'qorovullar, xazinabonlar', 'стражи', 'keepers, guards'],
  ['خَلِيل', 'do‘st, xalil', 'близкий друг', 'intimate friend'],
  ['دَأْب', 'odat, yo‘sin', 'обычай', 'way, custom'],
  ['دابِر', 'orqa, ildiz', 'последний, корень', 'last remnant, root'],
  ['داخِر', 'xor, bo‘ysungan', 'униженный', 'humbled'],
  ['داعِي', 'chaqiruvchi, da’vatchi', 'зовущий', 'caller'],
  ['دَعْوَى', 'da’vo, chaqiriq', 'призыв, притязание', 'call, claim'],
  ['راجِع', 'qaytuvchi', 'возвращающийся', 'returning'],
  ['راضِيَة', 'rozi bo‘lgan', 'довольная', 'well-pleased'],
  ['رَبَتْ', 'o‘smoq, ko‘paymoq', 'расти', 'to grow, swell'],
  ['رَجْفَة', 'zilzila, silkinish', 'сотрясение', 'earthquake, shock'],
  ['زُخْرُف', 'bezak, oltin', 'украшение, золото', 'ornament, gold'],
  ['زُلْفَى', 'yaqinlik', 'приближение', 'nearness'],
  ['زُور', 'yolg‘on, tuhmat', 'ложь', 'falsehood'],
  ['ساق', 'soq, oyoq', 'голень', 'shank, leg'],
  ['سَبْعَة', 'yetti', 'семь', 'seven'],
  ['سَدّ', 'to‘siq, sadd', 'преграда', 'barrier, dam'],
  ['سِراج', 'chiroq', 'светильник', 'lamp'],
  ['سَرَقَ', 'o‘g‘irlamoq', 'красть', 'to steal'],
  ['سَفِينَة', 'kema', 'корабль', 'ship'],
  ['سَقَر', 'Saqar (do‘zax)', 'Сакар (ад)', 'Saqar (Hellfire)'],
  ['سَقْف', 'shift, tom', 'крыша', 'roof, ceiling'],
  ['سَمّاع', 'ko‘p eshituvchi', 'жадно слушающий', 'avid listener'],
  ['سُنبُلَة', 'boshoq', 'колос', 'ear of grain'],
  ['سُوق', 'bozor', 'рынок', 'market'],
  ['سَوَّلَ', 'bezab ko‘rsatmoq, vasvasa qilmoq', 'прельщать', 'to entice, make seem fair'],
  ['سَيِّئ', 'yomon', 'плохой', 'evil'],
  ['شَأْن', 'ish, holat', 'дело, состояние', 'affair, matter'],
  ['شَرَ', 'sotmoq, sotib olmoq', 'продавать, покупать', 'to sell, buy'],
  ['شَعائِر', 'sha’oir, ibodat belgilari', 'обряды', 'rites, symbols'],
  ['شِفاء', 'shifo', 'исцеление', 'healing'],
  ['شَقُ', 'badbaxt bo‘lmoq', 'быть несчастным', 'to be wretched'],
  ['شَقِيّ', 'badbaxt', 'несчастный', 'wretched'],
  ['شِهاب', 'uchqun, yulduz shu’lasi', 'пылающий огонь, метеор', 'flame, shooting star'],
  ['شَيْخ', 'keksa, shayx', 'старец', 'old man'],
  ['صاحِبَة', 'hamroh ayol, xotin', 'спутница, жена', 'female companion, wife'],
  ['صَبَّ', 'quymoq', 'лить', 'to pour'],
  ['صَبّار', 'juda sabrli', 'очень терпеливый', 'most patient'],
  ['صَدَفَ', 'yuz o‘girmoq', 'отворачиваться', 'to turn away'],
  ['صَرْح', 'saroy, baland qasr', 'дворец', 'lofty palace'],
  ['صَعِيد', 'tuproq, yer yuzi', 'земля, почва', 'earth, dust'],
  ['صَلْصال', 'quruq loy', 'звонкая глина', 'dry clay'],
  ['صَوَّرَ', 'shakl bermoq', 'придавать облик', 'to fashion, form'],
  ['ضَعْف', 'zaiflik', 'слабость', 'weakness'],
  ['طائِف', 'aylanuvchi; yopiruvchi balo', 'обходящий; напасть', 'one who circles; visitation'],
  ['طَبَق', 'qatlam, bosqich', 'слой, ступень', 'stage, layer'],
  ['طَرِيق', 'yo‘l', 'дорога', 'road, way'],
  ['طِفْل', 'bola, chaqaloq', 'ребёнок', 'child'],
  ['طَلْع', 'xurmo gullari, meva boshi', 'завязь пальмы', 'spathe, date-palm bud'],
  ['طَمَع', 'tama, ochko‘zlik', 'алчность, надежда', 'greed, craving'],
  ['طَوْع', 'itoat, ixtiyor', 'покорность, добровольность', 'obedience, willingness'],
  ['ظالِمَة', 'zolim ayol; zolim shahar', 'несправедливая', 'wrongdoing (feminine)'],
  ['عالِي', 'baland, yuqori', 'высокий', 'high, lofty'],
  ['عَجُوز', 'kampir, keksa ayol', 'старуха', 'old woman'],
  ['عَرْض', 'kenglik; taqdim etish; mol', 'ширина; представление', 'breadth; presentation'],
  ['عَزَمَ', 'qat’iy qaror qilmoq', 'твёрдо решить', 'to resolve firmly'],
  ['عَشَر', 'o‘n', 'десять', 'ten'],
  ['عُصْبَة', 'guruh, jamoa', 'группа, отряд', 'band, group'],
  ['عُقْدَة', 'tugun; ahd', 'узел; договор', 'knot; pledge'],
  ['عَقِيم', 'bepusht, tug‘masligi', 'бесплодный', 'barren'],
  ['عَلّام', 'hamma narsani biluvchi', 'всеведущий', 'all-knowing'],
  ['عَلانِيَة', 'oshkoralik', 'открыто, явно', 'openness, in public'],
  ['عُلُوّ', 'baland kelish, kibr', 'превозношение', 'haughtiness, exaltedness'],
  ['عَمَرُ', 'obod qilmoq, yashamoq', 'заселять, обустраивать', 'to inhabit, maintain'],
  ['عَنِيد', 'qaysar, o‘jar', 'упрямый', 'obstinate'],
  ['عَوْرَة', 'avrat, ochiq joy', 'уязвимое место, нагота', 'vulnerable place, nakedness'],
  ['عِين', 'katta ko‘zli (huriylar)', 'большеглазые', 'wide-eyed'],
  ['غَمام', 'bulut', 'облако', 'cloud'],
  ['غَيّ', 'adashish, gumrohlik', 'заблуждение', 'error, misguidance'],
  ['غُيُوب', 'g‘oyiblar, sirlar', 'сокровенное', 'hidden things'],
  ['فائِز', 'yutuqqa erishuvchi', 'преуспевший', 'successful one'],
  ['فُجّار', 'fojirlar, buzuqlar', 'нечестивцы', 'the wicked'],
  ['فَخُور', 'maqtanchoq', 'хвастливый', 'boastful'],
  ['فِرار', 'qochish', 'бегство', 'flight, escape'],
  ['فُسُوق', 'fisq, itoatsizlik', 'нечестие', 'defiant disobedience'],
  ['فَشِلْ', 'bo‘shashmoq, ojizlanmoq', 'падать духом', 'to lose heart'],
  ['قارُون', 'Qorun', 'Карун', 'Qarun (Korah)'],
  ['قِبَل', 'tomon, oldi; qudrat', 'сторона; способность', 'side, direction; ability'],
  ['قُتِّلُ', 'qattiq o‘ldirilmoq', 'быть убитым', 'to be slain'],
  ['قُدَّ', 'yirtilmoq', 'быть разорванным', 'to be torn'],
  ['قُدُس', 'poklik, muqaddaslik', 'святость', 'holiness'],
  ['قِصاص', 'qasos, qisos', 'возмездие, воздаяние', 'legal retribution'],
  ['قَصْر', 'saroy, qasr; qisqartirish', 'дворец; сокращение', 'palace; shortening'],
  ['قُعُود', 'o‘tirish', 'сидение', 'sitting'],
  ['قَفَّيْ', 'ketma-ket yubormoq', 'посылать вслед', 'to send one after another'],
  ['قَلَم', 'qalam', 'перо', 'pen'],
  ['قَنَطُ', 'umidsizlikka tushmoq', 'отчаиваться', 'to despair'],
  ['قِيل', 'aytilgan so‘z', 'сказанное', 'what is said'],
  ['كَبِّرْ', 'ulug‘lamoq, takbir aytmoq', 'возвеличивать', 'to magnify'],
  ['كَرْب', 'g‘am, iztirob', 'скорбь, беда', 'distress, anguish'],
  ['كِسَف', 'parchalar, bo‘laklar', 'куски', 'fragments, pieces'],
  ['كَفّارَة', 'kafforat, yuvish', 'искупление', 'expiation'],
  ['كِفْل', 'ulush, nasiba', 'доля', 'share, portion'],
  ['كَلام', 'so‘z, kalom', 'речь, слово', 'speech, words'],
  ['كَلِم', 'so‘zlar', 'слова', 'words'],
  ['لَمَسُ', 'tegmoq, qidirmoq', 'касаться, искать', 'to touch, seek'],
  ['مالِك', 'ega, egalik qiluvchi', 'владыка', 'owner, master'],
  ['مُبارَكَة', 'barakali', 'благословенная', 'blessed'],
  ['مُبْصِر', 'ko‘ruvchi; yorituvchi', 'зрячий; освещающий', 'seeing; giving sight'],
  ['مُبْلِس', 'umidsiz, hangu mang', 'отчаявшийся', 'despairing, dumbfounded'],
  ['مُتَقابِل', 'bir-biriga qarama-qarshi', 'друг против друга', 'facing one another'],
  ['مُتَوَكِّل', 'tavakkul qiluvchi', 'уповающий', 'one who trusts in God'],
  ['مُجاهِد', 'jihod qiluvchi', 'усердствующий', 'one who strives'],
  ['مَجِيد', 'ulug‘, sharafli', 'славный', 'glorious'],
  ['مِحْراب', 'mehrob, ibodat joyi', 'михраб, святилище', 'prayer chamber'],
  ['مُحَرَّم', 'harom qilingan', 'запретный', 'forbidden'],
  ['مَحْرُوم', 'mahrum, nasibasiz', 'обделённый', 'deprived'],
  ['مُحَمَّد', 'Muhammad', 'Мухаммад', 'Muhammad'],
  ['مُخَلَّف', 'ortda qoldirilgan', 'оставленный позади', 'left behind'],
  ['مَرْء', 'kishi, odam', 'человек', 'man, person'],
  ['مُرْسِل', 'yuboruvchi', 'посылающий', 'one who sends'],
  ['مَسْحُور', 'sehrlangan', 'околдованный', 'bewitched'],
  ['مِصْباح', 'chiroq, qandil', 'светильник', 'lamp'],
  ['مَضَى', 'o‘tib ketmoq', 'проходить, миновать', 'to pass, go on'],
  ['مُعَذَّب', 'azoblanuvchi', 'подвергаемый мучению', 'one punished'],
  ['مُعَذِّب', 'azoblovchi', 'мучающий', 'one who punishes'],
  ['مَعِين', 'oquvchi (suv), buloq', 'источник, текучая вода', 'flowing spring'],
  ['مَغانِم', 'o‘ljalar', 'трофеи', 'spoils of war'],
  ['مُغْرَق', 'g‘arq qilingan', 'потопленный', 'drowned'],
  ['مُقْتَدِر', 'qudratli, qodir', 'всемогущий', 'all-powerful'],
  ['مَقْعَد', 'o‘tirar joy, maqom', 'место сидения', 'seat, station'],
  ['مَكَثَ', 'turmoq, qolmoq', 'оставаться, пребывать', 'to stay, remain'],
  ['مَكْنُون', 'yashirilgan, saqlangan', 'сокрытый, оберегаемый', 'hidden, well-guarded'],
  ['مَكِين', 'mustahkam o‘rinli, e’tiborli', 'прочно утвердившийся', 'firmly established'],
  ['مُلاقُوا', 'uchrashuvchilar', 'встречающие', 'those who will meet'],
  ['مَلَكُوت', 'mulk, saltanat', 'царство, владычество', 'dominion, kingdom'],
  ['مُمْتَري', 'shubhalanuvchi', 'сомневающийся', 'one who doubts'],
  ['مَمْنُون', 'uzilmas, minnatsiz', 'непрерывный; без упрёка', 'unending; without reproach'],
  ['مَنام', 'uyqu, tush', 'сон', 'sleep, dream'],
  ['مُنتَصِر', 'g‘alaba qozonuvchi, yordam oluvchi', 'побеждающий', 'one who is helped, victorious'],
  ['مَنسَك', 'ibodat joyi, qurbonlik marosimi', 'обряд, место обряда', 'rite, place of sacrifice'],
  ['مَهِين', 'xor, past', 'презренный', 'despised, feeble'],
  ['نَذَرْ', 'ogohlantirmoq; nazr qilmoq', 'предостерегать; давать обет', 'to warn; to vow'],
  ['نَزَغَ', 'vasvasa solmoq, qutqu solmoq', 'подстрекать', 'to incite, sow discord'],
  ['نَصَب', 'mashaqqat, charchoq', 'тяготы, усталость', 'toil, hardship'],
  ['نَعْجَة', 'qo‘y, sovliq', 'овца', 'ewe'],
  ['نَفِدَ', 'tugamoq, tükenmoq', 'иссякать', 'to run out, be exhausted'],
  ['نَقَمُ', 'intiqom olmoq, ayblamoq', 'мстить, порицать', 'to take vengeance, resent'],
  ['هاتُ', 'keltiring, bering', 'подайте, приведите', 'bring it, produce it'],
  ['هُنا', 'bu yerda', 'здесь', 'here'],
  ['هَنِيئ', 'yoqimli, sog‘lom', 'приятный', 'wholesome, pleasant'],
  ['هُون', 'xorlik, yengillik', 'унижение; лёгкость', 'humiliation; ease'],
  ['واسِعَة', 'keng qamrovli (ayol)', 'обширная', 'vast (feminine)'],
  ['واعَدْ', 'va’dalashmoq', 'договариваться о сроке', 'to make an appointment'],
  ['وَبال', 'yomon oqibat, jazo', 'пагубные последствия', 'evil consequence'],
  ['وُۥرِيَ', 'yashirilmoq', 'быть скрытым', 'to be concealed'],
  ['وَسْوَسَ', 'vasvasa solmoq', 'нашёптывать', 'to whisper temptation'],
  ['وَقُود', 'yoqilg‘i, o‘tin', 'топливо', 'fuel'],
  ['يُبْطِلَ', 'botil qilmoq', 'делать тщетным', 'to nullify'],
  ['يَتَبَوَّأُ', 'joylashmoq, maskan tutmoq', 'поселяться', 'to settle, take a dwelling'],
  ['يَتَدَبَّرُ', 'chuqur o‘ylamoq, tafakkur qilmoq', 'размышлять', 'to ponder'],
  ['يَتَكَلَّمُ', 'gapirmoq, so‘zlamoq', 'говорить', 'to speak'],
  ['يُحافِظُ', 'saqlamoq, rioya qilmoq', 'беречь, соблюдать', 'to guard, keep up'],
  ['يُحَرِّفُ', 'so‘zni buzib talqin qilmoq', 'искажать', 'to distort'],
  ['يُحِقَّ', 'haqni ro‘yobga chiqarmoq', 'утверждать истину', 'to establish the truth'],
  ['يَخْرُصُ', 'taxmin qilmoq, yolg‘on to‘qimoq', 'строить догадки, лгать', 'to conjecture, lie'],
  ['يُخَوِّفُ', 'qo‘rqitmoq', 'устрашать', 'to frighten'],
  ['يُدَبِّرُ', 'tadbir qilmoq, boshqarmoq', 'управлять', 'to direct, manage'],
  ['يَدْرَؤُا۟', 'qaytarmoq, daf qilmoq', 'отвращать', 'to avert, ward off'],
  ['يَرْغَبُ', 'rag‘bat qilmoq, istamoq', 'желать, стремиться', 'to desire, wish'],
  ['يَسْتَعْتِبُ', 'rozilik so‘ramoq', 'просить о снисхождении', 'to seek to make amends'],
  ['يَسْتَقْدِمُ', 'oldinga o‘tmoq, oldinlamoq', 'опережать', 'to go ahead, precede'],
  ['يَسُومُ', 'qiynamoq, tatib ko‘rmoq', 'подвергать, насылать', 'to inflict, impose'],
  ['يُصَلَّبُ', 'xochga tortilmoq', 'быть распятым', 'to be crucified'],
  ['يُعْجِزَ', 'ojiz qoldirmoq', 'обессилить', 'to frustrate, escape'],
  ['يَغُضُّ', '(ko‘zni) pastga solmoq', 'опускать (взор)', 'to lower (the gaze)'],
  ['يُغَيِّرُ', 'o‘zgartirmoq', 'изменять', 'to change'],
  ['يَنْحِتُ', 'yo‘nmoq, o‘ymoq', 'высекать', 'to carve, hew'],
  ['يُونُس', 'Yunus', 'Юнус (Иона)', 'Jonah (Yunus)'],
  ['أَبْرَحَ', 'davom etmoq, ketmoq', 'продолжать; уходить', 'to keep on; to depart'],
  ['ابْيَضَّتْ', 'oqarmoq', 'белеть', 'to turn white'],
  ['أَتْراب', 'tengdoshlar', 'сверстницы', 'companions of equal age'],
  ['أُتْرِفُ', 'hashamatga botirilmoq', 'быть изнеженным роскошью', 'to be given a life of ease'],
  ['أَثابَ', 'mukofot bermoq', 'вознаграждать', 'to reward'],
  ['آثِم', 'gunohkor', 'грешник', 'sinful'],
  ['أُجاج', 'achchiq, sho‘r (suv)', 'горько-солёная', 'bitter, salty'],
  ['أَجْداث', 'qabrlar', 'могилы', 'graves'],
  ['أَحَبّ', 'eng suyukli, afzalroq', 'более любимый', 'more beloved'],
  ['احْتَمَلَ', 'ko‘tarmoq, o‘z bo‘yniga olmoq', 'брать на себя', 'to bear, take upon oneself'],
  ['أَحَسَّ', 'sezmoq, his qilmoq', 'чувствовать', 'to perceive, sense'],
  ['أَحْضَرَتْ', 'keltirmoq, hozir qilmoq', 'приводить, представлять', 'to bring forth'],
  ['أَخْبار', 'xabarlar', 'вести', 'tidings, news'],
  ['اخْتَلَطَ', 'aralashmoq', 'смешиваться', 'to mingle'],
  ['آخِذ', 'oluvchi', 'берущий', 'one who takes'],
  ['اخْفِضْ', 'pasaytirmoq (qanotni)', 'опускать (крыло)', 'to lower (the wing)'],
  ['ادّارَكَ', 'bir-biriga yetmoq, jamlanmoq', 'достигать друг друга', 'to accumulate, reach'],
  ['أَذْقان', 'iyaklar', 'подбородки', 'chins'],
  ['أَذَّنَ', 'e’lon qilmoq, jar solmoq', 'возвещать', 'to announce, proclaim'],
  ['ارْتَضَى', 'rozi bo‘lmoq, tanlamoq', 'одобрять, избирать', 'to approve, choose'],
  ['أَرْدَى', 'halok qilmoq', 'губить', 'to destroy'],
  ['اسْتَخَفَّ', 'yengil sanamoq, beparvo qilmoq', 'считать лёгким, тревожить', 'to make light of, unsettle'],
  ['اسْتَفْتَحُ', 'g‘alaba, hukm so‘ramoq', 'просить о победе, решении', 'to seek victory or judgement'],
  ['اسْتَكْثَرْ', 'ko‘p deb bilmoq, ko‘paytirmoq', 'считать многим', 'to seek much'],
  ['اسْتَمْسَكَ', 'mahkam tutmoq', 'крепко держаться', 'to hold fast'],
  ['اسْتَنكَفُ', 'or qilmoq, kibrlanmoq', 'гнушаться', 'to disdain'],
  ['أَسَّسَ', 'asos solmoq', 'основывать', 'to found, establish'],
  ['أُسْوَة', 'o‘rnak, namuna', 'пример, образец', 'example, model'],
  ['أَشْقَى', 'eng badbaxt', 'самый несчастный', 'most wretched'],
  ['إِصْر', 'og‘ir yuk, ahd', 'бремя, обязательство', 'burden, covenant'],
  ['اصْطَبِرْ', 'sabr qilmoq', 'терпеть', 'to be steadfast'],
  ['أَصْل', 'ildiz, asos', 'корень, основа', 'root, origin'],
  ['أَضاءَ', 'yoritmoq', 'освещать', 'to give light'],
  ['إِطْعام', 'taom berish', 'кормление', 'feeding'],
  ['أَطْفَأَ', 'o‘chirmoq', 'гасить', 'to extinguish'],
  ['اطَّيَّرْ', 'shumlanmoq, yomon fol ko‘rmoq', 'считать дурным предзнаменованием', 'to take as an evil omen'],
  ['اعْتَرَفُ', 'iqror bo‘lmoq, tan olmoq', 'признаваться', 'to confess, acknowledge'],
  ['أَعْجَمِيّ', 'arab bo‘lmagan, ajnabiy', 'иноязычный', 'foreign, non-Arabic'],
  ['أَعَزّ', 'eng qudratli, azizroq', 'могущественнее', 'mightier'],
  ['أَعْظَم', 'eng ulug‘', 'величайший', 'greatest'],
  ['أُفّ', 'uf (norozilik so‘zi)', 'уф (звук досады)', 'ugh (expression of disgust)'],
  ['أَفاءَ', 'qaytarmoq, o‘lja bermoq', 'даровать (добычу)', 'to grant as spoils'],
  ['أَفْرِغْ', 'quymoq, to‘kmoq', 'излей, ниспошли', 'pour out'],
  ['أُفُق', 'ufq, chekka', 'горизонт', 'horizon'],
  ['أَفَلَ', 'botmoq (yulduz)', 'закатываться', 'to set, disappear'],
  ['أَقْصا', 'eng uzoq', 'самый дальний', 'farthest'],
  ['آكِل', 'yeyuvchi', 'едящий', 'one who eats'],
  ['أَكْنَن', 'yashirmoq', 'скрывать', 'to conceal'],
  ['أَلْزَمَ', 'majbur qilmoq, biriktirmoq', 'обязывать', 'to bind, impose'],
  ['أَلْفَ', 'topmoq, uchratmoq', 'находить, заставать', 'to find, come upon'],
  ['إِلْياس', 'Ilyos', 'Ильяс (Илия)', 'Elias (Ilyas)'],
  ['امْسَحُ', 'silamoq, mash tortmoq', 'обтирать', 'to wipe, rub'],
  ['آناء', 'vaqtlar, soatlar', 'часы, поры', 'hours, times'],
  ['أَنشَرَ', 'tiriltirmoq', 'оживлять', 'to bring to life'],
  ['انفَضُّ', 'tarqalmoq', 'расходиться', 'to disperse'],
  ['أَوْتاد', 'qoziqlar', 'колья', 'pegs, stakes'],
  ['أَوْثان', 'butlar, sanamlar', 'идолы', 'idols'],
  ['أَوْجَسَ', 'ich-ichidan sezmoq, qo‘rquv his qilmoq', 'ощутить (страх)', 'to conceive (fear) inwardly'],
  ['إِيتاء', 'berish, ato qilish', 'дарование', 'the giving'],
  ['أَيْمَن', 'o‘ng tomon; barakali', 'правый; благословенный', 'right side; blessed'],
  ['بارِئ', 'yaratuvchi', 'творец', 'the Originator'],
  ['باطِن', 'botin, ichki', 'внутренний, скрытый', 'inward, hidden'],
  ['باغ', 'haddan oshuvchi, zolim', 'преступающий', 'transgressor'],
  ['بالِغَة', 'yetuvchi, ta’sirli', 'достигающая', 'far-reaching, effective'],
  ['بَرْزَخ', 'barzax, oraliq to‘siq', 'барзах, преграда', 'barrier, interval'],
  ['بَرَكَة', 'baraka', 'благословение', 'blessing'],
  ['بُشْر', 'xushxabar', 'благая весть', 'glad tidings'],
  ['بَصُرَتْ', 'ko‘rmoq, payqamoq', 'разглядеть', 'to perceive, discern'],
  ['بَطْش', 'qattiq ushlash, zarba', 'хватка, мощь', 'grip, might'],
  ['بَقَر', 'mol, sigir', 'коровы', 'cattle, cows'],
  ['بَقِيَ', 'qolmoq', 'оставаться', 'to remain'],
  ['بَقِيَّت', 'qoldiq, meros', 'остаток', 'remnant'],
  ['بِكْر', 'bokira, yosh', 'девственница', 'virgin'],
  ['بَهِيمَة', 'chorva, hayvon', 'скотина', 'beast, cattle'],
  ['بَيات', 'tunda, tunda kelgan balo', 'ночью', 'by night'],
  ['بَيان', 'bayon, ravshan qilish', 'разъяснение', 'clear explanation'],
  ['تابِع', 'ergashuvchi', 'последователь', 'follower'],
  ['تَأَخَّرَ', 'kechikmoq, ortda qolmoq', 'отставать', 'to lag behind'],
  ['تارِك', 'tark etuvchi', 'оставляющий', 'one who abandons'],
  ['تُحَدِّثُ', 'so‘zlamoq, xabar bermoq', 'рассказывать', 'to relate, tell'],
  ['تَحْوِيل', 'o‘zgartirish, ko‘chirish', 'изменение, перемещение', 'alteration, transfer'],
  ['تُرْجِي', 'kechiktirmoq', 'откладывать', 'to defer, put off'],
  ['تُسْقِطَ', 'tushirmoq, qulatmoq', 'обрушивать', 'to bring down, drop'],
  ['تَسْلِيم', 'salom berish, taslim bo‘lish', 'приветствие, покорность', 'greeting, submission'],
  ['تَضَرُّع', 'tazarru, yolvorish', 'смирение, мольба', 'humble supplication'],
  ['تُقْسِطُ', 'adolat qilmoq', 'поступать справедливо', 'to act justly'],
  ['تِلْقاء', 'tomon, yo‘nalish', 'сторона', 'direction, presence'],
  ['تَلْقَفُ', 'yutmoq, ilib olmoq', 'заглатывать', 'to swallow up'],
  ['تَمَنَّى', 'orzu qilmoq, tamanno qilmoq', 'желать', 'to wish, long for'],
  ['تَمِيدَ', 'tebranmoq, chayqalmoq', 'колебаться', 'to sway, shake'],
  ['تَنتَشِرُ', 'tarqalmoq, yoyilmoq', 'расходиться', 'to disperse, spread out'],
  ['تَنفُذُ', 'kirib bormoq, o‘tmoq', 'проникать', 'to pass through, penetrate'],
  ['تُنكِحُ', 'nikohlab bermoq', 'выдавать замуж', 'to give in marriage'],
  ['تَيَمَّمُ', 'qasd qilmoq, tayammum qilmoq', 'намереваться, обращаться', 'to head for, seek'],
  ['ثُلَّة', 'guruh, jamoa', 'группа', 'group, company'],
  ['جار', 'qo‘shni; zolim', 'сосед; несправедливый', 'neighbour; unjust'],
  ['جارِيَة', 'oquvchi, kema', 'текущая, судно', 'flowing, ship'],
  ['جالُوت', 'Jolut', 'Джалут (Голиаф)', 'Goliath (Jalut)'],
  ['جامِع', 'to‘plovchi, jamlovchi', 'собирающий', 'gatherer'],
  ['جِبْرِيل', 'Jibril', 'Джибриль (Гавриил)', 'Gabriel (Jibril)'],
  ['جِذْع', 'xurmo shoxi, tanasi', 'ствол пальмы', 'trunk of a palm tree'],
  ['جُزْء', 'bo‘lak, qism', 'часть', 'part, portion'],
  ['جَهْرَة', 'oshkora, ochiq', 'открыто, воочию', 'openly, visibly'],
  ['جَوار', 'oquvchi kemalar', 'плывущие суда', 'ships that sail'],
  ['جَيْب', 'yoqa, ko‘krak', 'пазуха, ворот', 'bosom, opening of a garment'],
  ['حاجَة', 'ehtiyoj, hojat', 'нужда', 'need, want'],
  ['حاسَبْ', 'hisob-kitob qilmoq', 'призывать к отчёту', 'to bring to account'],
  ['حاشِر', 'to‘plovchi', 'собирающий', 'gatherer, summoner'],
  ['حاقَّة', 'muqarrar voqea, qiyomat', 'неизбежное', 'the inevitable reality'],
  ['حالَ', 'to‘smoq, oraga kirmoq', 'вставать между', 'to come between'],
  ['حَدائِق', 'bog‘lar', 'сады', 'gardens'],
  ['حِذْر', 'ehtiyot, hazar', 'осторожность', 'caution'],
  ['حَرّ', 'issiqlik; ozod', 'жар; свободный', 'heat; free'],
  ['حَرَصْ', 'qattiq intilmoq, hirs qilmoq', 'сильно желать', 'to be eager, covet'],
  ['حَرِّقُ', 'kuydirmoq', 'сжигать', 'to burn'],
  ['حَرِير', 'shoyi, ipak', 'шёлк', 'silk'],
  ['حَزَن', 'g‘am, qayg‘u', 'печаль', 'grief, sorrow'],
  ['حُسْبان', 'hisob, o‘lchov', 'расчёт, мера', 'reckoning, measure'],
  ['حَسَدَ', 'hasad qilmoq', 'завидовать', 'to envy'],
  ['حَسُنَ', 'yaxshi bo‘lmoq, go‘zallashmoq', 'быть хорошим', 'to be good, comely'],
  ['حُطام', 'chirindi, singan poya', 'труха, обломки', 'debris, dry stubble'],
  ['حِفْظ', 'saqlash, muhofaza', 'хранение', 'preservation, guarding'],
  ['حَكَم', 'hakam, hukm qiluvchi', 'судья', 'judge, arbiter'],
  ['حَمَإ', 'qora loy', 'чёрная глина', 'dark mud'],
  ['حِمْل', 'yuk, homila', 'ноша, бремя', 'load, burden'],
  ['خارِج', 'chiquvchi, tashqari', 'выходящий', 'one who goes out'],
  ['خاسِئ', 'xor, quvilgan', 'презренный, отверженный', 'despised, driven away'],
  ['خاطَبَ', 'murojaat qilmoq, so‘zlashmoq', 'обращаться с речью', 'to address, speak to'],
  ['خالَة', 'xola', 'тётя (по матери)', 'maternal aunt'],
  ['خائِف', 'qo‘rquvchi', 'боящийся', 'fearful']
]
