import type { Gloss } from './glossary-types'

/** Quranic lemmas ranked 1801-2300 by frequency. See glossary-types.ts for conventions. */
export const WORD_GLOSSES_1800: readonly Gloss[] = [
  ['خائِن', 'xoin, xiyonatkor', 'предатель', 'treacherous one'],
  ['خَسار', 'ziyon, zarar', 'убыток', 'loss'],
  ['خُسْران', 'ziyon, halokat', 'убыток, погибель', 'loss, ruin'],
  ['خَصْم', 'raqib, da’vogar', 'противник в споре', 'adversary, litigant'],
  ['خِطاب', 'murojaat, nutq', 'обращение, речь', 'address, discourse'],
  ['خَطِفَ', 'ilib olmoq, yulmoq', 'выхватывать', 'to snatch'],
  ['خَفَّتْ', 'yengil bo‘lmoq', 'становиться лёгким', 'to be light'],
  ['خَمْسَة', 'besh', 'пять', 'five'],
  ['خَوَّلَ', 'bermoq, ega qilmoq', 'наделять', 'to grant, bestow'],
  ['داع', 'chaqiruvchi, da’vatchi', 'зовущий', 'caller'],
  ['دانِيَة', 'yaqin, past osilgan', 'близкая, свисающая', 'near, low-hanging'],
  ['دائِرَة', 'aylana; balo, ko‘rgilik', 'круг; беда', 'circle; misfortune'],
  ['دَكّ', 'yanchish, tekislash', 'сокрушение', 'crushing, levelling'],
  ['ذائِقَة', 'tatib ko‘ruvchi', 'вкушающая', 'one who tastes'],
  ['ذَرْع', 'qo‘l yetishi, imkon', 'возможность, сила', 'capacity, reach'],
  ['ذُلّ', 'xorlik, past bo‘lish', 'униженность', 'humility, lowliness'],
  ['ذِئْب', 'bo‘ri', 'волк', 'wolf'],
  ['رادّ', 'qaytaruvchi', 'отвращающий', 'one who repels'],
  ['راغَ', 'qochib qolmoq, chetga burilmoq', 'улизнуть', 'to slip away, turn aside'],
  ['راغِب', 'istovchi, rag‘bat qiluvchi', 'желающий', 'one who desires'],
  ['رَبّانِيِّن', 'rabbiylar, ilohiyot olimlari', 'раввины, богословы', 'rabbis, divines'],
  ['رَبَطْ', 'bog‘lamoq, mustahkamlamoq', 'укреплять, связывать', 'to bind, strengthen'],
  ['رَجْع', 'qaytish, javob', 'возвращение, ответ', 'return, response'],
  ['رَحْل', 'yuk, ko‘chish', 'поклажа, кочёвка', 'saddle-bag, journey'],
  ['رَشِيد', 'to‘g‘ri yo‘ldagi, oqil', 'благоразумный', 'rightly guided, sensible'],
  ['رَغَد', 'keng, farovon', 'изобильный', 'abundant, pleasant'],
  ['رُمّان', 'anor', 'гранат', 'pomegranate'],
  ['رُهْبان', 'rohiblar', 'монахи', 'monks'],
  ['رَهْط', 'guruh, toifa', 'группа людей', 'band, group'],
  ['رَوْح', 'orom, rohat; shabada', 'отдохновение, дуновение', 'comfort, breath of mercy'],
  ['رِئاء', 'ko‘z-ko‘z qilish, riyo', 'показное', 'showing off'],
  ['زالَ', 'ketmoq, yo‘qolmoq', 'исчезать', 'to cease, depart'],
  ['زان', 'zino qiluvchi erkak', 'прелюбодей', 'fornicator'],
  ['زانِيَة', 'zino qiluvchi ayol', 'прелюбодейка', 'adulteress'],
  ['زَبَد', 'ko‘pik', 'пена', 'froth, scum'],
  ['زَبُور', 'Zabur', 'Псалтырь', 'Psalms (Zabur)'],
  ['زَفِير', 'nafas olish, uvillash', 'стон, рёв', 'roaring, groaning'],
  ['زَقُّوم', 'zaqqum daraxti', 'дерево заккум', 'the Zaqqum tree'],
  ['زُلْزِلُ', 'larzaga solinmoq', 'быть потрясённым', 'to be shaken violently'],
  ['زَهَقَ', 'yo‘qolmoq, so‘nmoq', 'исчезать, гибнуть', 'to vanish, perish'],
  ['سارِق', 'o‘g‘ri', 'вор', 'thief'],
  ['سافِل', 'past, quyidagi', 'низший', 'lowest'],
  ['سامِرِيّ', 'Somiriy', 'Самири', 'the Samiri'],
  ['سِجِّيل', 'pishgan loy toshi', 'обожжённая глина', 'baked clay'],
  ['سُحْت', 'harom mol', 'запретное имущество', 'unlawful gain'],
  ['سَحَر', 'tong oldi, sahar', 'предрассветная пора', 'dawn, small hours'],
  ['سَحَرُ', 'sehr qilmoq', 'колдовать', 'to bewitch'],
  ['سُدُس', 'oltidan bir', 'одна шестая', 'one sixth'],
  ['سَرابِيل', 'ko‘ylaklar', 'рубахи', 'garments, shirts'],
  ['سَرِّحُ', 'qo‘yib yubormoq, ozod qilmoq', 'отпускать', 'to release, let go'],
  ['سُقِطَ', 'tushirilmoq, qulatilmoq', 'быть повергнутым', 'to be cast down'],
  ['سُكارَى', 'mastlar', 'пьяные', 'drunken'],
  ['سَكَن', 'orom, maskan; sokinlik', 'покой, жилище', 'repose, dwelling'],
  ['سِلْسِلَة', 'zanjir', 'цепь', 'chain'],
  ['سَلْوَى', 'bedana (osmoniy taom)', 'перепела', 'quail'],
  ['سَمُوم', 'issiq shamol, sumum', 'знойный ветер', 'scorching wind'],
  ['سَمِين', 'semiz', 'жирный', 'fat, plump'],
  ['سُندُس', 'nozik shoyi, sundus', 'тонкий шёлк', 'fine silk'],
  ['سَيّارَة', 'yo‘lovchilar, karvon', 'путники, караван', 'travellers, caravan'],
  ['سَيِّد', 'xo‘jayin, sarvar', 'господин', 'master, chief'],
  ['شَتَّى', 'har xil, turli-tuman', 'разные', 'diverse, various'],
  ['شِرْب', 'ichimlik ulushi, suv navbati', 'доля питья', 'share of drink'],
  ['شَهَوَة', 'shahvat, ishtiyoq', 'страсть', 'desire, lust'],
  ['صابِئ', 'sobiy (bir toifa)', 'сабий', 'Sabian'],
  ['صافَّة', 'saf tortuvchi (qush)', 'выстроившиеся рядами', 'ranged in rows'],
  ['صَرْصَر', 'qattiq sovuq shamol', 'ледяной ураган', 'furious cold wind'],
  ['صَغِير', 'kichik', 'малый', 'small'],
  ['صُورَة', 'shakl, surat', 'образ, форма', 'form, shape'],
  ['ضَرْب', 'urish; misol keltirish', 'удар; приведение примера', 'striking; setting forth'],
  ['ضِغْث', 'bir dasta cho‘p', 'пучок веток', 'bundle of twigs'],
  ['ضِياء', 'yorug‘lik, ziyo', 'сияние', 'light, radiance'],
  ['طابَ', 'pok, yoqimli bo‘lmoq', 'быть приятным', 'to be good, pleasant'],
  ['طاعَة', 'itoat', 'повиновение', 'obedience'],
  ['طالَ', 'uzoq davom etmoq', 'длиться', 'to grow long'],
  ['طَرَد', 'quvmoq, haydamoq', 'прогонять', 'to drive away'],
  ['طَفِقَ', 'kirishmoq, boshlamoq', 'приниматься', 'to set about, begin'],
  ['طَوْل', 'imkon, boylik; uzunlik', 'достаток; длина', 'means, capacity'],
  ['عاجِلَة', 'shoshqaloq (dunyo hayoti)', 'быстротечная', 'the fleeting (life)'],
  ['عاصِم', 'saqlovchi, himoyachi', 'защитник', 'protector'],
  ['عاقِر', 'bepusht', 'бесплодная', 'barren'],
  ['عَزَّرُ', 'hurmatlamoq, qo‘llab-quvvatlamoq', 'почитать, поддерживать', 'to honour, support'],
  ['عَشْرَة', 'o‘nta', 'десять', 'ten'],
  ['عَشِيرَت', 'qarindoshlar, urug‘', 'родня', 'kinsfolk'],
  ['عَصْف', 'somon, quruq barg', 'солома, мякина', 'chaff, husk'],
  ['عُلْيا', 'eng baland', 'высочайшая', 'highest'],
  ['عَمَّة', 'amma', 'тётя (по отцу)', 'paternal aunt'],
  ['عَمَد', 'ustunlar', 'столбы', 'pillars'],
  ['عِمْران', 'Imron', 'Имран', 'Imran'],
  ['عَنِ', 'mashaqqatga tushmoq', 'впадать в тягость', 'to fall into hardship'],
  ['عِير', 'karvon', 'караван', 'caravan'],
  ['غاشِيَة', 'qoplovchi balo, qiyomat', 'покрывающее бедствие', 'the overwhelming event'],
  ['غائِب', 'g‘oyib, yo‘q', 'отсутствующий', 'absent'],
  ['غَدَ', 'erta bormoq, chiqmoq', 'выходить поутру', 'to go forth early'],
  ['غَرُور', 'aldov, mag‘rurlik', 'обольщение', 'delusion, deception'],
  ['غَشَّى', 'qoplamoq, o‘ramoq', 'покрывать', 'to cover, envelop'],
  ['غَمْرَة', 'qattiq holat, g‘aflat', 'пучина, беспамятство', 'stupor, flood'],
  ['غَنَم', 'qo‘y-echki', 'мелкий скот', 'sheep and goats'],
  ['غَوَى', 'adashmoq, gumroh bo‘lmoq', 'заблуждаться', 'to go astray'],
  ['غَيْث', 'yomg‘ir', 'дождь', 'rain'],
  ['فاءُ', 'qaytmoq, moyil bo‘lmoq', 'возвращаться, склоняться', 'to return, incline'],
  ['فاتَ', 'qo‘ldan chiqmoq, o‘tib ketmoq', 'ускользать', 'to escape, be missed'],
  ['فارَ', 'qaynamoq, otilmoq', 'кипеть, бить ключом', 'to boil, gush'],
  ['فازَ', 'yutuqqa erishmoq, najot topmoq', 'преуспевать', 'to attain, succeed'],
  ['فاكِه', 'meva yeyuvchi, shod', 'вкушающий плоды', 'enjoying fruits'],
  ['فَتَى', 'yigit, xizmatkor', 'юноша, слуга', 'young man, servant'],
  ['فِتْيَة', 'yigitlar', 'юноши', 'young men'],
  [
    'فَتِيل',
    'xurmo danagidagi ip, arzimas narsa',
    'волосок на финиковой косточке',
    'a thread on a date-stone, a trifle'
  ],
  ['فَجّ', 'keng yo‘l, dara', 'широкий проход', 'broad pass'],
  ['فِدْيَة', 'tovon, fidya', 'выкуп', 'ransom, compensation'],
  ['فُرات', 'chuchuk (suv)', 'пресная', 'fresh, sweet'],
  ['فِراش', 'to‘shak', 'ложе', 'bed, couch'],
  ['فَرْد', 'yolg‘iz, yakka', 'одинокий', 'alone, single'],
  ['فَزِعَ', 'qo‘rqib ketmoq, cho‘chimoq', 'пугаться', 'to be terrified'],
  ['فَسَدَتِ', 'buzilmoq, fasodga uchramoq', 'приходить в расстройство', 'to be corrupted'],
  ['فِسْق', 'fisq, itoatsizlik', 'нечестие', 'disobedience, defiance'],
  ['فِصال', 'ajratish, sutdan ajratish', 'отлучение от груди', 'weaning, separation'],
  ['فَواكِه', 'mevalar', 'плоды', 'fruits'],
  ['قاسِيَة', 'qattiq, toshbag‘ir', 'жестокая', 'hardened'],
  ['قاصِرَة', 'chegaralangan, ko‘zini tikkan', 'потупившая взор', 'restraining (the gaze)'],
  ['قانِتَة', 'itoatkor ayol', 'покорная', 'devoutly obedient (feminine)'],
  ['قاهِر', 'g‘olib, qahr qiluvchi', 'одолевающий', 'subduer, irresistible'],
  ['قُبُل', 'old tomon; yuzma-yuz', 'спереди; лицом к лицу', 'in front; face to face'],
  ['قَدِيم', 'qadimgi, eski', 'древний', 'ancient, old'],
  ['قُرْبان', 'qurbonlik', 'жертвоприношение', 'offering, sacrifice'],
  ['قُرَّة', 'quvonch, ko‘z nuri', 'отрада', 'comfort, delight'],
  ['قَرْح', 'yara', 'рана', 'wound'],
  ['قِرَدَة', 'maymunlar', 'обезьяны', 'apes'],
  ['قَسَتْ', 'qattiqlashmoq (qalb)', 'ожесточаться', 'to harden'],
  ['قِسْمَة', 'bo‘lish, taqsimlash', 'дележ', 'division, sharing'],
  ['قِنطار', 'qintor, katta boylik', 'кинтар, большое богатство', 'a heap of wealth'],
  ['قَوارِيرا', 'shishalar, billur idishlar', 'хрустальные сосуды', 'crystal vessels'],
  ['قَواعِد', 'poydevorlar; o‘tirib qolgan ayollar', 'основания; престарелые', 'foundations; women past childbearing'],
  ['قَوّام', 'adolat bilan turuvchi, qo‘riqchi', 'стойкий блюститель', 'upholder, maintainer'],
  ['قَيُّوم', 'abadiy turuvchi, qayyum', 'вечно сущий', 'self-subsisting'],
  ['كاشِف', 'ochuvchi, ko‘taruvchi', 'устраняющий', 'one who removes'],
  ['كُبِتَ', 'xor qilinmoq, tor-mor qilinmoq', 'быть поверженным', 'to be laid low'],
  ['كُرْه', 'majburlik, istamaslik', 'принуждение, нежелание', 'reluctance, compulsion'],
  ['كَسَوْ', 'kiydirmoq', 'одевать', 'to clothe'],
  ['كَظِيم', 'g‘azabini yutuvchi', 'сдерживающий гнев', 'one who restrains anger'],
  ['كُفُور', 'noshukurlik, kufr', 'неблагодарность', 'ingratitude'],
  ['كَنَزْ', 'xazina to‘plamoq', 'копить сокровища', 'to hoard'],
  ['كُوِّرَتْ', 'o‘ralmoq, so‘nmoq (quyosh)', 'быть свёрнутым', 'to be wound up'],
  ['لاعِب', 'o‘ynovchi', 'играющий', 'one who plays'],
  ['لُمْ', 'malomat qilmoq', 'порицать', 'to blame'],
  ['لَهَب', 'olov yalovi', 'пламя', 'flame'],
  ['مُبَدِّل', 'o‘zgartiruvchi', 'изменяющий', 'one who changes'],
  ['مُبْصِرَة', 'ko‘rsatuvchi, yorituvchi', 'дающая видеть', 'giving sight'],
  ['مُتَّخِذ', 'tutuvchi, qabul qiluvchi', 'берущий', 'one who takes'],
  ['مُتَرَبِّص', 'kutuvchi, poyluvchi', 'выжидающий', 'one who waits'],
  ['مَتِين', 'mustahkam, kuchli', 'крепкий', 'firm, strong'],
  ['مَثْنَى', 'ikkitadan', 'по двое', 'two by two'],
  ['مَحِلّ', 'tushar joy, muddat', 'место назначения', 'destination, appointed place'],
  ['مَحَوْ', 'o‘chirmoq', 'стирать', 'to erase'],
  ['مَحِيض', 'hayz', 'менструация', 'menstruation'],
  ['مُخْتال', 'kibrlanuvchi, mag‘rur', 'надменный', 'arrogant'],
  ['مُخْرِج', 'chiqaruvchi', 'выводящий', 'one who brings out'],
  ['مَدائِن', 'shaharlar', 'города', 'cities'],
  ['مَدْحُور', 'quvilgan, xor', 'изгнанный', 'driven away, disgraced'],
  ['مُدْخَل', 'kirar joy, kirish', 'место входа', 'entrance'],
  ['مِدْرار', 'mo‘l yog‘adigan (yomg‘ir)', 'обильный', 'abundantly pouring'],
  ['مَذْمُوم', 'qoralangan, malomatli', 'порицаемый', 'blameworthy'],
  ['مُرْسَى', 'langar tashlash joyi, to‘xtash', 'место стоянки', 'anchorage, mooring'],
  ['مَرْفُوعَة', 'baland ko‘tarilgan', 'вознесённая', 'raised high'],
  ['مِزاج', 'aralashma, tatim', 'примесь', 'mixture, blend'],
  ['مُسْتَقِرّ', 'qarorgoh, barqaror joy', 'место пребывания', 'resting place, abode'],
  ['مُسَخَّرَة', 'bo‘ysundirilgan', 'подчинённая', 'made subservient'],
  ['مَسْطُور', 'chizilgan, yozilgan', 'начертанное', 'written, inscribed'],
  ['مُسَلَّمَة', 'sog‘lom, nuqsonsiz', 'беспорочная', 'sound, flawless'],
  ['مُسْلِمَة', 'musulma ayol', 'мусульманка', 'Muslim woman'],
  ['مَسْنُون', 'o‘zgarib qolgan (loy)', 'изменившаяся', 'altered, moulded'],
  ['مُسَوَّمَة', 'belgilangan, nishonlangan', 'помеченная', 'marked, distinguished'],
  ['مَشْأَمَة', 'chap tomon, shumlik', 'левая сторона, злосчастье', 'the left, ill fortune'],
  ['مَشْحُون', 'to‘la yuklangan (kema)', 'гружёный', 'laden, loaded'],
  ['مَشْرَب', 'suv ichar joy, ichimlik', 'место питья', 'drinking place'],
  ['مَشْهُود', 'guvoh bo‘linadigan, hozir bo‘lingan', 'засвидетельствованный', 'witnessed, attended'],
  ['مُصْفَرّ', 'sarg‘aygan', 'пожелтевший', 'turning yellow'],
  ['مُصَلّي', 'namoz o‘quvchi', 'молящийся', 'one who prays'],
  ['مَضاجِع', 'yotar joylar', 'ложа, постели', 'sleeping places'],
  ['مُضْغَة', 'chaynalgan bir bo‘lak go‘sht', 'кусочек плоти', 'a lump of flesh'],
  ['مُضِلّ', 'adashtiruvchi', 'вводящий в заблуждение', 'one who misleads'],
  ['مُعاجِز', 'ojiz qoldirmoqchi bo‘luvchi', 'стремящийся ослабить', 'one who seeks to frustrate'],
  ['مُعْتَد', 'haddan oshuvchi', 'преступающий', 'transgressor'],
  ['مَعْذِرَة', 'uzr, bahona', 'оправдание', 'excuse'],
  ['مَعْشَر', 'jamoa, toifa', 'сообщество', 'assembly, company'],
  ['مَعِيشَة', 'turmush, tirikchilik', 'средства к жизни', 'livelihood'],
  ['مَغْرَم', 'tovon, zarar', 'убыток, штраф', 'fine, loss'],
  ['مَفاتِح', 'kalitlar, xazinalar', 'ключи, сокровищницы', 'keys, treasuries'],
  ['مُقام', 'turar joy, maqom', 'место пребывания', 'station, dwelling'],
  ['مِقْدار', 'o‘lchov, miqdor', 'мера, величина', 'measure, extent'],
  ['مُقَرَّن', 'bir-biriga bog‘langan', 'скованные вместе', 'bound together'],
  ['مُقْسِط', 'adolat qiluvchi', 'справедливый', 'one who acts justly'],
  ['مَلْجَإ', 'boshpana, panoh', 'убежище', 'refuge, shelter'],
  ['مُلْقي', 'tashlovchi, yetkazuvchi', 'бросающий', 'one who casts'],
  ['مَمات', 'o‘lim', 'смерть', 'death'],
  ['مُنتَقِم', 'intiqom oluvchi', 'мстящий', 'avenger'],
  ['مُنتَهَى', 'oxirgi chegara, borar joy', 'предел', 'final end, utmost limit'],
  ['مُنقَلِب', 'qaytuvchi, ag‘dariluvchi', 'возвращающийся', 'one who returns'],
  ['مُنكِر', 'inkor qiluvchi', 'отрицающий', 'one who denies'],
  ['مُهْتَد', 'hidoyat topgan', 'идущий верным путём', 'rightly guided'],
  ['مُهْطِع', 'bo‘yin cho‘zib shoshuvchi', 'спешащий с поднятой головой', 'hastening with outstretched neck'],
  ['مُهْل', 'erigan metall, quyqa', 'расплав', 'molten metal, dregs'],
  ['مَواضِع', 'joylar, o‘rinlar', 'места', 'places, positions'],
  ['مَوالِي', 'yaqinlar, homiylar', 'покровители, близкие', 'allies, kinsmen'],
  ['مَوْتَت', 'o‘lim', 'смерть', 'death'],
  ['مُؤْتَفِكَة', 'ag‘darilgan (shaharlar)', 'опрокинутые', 'overturned (cities)'],
  ['مَوْثِق', 'mustahkam ahd', 'твёрдый договор', 'binding covenant'],
  ['مَوْلُود', 'tug‘ilgan bola', 'новорождённый', 'newborn child'],
  ['مَيْسِر', 'qimor', 'азартная игра', 'gambling'],
  ['مَيْمَنَة', 'o‘ng tomon, baraka', 'правая сторона', 'the right side'],
  ['ناصِيَة', 'peshona sochi', 'чуб, хохол', 'forelock'],
  ['نَأَى', 'uzoqlashmoq, yiroq bo‘lmoq', 'удаляться', 'to keep away'],
  ['نَسَب', 'nasab, qarindoshlik', 'родство', 'lineage, kinship'],
  ['نُسِفَتْ', 'kukun qilib sochilmoq', 'быть развеянным', 'to be scattered to dust'],
  ['نَشْأَة', 'paydo bo‘lish, yaratilish', 'возникновение', 'bringing into being'],
  ['نُشِرَتْ', 'yoyilmoq, tarqalmoq', 'быть развёрнутым', 'to be spread out'],
  ['نُصُب', 'qurbongoh toshlari, butlar', 'жертвенники, идолы', 'altar stones, idols'],
  ['نِفاق', 'nifoq, ikkiyuzlamachilik', 'лицемерие', 'hypocrisy'],
  ['نَفَر', 'bir necha kishi, guruh', 'несколько человек', 'a few men, group'],
  ['نَفَقَة', 'sarf-xarajat, nafaqa', 'расход, содержание', 'spending, maintenance'],
  ['نَكال', 'ibratli jazo', 'назидательная кара', 'exemplary punishment'],
  ['نُكْر', 'yomon ish, dahshat', 'нечто предосудительное', 'something abominable'],
  ['نَوْم', 'uyqu', 'сон', 'sleep'],
  ['هادِي', 'yo‘l ko‘rsatuvchi', 'ведущий', 'guide'],
  ['هَيِّن', 'oson, yengil', 'лёгкий', 'easy, trifling'],
  ['وابِل', 'kuchli yomg‘ir', 'ливень', 'heavy rain'],
  ['وارِد', 'kelib turuvchi, suvga boruvchi', 'приходящий (к воде)', 'one who comes (to water)'],
  ['واق', 'saqlovchi, himoyachi', 'защитник', 'protector'],
  ['والِدَة', 'tug‘uvchi, ona', 'родительница', 'mother'],
  ['وَجِلَتْ', 'qo‘rqib titramoq', 'трепетать', 'to tremble with fear'],
  ['وَزَنُ', 'tortmoq, o‘lchamoq', 'взвешивать', 'to weigh'],
  ['وَزْن', 'tortish, vazn', 'вес', 'weight'],
  ['وِعاء', 'idish, qop', 'вместилище', 'container, receptacle'],
  ['وَقْت', 'vaqt, muddat', 'время, срок', 'time, appointed hour'],
  ['وُقِفُ', 'to‘xtatilmoq', 'быть остановленным', 'to be made to stand'],
  ['وَهّاب', 'ko‘p hadya qiluvchi', 'щедро дарующий', 'ever-bestowing'],
  ['يَأْلَمُ', 'og‘riq sezmoq', 'испытывать боль', 'to feel pain'],
  ['يُبْدِلَ', 'almashtirmoq', 'заменять', 'to replace'],
  ['يُبْدِئُ', 'boshlamoq, yo‘qdan yaratmoq', 'начинать творение', 'to originate'],
  ['يَتَبَدَّلِ', 'almashtirib olmoq', 'обменивать', 'to exchange'],
  ['يَتَخَطَّفَ', 'ilib ketilmoq, o‘g‘irlanmoq', 'быть похищенным', 'to be snatched away'],
  ['يَتَضَرَّعُ', 'tazarru qilmoq, yolvormoq', 'смиренно молить', 'to humble oneself in prayer'],
  ['يَتَعَدَّ', 'haddan oshmoq', 'преступать', 'to transgress'],
  ['يَجْأَرُ', 'baqirmoq, dod solmoq', 'вопить', 'to cry out'],
  ['يَجْرِمَ', 'jinoyatga undamoq', 'толкать на грех', 'to lead into crime'],
  ['يَحْتَسِبُ', 'hisobga olmoq, kutmoq', 'рассчитывать', 'to reckon, expect'],
  ['يُحْدِثُ', 'yangidan paydo qilmoq', 'производить заново', 'to bring about anew'],
  ['يَدَّعُ', 'haydab yubormoq, itarmoq', 'отталкивать', 'to drive away'],
  ['يُذَبِّحُ', 'qattiq so‘ymoq', 'резать (многих)', 'to slaughter (many)'],
  ['يُرْضُ', 'rozi qilmoq', 'удовлетворять', 'to please, satisfy'],
  ['يَرْقُبُ', 'kuzatmoq, poylamoq', 'наблюдать', 'to watch, keep an eye on'],
  ['يَرْكُضُ', 'chopmoq, yugurmoq', 'бежать', 'to run'],
  ['يَرْهَبُ', 'qo‘rqmoq', 'страшиться', 'to fear'],
  ['يُرْهِقَ', 'qoplamoq, zulm qilmoq', 'обременять', 'to burden, cover'],
  ['يَسْأَمُ', 'zerikmoq, to‘ymoq', 'уставать, пресыщаться', 'to weary, tire'],
  ['يَسْتَبْدِلْ', 'almashtirib olmoq', 'обменивать', 'to exchange'],
  ['يَسْتَخْفُ', 'yashirinmoq', 'укрываться', 'to hide oneself'],
  ['يَسْتَعْفِفْ', 'iffatli bo‘lmoq, o‘zini tiymoq', 'блюсти целомудрие', 'to keep chaste'],
  ['يَسْتَفِزَّ', 'qo‘zg‘atmoq, joyidan siljitmoq', 'подстрекать, вытеснять', 'to provoke, unsettle'],
  ['يُسْجَنَ', 'zindonga solinmoq', 'быть заточённым', 'to be imprisoned'],
  ['يَشَّقَّقُ', 'yorilmoq, parchalanmoq', 'раскалываться', 'to split apart'],
  ['يُضارَّ', 'zarar yetkazilmoq', 'терпеть вред', 'to be harmed'],
  ['يَطَأُ', 'bosmoq, oyoq qo‘ymoq', 'ступать', 'to tread'],
  ['يَعْدُ', 'haddan oshmoq, dushmanlik qilmoq', 'враждовать', 'to transgress, act with enmity'],
  ['يَعْصِمُ', 'saqlamoq, himoya qilmoq', 'защищать', 'to protect'],
  ['يَغِيظُ', 'g‘azablantirmoq', 'гневить', 'to enrage'],
  ['يَكْفُلُ', 'kafolat olmoq, boqmoq', 'брать на попечение', 'to take charge of'],
  ['يَلْ', 'burmoq, egmoq', 'поворачивать', 'to turn away, twist'],
  ['يُلاقُ', 'uchrashmoq', 'встречать', 'to meet'],
  ['يَلِجَ', 'kirmoq', 'входить', 'to enter'],
  ['يُلْحِدُ', 'haqdan og‘moq', 'уклоняться от истины', 'to deviate'],
  ['يَلْمِزُ', 'chaqmoq, ta’na qilmoq', 'злословить', 'to slander, find fault'],
  ['يُمِلَّ', 'diktovka qilmoq', 'диктовать', 'to dictate'],
  ['يُمْنَى', 'to‘kilmoq (nutfa)', 'извергаться', 'to be emitted'],
  ['يَمِيلُ', 'moyil bo‘lmoq', 'склоняться', 'to incline'],
  ['يُنكِرُ', 'inkor qilmoq', 'отрицать', 'to deny'],
  ['يُوزَعُ', 'guruhlarga bo‘linmoq', 'быть построенным по рядам', 'to be marshalled in ranks'],
  ['يَئُوس', 'juda umidsiz', 'отчаявшийся', 'utterly despairing'],
  ['أَبْرَص', 'pes, moxov', 'прокажённый', 'leper'],
  ['أُبْسِلُ', 'halokatga topshirilmoq', 'быть обречённым', 'to be given over to ruin'],
  ['إِبْكار', 'erta tong', 'раннее утро', 'early morning'],
  ['إِبِل', 'tuyalar', 'верблюды', 'camels'],
  ['ابْنَت', 'qiz, farzand', 'дочь', 'daughter'],
  ['اتِّباع', 'ergashish, ittibo', 'следование', 'following'],
  ['أَتْقَى', 'eng taqvodor', 'самый богобоязненный', 'most God-fearing'],
  ['أَثاث', 'uy jihozi, mol-mulk', 'утварь, имущество', 'furnishings, goods'],
  ['أَثْخَن', 'qattiq zarba bermoq, ko‘pini o‘ldirmoq', 'одолеть, ослабить', 'to subdue thoroughly'],
  ['أَثْمَرَ', 'meva bermoq', 'плодоносить', 'to bear fruit'],
  ['اجْتَمَعُ', 'to‘planmoq', 'собираться', 'to gather together'],
  ['أَجَّلَ', 'muddat belgilamoq', 'назначать срок', 'to appoint a term'],
  ['اجْلِدُ', 'qamchi urmoq', 'бичевать', 'to flog'],
  ['أُحْصِرُ', 'to‘sib qo‘yilmoq, qamalmoq', 'быть задержанным', 'to be prevented, hindered'],
  ['أَحْكَم', 'eng hikmatli', 'мудрейший', 'most wise'],
  ['أُحْكِمَتْ', 'mustahkam qilinmoq', 'быть утверждённым', 'to be made firm'],
  ['أَخْبَتُ', 'kamtarin bo‘lmoq', 'смиряться', 'to be humble'],
  ['أَخْدان', 'yashirin do‘stlar, oshnalar', 'тайные друзья', 'secret lovers, companions'],
  ['أَخْطَأْ', 'xato qilmoq', 'ошибаться', 'to err, make a mistake'],
  ['أَخْلَدَ', 'dunyoga berilmoq, abadiy qolmoq', 'прилепляться к земному', 'to cling, incline to'],
  ['أَخْلَصُ', 'ixlosli qilmoq, tanlab olmoq', 'делать искренним', 'to make sincere, choose'],
  ['إِدْرِيس', 'Idris', 'Идрис', 'Idris (Enoch)'],
  ['أَدْلَى', '(chelakni) tushirmoq, taqdim qilmoq', 'опускать; предлагать', 'to let down; to offer'],
  ['أَذَلّ', 'eng xor', 'самый униженный', 'most abased'],
  ['آذَن', 'bildirmoq, e’lon qilmoq', 'объявлять', 'to announce'],
  ['أَرْبَى', 'ko‘paymoq, ribo yemoq', 'возрастать; ростовщичествовать', 'to increase, take usury'],
  ['أَرْكَسَ', 'orqaga qaytarmoq', 'повергать вспять', 'to turn back, overturn'],
  ['أَزاغَ', 'og‘dirmoq, burmoq', 'отклонять', 'to cause to swerve'],
  ['آزِفَة', 'yaqinlashuvchi (qiyomat)', 'приближающийся', 'the approaching (hour)'],
  ['أَزْلام', 'fol o‘qlari', 'гадательные стрелы', 'divining arrows'],
  ['اسْتَأْجَرْ', 'yollamoq', 'нанимать', 'to hire'],
  ['اسْتَحَقَّ', 'haqli bo‘lmoq, sazovor bo‘lmoq', 'заслуживать', 'to deserve, be entitled'],
  ['اسْتَحْوَذَ', 'egallab olmoq', 'овладевать', 'to gain mastery over'],
  ['اسْتَسْقَى', 'suv so‘ramoq', 'просить воды', 'to ask for water'],
  ['اسْتَشْهِدُ', 'guvoh keltirmoq', 'призывать в свидетели', 'to call to witness'],
  ['اسْتَغْشَ', 'kiyim bilan o‘ranmoq', 'закутываться', 'to cover oneself'],
  ['اسْتَكانُ', 'bo‘ysunmoq, tavozu qilmoq', 'смиряться', 'to humble oneself'],
  ['اسْتِكْبار', 'kibrlanish, takabburlik', 'высокомерие', 'arrogance'],
  ['اسْتَنصَرَ', 'yordam so‘ramoq', 'просить помощи', 'to seek help'],
  ['اسْتَيْأَسَ', 'umidini uzmoq', 'отчаиваться', 'to despair'],
  ['اسْتَيْسَرَ', 'oson bo‘lmoq, muyassar bo‘lmoq', 'быть доступным', 'to be made easy'],
  ['اسْتَيْقَنَتْ', 'aniq bilmoq, ishonch hosil qilmoq', 'убеждаться', 'to be certain'],
  ['إِسْرار', 'sir tutish, yashirish', 'утаивание', 'concealment'],
  ['إِسْراف', 'isrof, haddan oshish', 'расточительство', 'extravagance, excess'],
  ['أَسْرَع', 'eng tez', 'быстрейший', 'swiftest'],
  ['أَسَف', 'qayg‘u, afsus', 'печаль, сожаление', 'sorrow, regret'],
  ['أَسِف', 'qayg‘uli, g‘azabnok', 'опечаленный', 'sorrowful, angry'],
  ['أَسْفار', 'kitoblar; safarlar', 'книги; путешествия', 'books; journeys'],
  ['أَسْلَفَتْ', 'oldindan yubormoq, o‘tkazmoq', 'отправлять вперёд', 'to send ahead, have done before'],
  ['أَسْوَأ', 'eng yomon', 'худший', 'worst'],
  ['اسْوَدَّتْ', 'qoraymoq', 'чернеть', 'to turn black'],
  ['أَشْتات', 'turli guruhlar', 'разрозненные группы', 'scattered groups'],
  ['اشْتَمَلَتْ', 'o‘z ichiga olmoq', 'вмещать, содержать', 'to contain, enclose'],
  ['أَشِر', 'kekkaygan, mag‘rur', 'дерзкий', 'insolent'],
  ['أَشْفَقْ', 'qo‘rqmoq, achinmoq', 'страшиться', 'to be apprehensive'],
  ['أَصابِع', 'barmoqlar', 'пальцы', 'fingers'],
  ['أَصْدَق', 'eng rostgo‘y', 'правдивейший', 'most truthful'],
  ['أَصْغَر', 'eng kichik', 'наименьший', 'smallest'],
  ['أَصْفاد', 'kishanlar', 'оковы', 'fetters'],
  ['أَصْفَى', 'tanlab olmoq, afzal ko‘rmoq', 'отдавать предпочтение', 'to prefer, choose'],
  ['أَضْعَف', 'eng zaif', 'слабейший', 'weakest'],
  ['أَضْغان', 'kek, adovat', 'злоба', 'rancour, malice'],
  ['اضْمُمْ', 'qo‘shmoq, o‘ziga tortmoq', 'прижимать', 'to draw close'],
  ['أَعانَ', 'yordam bermoq', 'помогать', 'to help'],
  ['أَعْجاز', 'orqa qismlar, tanalar', 'стволы, остовы', 'trunks, stumps'],
  ['إِعْراض', 'yuz o‘girish', 'отвращение, отказ', 'turning away'],
  ['أَعْراف', 'ikki orasidagi to‘siq, tepalik', 'преграда, возвышенность', 'the heights, barrier'],
  ['أَعْرَج', 'cho‘loq', 'хромой', 'lame'],
  ['أَعْلام', 'belgilar, nishonalar', 'знамения, вехи', 'landmarks, signs'],
  ['أَعْلَوْن', 'eng yuqori bo‘lganlar', 'превосходящие', 'those who prevail'],
  ['أَغْرَيْ', 'qiziqtirmoq, gij-gijlamoq', 'возбуждать', 'to stir up, incite'],
  ['اغْلُظْ', 'dag‘al bo‘lmoq, qattiq turmoq', 'быть суровым', 'to be harsh'],
  ['أَفّاك', 'o‘ta yolg‘onchi, tuhmatchi', 'клеветник', 'great liar'],
  ['افْتِراء', 'uydirma, tuhmat', 'измышление', 'fabrication'],
  ['إِقام', 'barpo qilish (namozni)', 'совершение (молитвы)', 'establishing (prayer)'],
  ['أَقْسَط', 'eng adolatli', 'справедливейший', 'most just'],
  ['أَقْطار', 'tomonlar, chekkalar', 'края, стороны', 'regions, sides'],
  ['أَقَلّ', 'eng oz', 'наименьший', 'fewest, least'],
  ['اكْتالُ', 'o‘lchab olmoq', 'отмеривать себе', 'to take by measure'],
  ['أَكْثَرُ', 'ko‘paytirmoq', 'умножать', 'to make much'],
  ['إِكْرام', 'ikrom, izzat', 'почитание', 'honouring'],
  ['إِكْراه', 'majburlash', 'принуждение', 'compulsion'],
  ['أَكْرَم', 'eng karamli, ulug‘', 'благороднейший', 'most generous'],
  ['أَكْمام', 'g‘unchalar, qobiqlar', 'чашечки, завязи', 'sheaths, spathes'],
  ['أَكْمَلْ', 'kamolga yetkazmoq, to‘ldirmoq', 'завершать', 'to complete'],
  ['أَكْمَه', 'tug‘ma ko‘r', 'слепорождённый', 'one born blind'],
  ['إِلّ', 'qarindoshlik, ahd', 'родство, договор', 'kinship, pact'],
  ['إِلاف', 'uzviy bog‘lanish, ulfat', 'привязанность', 'familiarity, covenant'],
  ['الْتَقَطَ', 'terib olmoq', 'подбирать', 'to pick up'],
  ['الْيَسَع', 'Ilyaso', 'Аль-Ясаа', 'Elisha (al-Yasa)'],
  ['أَمانَت', 'omonatlar', 'доверенное', 'trusts'],
  ['أَمَة', 'cho‘ri, xizmatkor ayol', 'рабыня', 'bondwoman'],
  ['امْتَحَنَ', 'sinamoq, imtihon qilmoq', 'испытывать', 'to test'],
  ['أَمَل', 'orzu, umid', 'надежда', 'hope, aspiration'],
  ['إِمْلاق', 'qashshoqlik, faqirlik', 'нищета', 'poverty'],
  ['أَمَنَة', 'xotirjamlik, tinchlik', 'безопасность, покой', 'security, tranquillity'],
  ['انتَبَذَتْ', 'chetlanmoq, uzoqlashmoq', 'удаляться', 'to withdraw'],
  ['انسَلَخَ', 'o‘tib ketmoq, tugamoq', 'истекать', 'to pass, be over'],
  ['انشُزُ', 'o‘rningizdan turing', 'поднимайтесь', 'rise up'],
  ['أَنصِتُ', 'jim turmoq, quloq solmoq', 'молчать, внимать', 'to listen in silence'],
  ['أَنطَقَ', 'so‘zlatmoq, gapirtirmoq', 'заставлять говорить', 'to make speak'],
  ['أَنف', 'burun', 'нос', 'nose'],
  ['أَنفال', 'o‘ljalar', 'трофеи', 'spoils of war'],
  ['آنِيَة', 'idishlar', 'сосуды', 'vessels'],
  ['أَهانَ', 'xor qilmoq', 'унижать', 'to humiliate'],
  ['أَوّاه', 'ko‘p ohu chekuvchi, yumshoq', 'сострадательный', 'compassionate, oft-sighing'],
  ['أَوْدِيَة', 'vodiylar', 'долины', 'valleys'],
  ['أَوْزِعْ', 'ilhom ber, nasib et', 'внуши мне', 'inspire me, grant me'],
  ['أَوْسَط', 'o‘rtacha, eng yaxshi', 'средний, наилучший', 'middle, best'],
  ['أَوْعَى', 'ko‘proq anglagan, saqlaydigan', 'лучше сознающий', 'more heedful, retentive'],
  ['أَيْيد', 'kuch-quvvat', 'сила', 'strength'],
  ['باخِع', 'o‘zini halok qiluvchi', 'губящий себя', 'one who destroys himself'],
  ['بارِد', 'sovuq', 'холодный', 'cold'],
  ['باشِرُ', 'qo‘shilmoq, jinsiy yaqinlik qilmoq', 'вступать в близость', 'to have relations with'],
  ['باقي', 'qoluvchi, boqiy', 'остающийся', 'remaining'],
  ['بَخْس', 'kamaytirish, arzimas qilish', 'убавление', 'diminishing'],
  ['بُخْل', 'baxillik', 'скупость', 'miserliness'],
  ['بَدِيع', 'misli yo‘q yaratuvchi', 'создатель без образца', 'originator without precedent'],
  ['بَرَّأَ', 'oqlamoq, xoli qilmoq', 'оправдывать', 'to declare free, absolve'],
  ['بَراءَة', 'voz kechish, e’lon qilingan xoli bo‘lish', 'отречение', 'disavowal, immunity'],
  ['بَرْد', 'sovuq', 'холод', 'cold'],
  ['بُرِّزَتِ', 'chiqarilmoq, oshkor qilinmoq', 'быть явленным', 'to be brought forth'],
  ['بَرِيَّة', 'xaloyiq, yaratilganlar', 'творения', 'creatures, mankind'],
  ['بَصطَة', 'kenglik, keng imkon', 'обширность', 'expansion, ampleness'],
  ['بِضْع', 'bir necha (yil)', 'несколько', 'a few'],
  ['بِطانَة', 'ichki do‘st, sirdosh', 'близкий друг', 'intimate friend'],
  ['بَطْشَة', 'qattiq zarba', 'хватка, удар', 'violent seizure'],
  ['بَطَنَ', 'yashirin bo‘lmoq', 'быть скрытым', 'to be hidden'],
  ['بُعْثِرَ', 'ostin-ustun qilinmoq', 'быть перевёрнутым', 'to be turned upside down'],
  ['بَعُدَتْ', 'uzoqlashmoq', 'отдаляться', 'to be far off'],
  ['بَعِير', 'tuya', 'верблюд', 'camel'],
  ['بَغِيّ', 'buzuq ayol, haddan oshuvchi', 'распутница', 'harlot, transgressor'],
  ['بِناء', 'bino, qurilish', 'строение', 'building, structure'],
  ['بَنان', 'barmoq uchlari', 'кончики пальцев', 'fingertips'],
  ['بُهِتَ', 'hayron qolmoq, javobsiz qolmoq', 'опешить', 'to be dumbfounded'],
  ['بَهِيج', 'go‘zal, ko‘rkam', 'прекрасный', 'beautiful, delightful'],
  ['بُور', 'halokat, unumsiz', 'гибель, бесплодный', 'ruin, barren'],
  ['تابُوت', 'tobut, sandiq', 'ковчег, ларец', 'ark, chest'],
  ['تَأْثِيم', 'gunohga botirish', 'греховность', 'sinfulness'],
  ['تَأَذَّنَ', 'bildirmoq, e’lon qilmoq', 'возвестить', 'to proclaim'],
  ['تارَة', 'bir marta, gohida', 'однажды, порой', 'once, at times'],
  ['تَبَّ', 'halok bo‘lmoq, ziyon ko‘rmoq', 'погибать', 'to perish'],
  ['تَبْتَئِسْ', 'qayg‘urmoq, xafa bo‘lmoq', 'печалиться', 'to grieve'],
  ['تَبَرُّ', 'yaxshilik qilmoq', 'благодетельствовать', 'to be dutiful'],
  ['تَبَّرْ', 'halok qilmoq, yo‘q qilmoq', 'уничтожать', 'to destroy'],
  ['تُبْرِئُ', 'oqlamoq, sog‘aytirmoq', 'исцелять, оправдывать', 'to heal, absolve'],
  ['تَبَع', 'ergashuvchilar, tobelar', 'последователи', 'followers'],
  ['تُبَّع', 'Tubba (podshoh)', 'Тубба', 'Tubba (a king)'],
  ['تَتْبِير', 'halok qilish, yo‘q qilish', 'уничтожение', 'utter destruction'],
  ['تَثْبِيت', 'mustahkamlash, sobit qilish', 'укрепление', 'strengthening'],
  ['تَجَلَّى', 'zohir bo‘lmoq, tajalli qilmoq', 'являться', 'to manifest itself'],
  ['تَدْمِير', 'vayron qilish, halokat', 'разрушение', 'destruction'],
  ['تَراءَتِ', 'bir-birini ko‘rmoq', 'увидеть друг друга', 'to see one another'],
  ['تَراض', 'o‘zaro rozilik', 'взаимное согласие', 'mutual consent'],
  ['تَراضَ', 'o‘zaro rozi bo‘lmoq', 'приходить к согласию', 'to agree mutually'],
  ['تَرْتِيل', 'dona-dona o‘qish, tartil', 'размеренное чтение', 'measured recitation'],
  ['تَرْجُفُ', 'titramoq, larzaga kelmoq', 'сотрясаться', 'to quake'],
  ['تَرْكَنُ', 'suyanmoq, moyil bo‘lmoq', 'склоняться, опираться', 'to incline towards'],
  ['تَزْرَعُ', 'ekmoq', 'сеять', 'to sow'],
  ['تَسْبِيح', 'tasbeh, poklab yod etish', 'прославление', 'glorification'],
  ['تِسْعَة', 'to‘qqiz', 'девять', 'nine'],
  ['تُصاحِبْ', 'hamroh bo‘lmoq', 'сопровождать', 'to accompany'],
  ['تَصْدِيق', 'tasdiqlash', 'подтверждение', 'confirmation'],
  ['تَصْرِيف', 'turlantirish, o‘zgartirib berish', 'чередование', 'varying, dispensing'],
  ['تَصْطَلُ', 'olov bilan isinmoq', 'греться у огня', 'to warm oneself at a fire'],
  ['تَطَوَّعَ', 'ixtiyoriy ravishda qilmoq', 'делать добровольно', 'to do voluntarily'],
  ['تَظاهَرُ', 'bir-biriga yordam bermoq (yomonlikda)', 'поддерживать друг друга', 'to back one another'],
  ['تَعاوَنُ', 'bir-biriga yordam bermoq', 'помогать друг другу', 'to help one another'],
  ['تَعْضُلُ', 'to‘sqinlik qilmoq (nikohga)', 'препятствовать', 'to prevent, hold back'],
  ['تَغْلُو', 'haddan oshmoq (dinda)', 'чрезмерствовать', 'to go to excess'],
  ['تَفْجِير', 'otilib chiqarish, buloq ochish', 'заставить забить ключом', 'causing to gush forth'],
  ['تَفْضِيل', 'afzal qilish, ustun qo‘yish', 'предпочтение', 'preferring, favouring'],
  ['تَفْقِدُ', 'yo‘qotmoq, izlamoq', 'недосчитываться', 'to miss, find lacking'],
  ['تَفِيضُ', 'to‘lib oqmoq', 'переполняться', 'to overflow'],
  ['تَقَدَّمَ', 'oldinga o‘tmoq, ilgarilamoq', 'выступать вперёд', 'to come forward'],
  ['تَقَوَّلَ', 'o‘zidan to‘qib gapirmoq', 'измышлять слова', 'to fabricate sayings'],
  ['تَكاثُر', 'ko‘paytirishga intilish', 'стремление к приумножению', 'rivalry in worldly increase'],
  ['تَماثِيل', 'haykallar, tasvirlar', 'изваяния', 'statues, images'],
  ['تَمُورُ', 'chayqalmoq, mavj urmoq', 'колыхаться', 'to heave, surge'],
  ['تَنْهَرْ', 'jerkimoq, qattiq gapirmoq', 'прикрикивать', 'to rebuke harshly'],
  ['تَنُّور', 'tandir, o‘choq', 'печь', 'oven'],
  ['تَوارَتْ', 'yashirinmoq, ko‘zdan g‘oyib bo‘lmoq', 'скрываться', 'to disappear from sight'],
  ['تَوْفِيق', 'muvaffaqiyat, tavfiq', 'содействие, успех', 'success granted by God'],
  ['تَيَسَّرَ', 'oson bo‘lmoq, muyassar bo‘lmoq', 'оказываться посильным', 'to be made easy'],
  ['ثابِت', 'sobit, mustahkam', 'стойкий', 'firm, steadfast'],
  ['ثاقِب', 'teshib o‘tuvchi, yorqin', 'пронзающий, яркий', 'piercing, brightly shining'],
  ['ثالِث', 'uchinchi', 'третий', 'third'],
  ['ثانِي', 'ikkinchi', 'второй', 'second'],
  ['ثُعْبان', 'ilon, ajdar', 'змей', 'serpent'],
  ['ثُلاث', 'uchtadan', 'по трое', 'three by three'],
  ['جُبّ', 'quduq', 'колодец', 'well, pit'],
  ['جِبِلَّة', 'avlod, jamoa', 'поколение, множество', 'generation, multitude'],
  ['جِثِيّ', 'tiz cho‘kkan holda', 'на коленях', 'kneeling'],
  ['جِدار', 'devor', 'стена', 'wall'],
  ['جِدال', 'bahs, tortishuv', 'спор', 'dispute'],
  ['جَدَل', 'bahslashish, janjal', 'препирательство', 'wrangling'],
  ['جَراد', 'chigirtka', 'саранча', 'locusts'],
  ['جُرُز', 'qaqragan, unumsiz yer', 'бесплодная земля', 'barren land'],
  ['جِسْم', 'jism, tana', 'тело', 'body'],
  ['جَلال', 'ulug‘lik, jalol', 'величие', 'majesty'],
  ['جَلْدَة', 'qamchi zarbasi', 'удар плетью', 'lash, stroke'],
  ['جَلَّى', 'ochib bermoq, yorituvchi qilmoq', 'являть', 'to reveal, make manifest'],
  ['جُنَّة', 'qalqon, to‘siq', 'щит, прикрытие', 'shield, covering'],
  ['جَنَحُ', 'moyil bo‘lmoq (sulhga)', 'склоняться', 'to incline (to peace)'],
  ['جَهاز', 'jihoz, yuk', 'снаряжение', 'provisions, equipment'],
  ['جَهَّزَ', 'jihozlab bermoq', 'снаряжать', 'to equip, furnish'],
  ['حاجِز', 'to‘suvchi, ajratuvchi', 'преграда', 'barrier'],
  ['حادَّ', 'qarshilik qilmoq, dushmanlik qilmoq', 'противиться', 'to oppose, defy'],
  ['حارَبَ', 'urush qilmoq', 'воевать', 'to wage war'],
  ['حاسِب', 'hisob qiluvchi', 'ведущий счёт', 'reckoner'],
  ['حاش', 'aslo, sira', 'никак, упаси', 'far be it, by no means'],
  ['حاضِرَة', 'hozirgi, yaqin (qishloq)', 'близлежащая', 'present, nearby'],
  ['حافِظَة', 'saqlovchi ayol', 'хранящая', 'one who guards (feminine)'],
  ['حامِيَة', 'qizib turuvchi (olov)', 'пылающая', 'blazing'],
  ['حَجَر', 'tosh', 'камень', 'stone'],
  ['حَذَر', 'ehtiyot, hazar', 'осторожность', 'caution'],
  ['حُرّ', 'ozod, hur', 'свободный', 'free'],
  ['حَرِّضِ', 'undamoq, qiziqtirmoq', 'побуждать', 'to urge, incite'],
  ['حُرُمَة', 'hurmat qilinadigan narsa', 'святыня, запретное', 'sacred thing, sanctity'],
  ['حُزْن', 'g‘am, qayg‘u', 'печаль', 'grief'],
  ['حَشْر', 'to‘plash, mahshar', 'сбор', 'gathering, assembly'],
  ['حَصِرَتْ', 'torayib qolmoq (ko‘ngli)', 'стеснять грудь', 'to be constricted'],
  ['حَطَب', 'o‘tin', 'дрова', 'firewood']
]
