import type { Gloss } from './glossary-types'

/** Quranic lemmas ranked 550–800 by frequency. See glossary-types.ts for conventions. */
export const WORD_GLOSSES_550: readonly Gloss[] = [
  ['ثَمَرَة', 'meva', 'плод', 'fruit'],
  ['حُسْنَى', 'eng go‘zal (ayol shakli)', 'наилучшая', 'the best, most beautiful (fem.)'],
  ['حَمِيد', 'maqtovga loyiq', 'достохвальный', 'praiseworthy'],
  ['حَوْل', 'atrof; yil', 'вокруг; год', 'around; year'],
  ['سُلَيْمان', 'Sulaymon', 'Сулейман', 'Solomon'],
  ['فاحِشَة', 'fahsh, buzuq ish', 'мерзость, разврат', 'immorality, indecency'],
  ['فَصَّلَ', 'batafsil bayon qilmoq', 'разъяснять подробно', 'to explain in detail'],
  ['فَضَّلَ', 'afzal qilmoq, ustun qo‘ymoq', 'предпочитать, возвышать', 'to prefer, to favour'],
  ['قائِم', 'turuvchi, qoim', 'стоящий, устойчивый', 'standing, upright'],
  ['كَرِهَ', 'yoqtirmaslik, jirkanmoq', 'испытывать отвращение', 'to dislike, to hate'],
  ['مُهْتَدي', 'hidoyat topgan', 'идущий прямым путём', 'rightly guided'],
  ['نَعِيم', 'ne’mat, farovonlik', 'блаженство', 'bliss, delight'],
  ['وَدَّ', 'istamoq, sevmoq', 'желать, любить', 'to wish, to love'],
  ['يَتَفَكَّرُ', 'fikr yuritmoq, tafakkur qilmoq', 'размышлять', 'to reflect, to ponder'],
  ['آمِن', 'omon, xavfsiz', 'безопасный', 'safe, secure'],
  ['أَتَمَّ', 'to‘ldirmoq, kamolga yetkazmoq', 'завершать', 'to complete, to perfect'],
  ['أَظْلَم', 'eng zolim', 'самый несправедливый', 'most unjust'],
  ['أُفِكَ', 'burilmoq, aldanmoq', 'быть отвращённым', 'to be deluded, to be turned away'],
  ['أَلْباب', 'aqllar, idroklar', 'разумы', 'minds, understanding'],
  ['أَنۢبَتَ', 'o‘stirmoq, undirmoq', 'взращивать', 'to cause to grow'],
  ['اسْتَمَعَ', 'quloq solmoq', 'прислушиваться', 'to listen'],
  ['انتَهَى', 'to‘xtamoq, tugamoq', 'прекращать, заканчиваться', 'to desist, to cease'],
  ['بَسَطَ', 'yoymoq, kengaytirmoq', 'простирать, расширять', 'to spread out, to extend'],
  ['خَسِرَ', 'ziyon ko‘rmoq', 'терпеть убыток', 'to lose, to suffer loss'],
  ['داوُد', 'Dovud', 'Дауд', 'David'],
  ['سارَ', 'yurmoq, sayr qilmoq', 'идти, странствовать', 'to travel, to journey'],
  ['سَعِير', 'alangali olov', 'пылающий огонь', 'blazing fire'],
  ['سُنَّة', 'sunnat, yo‘l, odat', 'установление, обычай', 'way, established practice'],
  ['طَيِّب', 'pok, yaxshi', 'благой, чистый', 'good, pure'],
  ['فُؤاد', 'yurak, dil', 'сердце', 'heart'],
  ['فَتَحَ', 'ochmoq; g‘alaba bermoq', 'открывать; даровать победу', 'to open; to grant victory'],
  ['فَرِحَ', 'xursand bo‘lmoq', 'радоваться', 'to rejoice'],
  ['قَدَّرَ', 'taqdir qilmoq, o‘lchamoq', 'предопределять, измерять', 'to decree, to measure'],
  ['قَرَأَ', 'o‘qimoq', 'читать', 'to read, to recite'],
  ['قُرْبَى', 'qarindoshlik, yaqinlik', 'родство, близость', 'kinship, nearness'],
  ['مَرْجِع', 'qaytish joyi', 'место возвращения', 'place of return'],
  ['مَنَّ', 'minnat qilmoq; ne’mat bermoq', 'оказывать милость; попрекать', 'to bestow favour; to reproach'],
  ['مِيزان', 'tarozi, mezon', 'весы', 'balance, scale'],
  ['هاجَرَ', 'hijrat qilmoq', 'переселяться', 'to emigrate'],
  ['وَقَى', 'saqlamoq, himoya qilmoq', 'оберегать', 'to protect, to guard'],
  ['يَعْقُوب', 'Ya’qub', 'Якуб', 'Jacob'],
  ['أَتْبَعَ', 'ergashtirmoq, ketidan yubormoq', 'заставлять следовать', 'to make follow'],
  ['أَخَّرَ', 'kechiktirmoq', 'откладывать', 'to delay, to postpone'],
  ['أَغْنَى', 'boy qilmoq, foyda bermoq', 'обогащать, избавлять', 'to enrich, to avail'],
  ['أَفْسَدُ', 'buzmoq, fasod qilmoq', 'портить, сеять нечестие', 'to corrupt, to spread mischief'],
  ['أُوذِيَ', 'aziyat berilmoq', 'быть подвергнутым обиде', 'to be harmed'],
  ['اعْتَدَى', 'haddan oshmoq, tajovuz qilmoq', 'преступать, нападать', 'to transgress, to attack'],
  ['بُشْرَى', 'xushxabar', 'благая весть', 'good tidings'],
  ['بَلاغ', 'yetkazish, xabar', 'донесение, извещение', 'conveyance, notification'],
  ['تَنزِيل', 'nozil qilish', 'ниспослание', 'revelation, sending down'],
  ['حَرَج', 'qiyinchilik, tanglik', 'затруднение', 'hardship, constraint'],
  ['حَلِيم', 'halim, muloyim', 'кроткий, снисходительный', 'forbearing'],
  ['رِجْل', 'oyoq', 'нога', 'foot, leg'],
  ['سَكَنَ', 'yashamoq, sokin bo‘lmoq', 'обитать, успокаиваться', 'to dwell, to be still'],
  ['شَرِبَ', 'ichmoq', 'пить', 'to drink'],
  ['شَكّ', 'shubha', 'сомнение', 'doubt'],
  ['صَبْر', 'sabr', 'терпение', 'patience'],
  ['صَدَقَ', 'rost aytmoq', 'говорить правду', 'to tell the truth'],
  ['صَنَعُ', 'yasamoq, qilmoq', 'изготавливать', 'to make, to craft'],
  ['ظَهْر', 'orqa, yelka', 'спина', 'back'],
  ['غَرَّ', 'aldamoq, mag‘rur qilmoq', 'обольщать', 'to deceive, to delude'],
  ['غَلَبُ', 'g‘olib bo‘lmoq', 'побеждать', 'to overcome, to prevail'],
  ['قِسْط', 'adolat, insof', 'справедливость', 'justice, equity'],
  ['كُلَّما', 'har safar', 'каждый раз, когда', 'whenever'],
  ['مُسْرِف', 'isrofgar, haddan oshuvchi', 'расточительный, преступающий', 'extravagant, transgressing'],
  ['مِلَّة', 'millat, din yo‘li', 'религия, вероучение', 'religion, creed'],
  ['مَلِك', 'podshoh, malik', 'царь', 'king'],
  ['مُنذِر', 'ogohlantiruvchi', 'предостерегающий', 'warner'],
  ['نَصْرانِيّ', 'nasroniy, xristian', 'христианин', 'Christian'],
  ['وَعَظْ', 'nasihat qilmoq', 'наставлять', 'to admonish'],
  ['يُبْدِيَ', 'oshkor qilmoq', 'обнаруживать', 'to disclose, to reveal'],
  ['يَسِير', 'oson, yengil', 'лёгкий', 'easy'],
  ['أَثَر', 'iz, asar', 'след', 'trace, footstep'],
  ['أُخْت', 'singil, opa', 'сестра', 'sister'],
  ['أَخْلَفُ', 'va’daga xilof qilmoq', 'нарушать обещание', 'to break a promise'],
  ['أَعْتَدَتْ', 'tayyorlab qo‘ymoq', 'приготовить', 'to prepare'],
  ['أَلْف', 'ming', 'тысяча', 'thousand'],
  ['أَمِين', 'ishonchli, omonatdor', 'верный, надёжный', 'trustworthy'],
  ['ابْتِغاء', 'izlash, talab qilish', 'стремление, поиск', 'seeking'],
  ['بَلَد', 'shahar, yurt', 'город, страна', 'city, land'],
  ['تَعالَى', 'oliy bo‘lmoq, ulug‘ bo‘lmoq', 'быть превыше', 'to be exalted'],
  ['حُدُود', 'hadlar, chegaralar', 'границы, пределы', 'limits, bounds'],
  ['حَلَلْ', 'halol bo‘lmoq, tushmoq', 'быть дозволенным; настигать', 'to be lawful; to befall'],
  ['خاشِع', 'xushu’ qiluvchi, tavoze’li', 'смиренный', 'humbly submissive'],
  ['شاكِر', 'shukr qiluvchi', 'благодарный', 'grateful'],
  ['صِدْق', 'rostlik, sidq', 'правдивость', 'truthfulness'],
  ['صَرَفَ', 'burmoq, qaytarmoq', 'отвращать, отводить', 'to turn away, to avert'],
  ['ضالّ', 'adashgan', 'заблудший', 'astray'],
  ['ظِلّ', 'soya', 'тень', 'shade, shadow'],
  ['عَدَلَ', 'adolat qilmoq; teng qo‘ymoq', 'быть справедливым; приравнивать', 'to be just; to equate'],
  ['عَدْل', 'adolat', 'справедливость', 'justice'],
  ['غَضَب', 'g‘azab', 'гнев', 'anger, wrath'],
  ['قادِر', 'qodir, qudratli', 'способный, могущественный', 'able, powerful'],
  ['كَشَفَ', 'ochmoq, ko‘tarmoq (balo)', 'снимать, устранять', 'to remove, to uncover'],
  ['كَفَّرَ', 'gunohlarini o‘chirmoq, kafforat qilmoq', 'искупать, стирать грехи', 'to expiate, to remove sins'],
  ['لَعْنَة', 'la’nat', 'проклятие', 'curse'],
  ['لَقُ', 'uchramoq, duch kelmoq', 'встречать', 'to meet, to encounter'],
  ['لَيْت', 'qani edi, koshki', 'если бы', 'would that'],
  ['مَدِينَة', 'shahar, Madina', 'город, Медина', 'city, Medina'],
  ['مَقام', 'maqom, turar joy', 'место стояния', 'station, standing place'],
  ['مُهِين', 'xor qiluvchi, tahqirli', 'унизительный', 'humiliating'],
  ['نَكَحَ', 'nikohlanmoq, uylanmoq', 'жениться', 'to marry'],
  ['والِد', 'ota-ona', 'родитель', 'parent'],
  ['أَبَى', 'bosh tortmoq, rad qilmoq', 'отказываться', 'to refuse'],
  ['أَسْمَعَ', 'eshittirmoq', 'давать услышать', 'to make hear'],
  ['أَطْعَمَ', 'ovqatlantirmoq', 'кормить', 'to feed'],
  ['اثْنَيْن', 'ikki, ikkovi', 'два', 'two'],
  ['بَغْتَة', 'to‘satdan', 'внезапно', 'suddenly'],
  ['تَرَبَّصْ', 'kutmoq, poylab turmoq', 'выжидать', 'to wait, to await'],
  ['ثَلاثَة', 'uch', 'три', 'three'],
  ['ثَواب', 'savob, mukofot', 'награда', 'reward'],
  ['جَمْع', 'to‘plam, jamlanish', 'собрание', 'gathering, assembly'],
  ['حافِظ', 'saqlovchi, hofiz', 'хранитель', 'guardian, preserver'],
  ['حَرْث', 'ekin, ekinzor', 'посев, пашня', 'tilth, crops'],
  ['حُسْن', 'go‘zallik, yaxshilik', 'красота, благо', 'beauty, goodness'],
  ['رِضْوان', 'rizolik, Allohning roziligi', 'благоволение', 'good pleasure, approval'],
  ['زَعَمَ', 'da’vo qilmoq, o‘ylab aytmoq', 'утверждать, полагать', 'to claim, to allege'],
  ['سَوَّى', 'tekislamoq, mukammal qilmoq', 'выравнивать, устраивать', 'to fashion, to proportion'],
  ['شَفاعَة', 'shafoat', 'заступничество', 'intercession'],
  ['صَدَقَة', 'sadaqa', 'милостыня', 'charity'],
  ['صَيْحَة', 'qichqiriq, sayha', 'вопль, крик', 'blast, cry'],
  ['عِظام', 'suyaklar', 'кости', 'bones'],
  ['غالِب', 'g‘olib', 'победитель', 'dominant, victorious'],
  ['غَشِيَ', 'qoplamoq, o‘ramoq', 'покрывать, окутывать', 'to cover, to overwhelm'],
  ['غُلام', 'o‘g‘il bola, yigit', 'мальчик, юноша', 'boy, youth'],
  ['قِتال', 'jang, urush', 'сражение', 'fighting, combat'],
  ['مَثْوًى', 'turar joy, manzil', 'обитель, пристанище', 'abode, dwelling'],
  ['مَدَّ', 'cho‘zmoq, uzaytirmoq', 'простирать, продлевать', 'to extend, to stretch'],
  ['مَرَض', 'kasallik', 'болезнь', 'illness, disease'],
  ['مُفْلِح', 'najot topuvchi', 'преуспевающий', 'successful one'],
  ['مَكَّ', 'imkon bermoq, mustahkamlamoq', 'наделять властью, укреплять', 'to establish, to empower'],
  ['نَجْم', 'yulduz', 'звезда', 'star'],
  ['وَرِثَ', 'meros olmoq', 'наследовать', 'to inherit'],
  ['يَصِفُ', 'sifatlamoq, ta’riflamoq', 'описывать', 'to describe, to ascribe'],
  ['يَصْلَى', 'olovga kirmoq, kuymoq', 'гореть, входить в огонь', 'to burn in, to enter the fire'],
  ['أَخْزَيْ', 'xor qilmoq, sharmanda qilmoq', 'опозорить', 'to disgrace'],
  ['أَدْنَى', 'eng yaqin, pastroq', 'ближайший, низший', 'nearest, lower'],
  ['أَرْحام', 'bachadonlar; qarindoshlik', 'утробы; родственные узы', 'wombs; kinship'],
  ['أَصَمّ', 'kar', 'глухой', 'deaf'],
  ['أَعْلَن', 'oshkor qilmoq', 'объявлять', 'to declare openly'],
  ['أَفْواه', 'og‘izlar', 'уста', 'mouths'],
  ['أَوْرَثَ', 'meros qilib bermoq', 'давать в наследство', 'to bequeath, to make inherit'],
  ['إِحْسان', 'ehson, yaxshilik qilish', 'благодеяние', 'excellence, doing good'],
  ['إِسْماعِيل', 'Ismoil', 'Исмаил', 'Ishmael'],
  ['إِمام', 'imom, yetakchi; kitob', 'предводитель; писание', 'leader, imam; record'],
  ['إِنجِيل', 'Injil', 'Евангелие', 'Gospel'],
  ['اسْتَأْذَنَ', 'izn so‘ramoq', 'просить разрешения', 'to ask permission'],
  ['اصْطَفَى', 'tanlab olmoq, saylamoq', 'избирать', 'to choose, to select'],
  ['بَدَأَ', 'boshlamoq', 'начинать', 'to begin'],
  ['بَرِيء', 'beg‘ubor, uzoq', 'непричастный', 'free of, disassociated'],
  ['تَدْرِي', 'bilmoq', 'знать', 'to know'],
  ['تَوّاب', 'tavbalarni ko‘p qabul qiluvchi', 'принимающий покаяние', 'accepting of repentance'],
  ['جَحَدُ', 'inkor qilmoq', 'отрицать', 'to deny, to reject'],
  ['حاجَّ', 'bahslashmoq, dalil keltirmoq', 'спорить, приводить доводы', 'to argue, to dispute'],
  ['حَبِطَ', 'behuda ketmoq, botil bo‘lmoq', 'пропадать даром', 'to become worthless'],
  ['حَفِيظ', 'saqlovchi, nazorat qiluvchi', 'хранитель', 'guardian, preserver'],
  ['حَلَفْ', 'qasam ichmoq', 'клясться', 'to swear'],
  ['حَنِيف', 'hanif, sof tavhid yo‘lida', 'ханиф, единобожник', 'upright monotheist'],
  ['خالِق', 'yaratuvchi, xoliq', 'творец', 'creator'],
  ['خَرَّ', 'yiqilmoq, quladi', 'падать ниц', 'to fall down'],
  ['زَكَّى', 'poklamoq, tarbiyalamoq', 'очищать', 'to purify'],
  ['سَقَى', 'suv bermoq, sug‘ormoq', 'поить', 'to give to drink'],
  ['سَلَكَ', 'kirmoq, yo‘lga solmoq', 'вводить, направлять', 'to insert, to make enter'],
  ['سِنِين', 'yillar', 'годы', 'years'],
  ['صاحِب', 'sohib, hamroh', 'спутник, обладатель', 'companion, owner'],
  ['صَلَّى', 'namoz o‘qimoq, salavot aytmoq', 'молиться', 'to pray, to invoke blessings'],
  ['طَغَى', 'tug‘yon qilmoq, haddan oshmoq', 'бесчинствовать, преступать', 'to transgress, to tyrannise'],
  ['طِين', 'loy', 'глина', 'clay'],
  ['عامِل', 'ish qiluvchi, amal qiluvchi', 'делающий, работник', 'doer, worker'],
  ['فَتْح', 'fath, g‘alaba; ochilish', 'победа; открытие', 'victory; opening'],
  ['فَقِير', 'faqir, kambag‘al', 'бедный, нуждающийся', 'poor, needy'],
  ['قَطَّعَ', 'kesmoq, bo‘lak-bo‘lak qilmoq', 'рассекать, разделять', 'to cut up, to sever'],
  ['قُطِعَ', 'kesilmoq, uzilmoq', 'быть отсечённым', 'to be cut off'],
  ['قَعَدَ', 'o‘tirmoq, qolib ketmoq', 'сидеть, отсиживаться', 'to sit, to stay behind'],
  ['كَفُور', 'nonko‘r, kufr qiluvchi', 'неблагодарный', 'ungrateful'],
  ['لَحْم', 'go‘sht', 'мясо', 'meat, flesh'],
  ['مَسْكَن', 'turar joy, maskan', 'жилище', 'dwelling'],
  ['مُعْجِز', 'ojiz qoldiruvchi, qochib qutuluvchi', 'способный ускользнуть', 'one who escapes, frustrates'],
  ['مَنَعَ', 'man qilmoq, to‘smoq', 'препятствовать', 'to prevent, to withhold'],
  ['مَوْعِد', 'va’da qilingan vaqt yoki joy', 'назначенный срок или место', 'appointed time or place'],
  ['نُطْفَة', 'nutfa, tomchi', 'капля семени', 'sperm-drop'],
  ['وِزْر', 'yuk, gunoh', 'бремя, грех', 'burden, sin'],
  ['وَقَعَ', 'sodir bo‘lmoq, tushmoq', 'случаться, падать', 'to occur, to befall'],
  ['يَحْذَرُ', 'ehtiyot bo‘lmoq, qo‘rqmoq', 'остерегаться', 'to beware, to be cautious'],
  ['يُنظَرُ', 'muhlat berilmoq', 'получать отсрочку', 'to be given respite'],
  ['يُوقِنُ', 'yaqin qilmoq, ishonch hosil qilmoq', 'быть убеждённым', 'to be certain'],
  ['أَحْصَى', 'sanab chiqmoq, hisoblab olmoq', 'исчислять', 'to count, to enumerate'],
  ['أَذْهَبَ', 'ketkazmoq, yo‘qotmoq', 'уводить, устранять', 'to take away, to remove'],
  ['أَعْجَبَ', 'hayratlantirmoq, yoqmoq', 'восхищать, нравиться', 'to please, to impress'],
  ['أَنابَ', 'tavba bilan qaytmoq', 'обращаться с покаянием', 'to turn in repentance'],
  ['أَوْلَى', 'haqliroq, yaqinroq', 'более достойный', 'more deserving, closer'],
  ['إِبْلِيس', 'Iblis', 'Иблис', 'Iblis, Satan'],
  ['إِحْدَى', 'biri (ayol shakli)', 'одна из', 'one of (fem.)'],
  ['بَدا', 'ko‘rinmoq, oshkor bo‘lmoq', 'появляться, становиться явным', 'to appear, to become evident'],
  ['بَغْي', 'zulm, haddan oshish', 'притеснение, злоба', 'transgression, envy'],
  ['بَنَى', 'qurmoq', 'строить', 'to build'],
  ['تَمَتَّعَ', 'bahramand bo‘lmoq', 'наслаждаться', 'to enjoy'],
  ['ثَمَن', 'baho, narx', 'цена', 'price'],
  ['حَسْب', 'yetarli, kifoya', 'достаточно', 'sufficient'],
  ['خِزْى', 'xorlik, sharmandalik', 'позор', 'disgrace, humiliation'],
  ['رَءُوف', 'shafqatli, mehribon', 'сострадательный', 'compassionate, kind'],
  ['سَخِرَ', 'masxara qilmoq', 'насмехаться', 'to ridicule, to mock'],
  ['سِرّ', 'sir', 'тайна', 'secret'],
  ['شَراب', 'ichimlik', 'питьё, напиток', 'drink'],
  ['شُعَيْب', 'Shuayb', 'Шуайб', 'Shuayb'],
  ['شِيعَة', 'guruh, tarafdorlar', 'группа, сторонники', 'sect, faction'],
  ['ضِعْف', 'ikki barobar; zaiflik', 'вдвое; слабость', 'double; weakness'],
  ['طَبَعَ', 'muhrlamoq', 'запечатывать', 'to seal'],
  ['عابِد', 'ibodat qiluvchi', 'поклоняющийся', 'worshipper'],
  ['عاهَدَ', 'ahdlashmoq', 'заключать договор', 'to make a covenant'],
  ['عِدَّة', 'sanoq, muddat, idda', 'число, срок', 'number, appointed period'],
  ['عَدْن', 'Adn (jannat)', 'Адн (рай)', 'Eden'],
  ['عَرَبِيّ', 'arabcha', 'арабский', 'Arabic'],
  ['عَرَضَ', 'ko‘rsatmoq, taqdim qilmoq', 'представлять, показывать', 'to present, to display'],
  ['عِزَّة', 'izzat, qudrat, mag‘rurlik', 'могущество, гордость', 'might, honour, pride'],
  ['عَلِيّ', 'oliy, ulug‘', 'высокий, возвышенный', 'exalted, most high'],
  ['عِنَب', 'uzum', 'виноград', 'grapes'],
  ['فاكِهَة', 'meva', 'фрукты', 'fruit'],
  ['فَساد', 'fasod, buzuqlik', 'нечестие, порча', 'corruption, mischief'],
  ['قَدَر', 'taqdir, o‘lchov', 'мера, предопределение', 'measure, decree'],
  ['قَوِيّ', 'kuchli, qavi', 'сильный', 'strong'],
  ['كَثِيرَة', 'ko‘p (ayol shakli)', 'многая', 'many, much (fem.)'],
  ['كَذَبَ', 'yolg‘on gapirmoq', 'лгать', 'to lie'],
  ['لَبَسْ', 'kiymoq; aralashtirmoq', 'надевать; смешивать', 'to wear; to confuse'],
  ['مَجْنُون', 'majnun, telba', 'одержимый, безумный', 'possessed, mad'],
  ['مُخْلِص', 'ixlosli, sof niyatli', 'искренний', 'sincere'],
  ['مَسِيح', 'Masih', 'Мессия', 'Messiah'],
  ['مَشْرِق', 'sharq, chiqish joyi', 'восток', 'east, place of sunrise'],
  ['مَعْلُوم', 'ma’lum, belgilangan', 'известный, определённый', 'known, appointed'],
  ['ناصِر', 'yordamchi, nosir', 'помощник', 'helper'],
  ['نَجْوَى', 'yashirin suhbat', 'тайная беседа', 'secret conversation'],
  ['نَخْل', 'xurmo daraxti', 'финиковые пальмы', 'date palms'],
  ['نَفْع', 'foyda', 'польза', 'benefit'],
  ['هادُ', 'yahudiy bo‘lmoq', 'быть иудеем', 'to be a Jew'],
  ['هُزُو', 'masxara, kulgi', 'насмешка', 'mockery'],
  ['هَواء', 'havo; bo‘shliq', 'воздух; пустота', 'air; emptiness'],
  ['وَصَّى', 'vasiyat qilmoq, tayinlamoq', 'завещать, наставлять', 'to enjoin, to bequeath'],
  ['يَسَّرَ', 'osonlashtirmoq', 'облегчать', 'to make easy'],
  ['يَقْرَبُ', 'yaqinlashmoq', 'приближаться', 'to draw near'],
  ['يَنالُ', 'yetishmoq, erishmoq', 'достигать', 'to attain, to reach'],
  ['أَحَقّ', 'haqliroq', 'более достойный', 'more entitled, worthier'],
  ['أَضاعُ', 'zoe qilmoq, yo‘qotmoq', 'терять, губить', 'to waste, to lose'],
  ['أَعْراب', 'badaviy arablar', 'бедуины', 'bedouins'],
  ['أَمَدَّ', 'madad bermoq, ko‘paytirmoq', 'подкреплять, продлевать', 'to supply, to extend'],
  ['اجْتَبَى', 'tanlab olmoq', 'избирать', 'to choose, to select'],
  [
    'اسْتَقامُ',
    'to‘g‘ri turmoq, mustaqim bo‘lmoq',
    'быть стойким на прямом пути',
    'to be upright, to remain steadfast'
  ],
  ['بَخِلَ', 'baxillik qilmoq', 'скупиться', 'to be miserly'],
  ['تَقَبَّلَ', 'qabul qilmoq', 'принимать', 'to accept'],
  ['ثَبَّتْ', 'mustahkamlamoq, sobit qilmoq', 'укреплять', 'to make firm, to strengthen'],
  ['جاهِل', 'johil, bilimsiz', 'невежда', 'ignorant one'],
  ['جَبّار', 'jabbor, zo‘ravon; Qudratli', 'тиран; Всемогущий', 'tyrant; the Compeller']
] as const
