import { WORD_GLOSSES_300 } from './glossary-300'
import { WORD_GLOSSES_550 } from './glossary-550'
import { WORD_GLOSSES_800 } from './glossary-800'
import { WORD_GLOSSES_1050 } from './glossary-1050'
import { WORD_GLOSSES_1300 } from './glossary-1300'
import { WORD_GLOSSES_1800 } from './glossary-1800'
import type { Gloss } from './glossary-types'
import { ROOT_GLOSSES_2 } from './root-glossary-2'

export type { Gloss }

/** Quranic lemmas ranked 1-299 by frequency. See glossary-types.ts for conventions. */
const WORD_GLOSSES_1: readonly Gloss[] = [
  ['مِن', '...dan', 'из, от', 'from'],
  ['اللَّه', 'Alloh', 'Аллах', 'Allah'],
  ['ما', 'nima; ...emas', 'что; не', 'what; not'],
  ['لا', 'yo‘q, ...ma', 'не, нет', 'no, not'],
  ['فِي', '...da, ichida', 'в', 'in'],
  ['إِنّ', 'albatta, haqiqatan', 'поистине', 'indeed'],
  ['قالَ', 'aytmoq', 'сказать', 'to say'],
  ['الَّذِي', 'ki, qaysiki', 'который', 'who, which'],
  ['عَلَى', '...ustida, ...ga', 'на', 'on, upon'],
  ['كانَ', 'bo‘lmoq', 'быть', 'to be'],
  ['ذا', 'bu, mana bu', 'этот', 'this'],
  ['رَبّ', 'Rabb, parvardigor', 'Господь', 'Lord'],
  ['مَن', 'kim', 'кто', 'who'],
  ['إِلَى', '...ga, tomon', 'к, до', 'to, towards'],
  ['إِن', 'agar', 'если', 'if'],
  ['إِلّا', '...dan boshqa, magar', 'кроме, except', 'except'],
  ['أَن', '...ligini, ...moq', 'что, чтобы', 'that, to'],
  ['آمَنَ', 'imon keltirmoq', 'уверовать', 'to believe'],
  ['يَوْم', 'kun', 'день', 'day'],
  ['عَن', '...dan, haqida', 'от, о', 'from, about'],
  ['أَرْض', 'yer, zamin', 'земля', 'earth, land'],
  ['إِذا', 'qachonki', 'когда', 'when'],
  ['قَد', 'albatta; ba’zan', 'уже, действительно', 'indeed, already'],
  ['قَوْم', 'qavm, xalq', 'народ', 'people, folk'],
  ['آيَة', 'oyat; belgi', 'знамение, аят', 'sign, verse'],
  ['عَلِمَ', 'bilmoq', 'знать', 'to know'],
  ['أَنّ', '...ligini', 'что', 'that'],
  ['كُلّ', 'har, hamma', 'каждый, весь', 'every, all'],
  ['لَم', '...madi', 'не (прош.)', 'did not'],
  ['جَعَلَ', 'qilmoq, aylantirmoq', 'сделать', 'to make'],
  ['ثُمّ', 'so‘ng, keyin', 'затем', 'then'],
  ['رَسُول', 'rasul, elchi', 'посланник', 'messenger'],
  ['عَذاب', 'azob', 'наказание', 'punishment'],
  ['سَماء', 'osmon', 'небо', 'sky, heaven'],
  ['إِذ', 'o‘shanda, vaqtida', 'когда, вот', 'when'],
  ['نَفْس', 'nafs, jon; o‘zi', 'душа, сам', 'soul, self'],
  ['كَفَرَ', 'kufr keltirmoq', 'не веровать', 'to disbelieve'],
  ['شَىْء', 'narsa', 'вещь', 'thing'],
  ['أَو', 'yoki', 'или', 'or'],
  ['جاءَ', 'kelmoq', 'приходить', 'to come'],
  ['عَمِلَ', 'amal qilmoq', 'делать', 'to do, to work'],
  ['آتَى', 'bermoq, ato qilmoq', 'давать', 'to give'],
  ['رَأَى', 'ko‘rmoq', 'видеть', 'to see'],
  ['بَيْن', 'orasida', 'между', 'between'],
  ['أَتَى', 'kelmoq', 'приходить', 'to come'],
  ['كِتاب', 'kitob', 'книга, писание', 'book, scripture'],
  ['حَقّ', 'haq, haqiqat', 'истина', 'truth, right'],
  ['قَبْل', 'oldin', 'до, прежде', 'before'],
  ['ناس', 'odamlar', 'люди', 'people'],
  ['شاءَ', 'xohlamoq', 'желать', 'to will, to wish'],

  ['أَيّ', 'qaysi', 'какой', 'which'],
  ['مُؤْمِن', 'mo‘min', 'верующий', 'believer'],
  ['لَو', 'agar (bo‘lsa edi)', 'если бы', 'if (only)'],
  ['بَعْد', 'keyin, so‘ng', 'после', 'after'],
  ['عِند', 'yonida, huzurida', 'у, при', 'with, near'],
  ['خَلَقَ', 'yaratmoq', 'творить', 'to create'],
  ['أَنزَلَ', 'nozil qilmoq', 'ниспослать', 'to send down'],
  ['خَيْر', 'yaxshilik; yaxshiroq', 'добро; лучше', 'good; better'],
  ['سَبِيل', 'yo‘l', 'путь', 'way, path'],
  ['كَذَّبَ', 'yolg‘onga chiqarmoq', 'считать ложью', 'to deny, to call a lie'],
  ['دَعا', 'chaqirmoq, duo qilmoq', 'звать, взывать', 'to call, to pray'],
  ['أَمْر', 'ish; buyruq', 'дело; приказ', 'matter; command'],
  ['اتَّقَى', 'taqvo qilmoq, saqlanmoq', 'быть богобоязненным', 'to fear God, to be mindful'],
  ['لَمّا', 'hali ...ma; qachonki', 'когда; ещё не', 'when; not yet'],
  ['مَع', 'bilan, birga', 'с, вместе', 'with'],
  ['عَلِيم', 'bilguvchi, alim', 'знающий', 'all-knowing'],
  ['بَعْض', 'ba’zi, qismi', 'некоторые', 'some, part'],
  ['ذُو', 'egasi, ...li', 'обладатель', 'possessor of'],
  ['كافِر', 'kofir', 'неверующий', 'disbeliever'],
  ['آخِر', 'oxirgi, oxirat', 'последний', 'last, hereafter'],
  ['إِلٰه', 'iloh, ma’bud', 'бог, божество', 'god, deity'],
  ['جَنَّة', 'jannat; bog‘', 'рай, сад', 'paradise, garden'],
  ['غَيْر', 'boshqa, ...siz', 'другой, кроме', 'other than'],
  ['نار', 'olov, do‘zax', 'огонь', 'fire'],
  ['دُون', '...dan boshqa, past', 'помимо, ниже', 'besides, below'],
  ['هَدَى', 'hidoyat qilmoq', 'вести прямым путём', 'to guide'],
  ['حَتَّى', 'toki, ...gacha', 'пока, до', 'until'],
  ['أَرادَ', 'iroda qilmoq, istamoq', 'желать', 'to want, to intend'],
  ['أَم', 'yoki, yoxud', 'или', 'or'],
  ['اتَّبَعَ', 'ergashmoq', 'следовать', 'to follow'],
  ['مُوسَى', 'Muso', 'Муса', 'Moses'],
  ['قَلْب', 'qalb, yurak', 'сердце', 'heart'],
  ['عَبْد', 'banda, qul', 'раб', 'servant, slave'],
  ['أَرْسَلَ', 'yubormoq', 'посылать', 'to send'],
  ['ظالِم', 'zolim', 'несправедливый', 'wrongdoer'],
  ['لَعَلّ', 'shoyad, balki', 'быть может', 'perhaps, so that'],
  ['أَخَذَ', 'olmoq, tutmoq', 'брать', 'to take'],
  ['أَهْل', 'ahl, oila', 'семья, обладатели', 'family, people of'],
  ['بَل', 'balki, yo‘q', 'напротив, но', 'rather, but'],
  ['اتَّخَذَ', 'tutmoq, qabul qilmoq', 'принимать, брать', 'to take (for oneself)'],
  ['عَبَدَ', 'ibodat qilmoq', 'поклоняться', 'to worship'],
  ['يَد', 'qo‘l', 'рука', 'hand'],
  ['مُبِين', 'ochiq-oydin', 'явный', 'clear, manifest'],
  ['رَحِيم', 'rahmli, mehribon', 'милосердный', 'merciful'],
  ['دُنْيا', 'dunyo', 'мирская жизнь', 'world, worldly life'],
  ['رَحْمَة', 'rahmat', 'милость', 'mercy'],
  ['ظَلَمَ', 'zulm qilmoq', 'притеснять', 'to wrong, to oppress'],
  ['عَظِيم', 'ulug‘, buyuk', 'великий', 'great, mighty'],
  ['سَأَلَ', 'so‘ramoq', 'спрашивать', 'to ask'],
  ['لَن', 'hech qachon ...maydi', 'никогда не', 'will never'],
  ['وَجَدَ', 'topmoq', 'находить', 'to find'],

  ['أَجْر', 'ajr, mukofot', 'награда', 'reward'],
  ['عِلْم', 'ilm, bilim', 'знание', 'knowledge'],
  ['عَزِيز', 'aziz, qudratli', 'могущественный', 'mighty, honoured'],
  ['أَخْرَجَ', 'chiqarmoq', 'выводить', 'to bring out'],
  ['حَكِيم', 'hakim, hikmatli', 'мудрый', 'wise'],
  ['أَكَلَ', 'yemoq', 'есть, кушать', 'to eat'],
  ['هَل', '...mi?', 'ли?', 'is/does…?'],
  ['دِين', 'din', 'религия', 'religion'],
  ['قَوْل', 'so‘z, gap', 'слово, речь', 'word, saying'],
  ['غَفُور', 'mag‘firat qiluvchi', 'прощающий', 'forgiving'],
  ['لَيْسَ', '...emas', 'не является', 'is not'],
  ['شَيْطان', 'shayton', 'сатана', 'Satan, devil'],
  ['فَعَلَ', 'qilmoq', 'делать', 'to do'],
  ['مَثَل', 'masal, misol', 'пример, притча', 'example, parable'],
  ['مَلَك', 'farishta', 'ангел', 'angel'],
  ['نَظَرَ', 'qaramoq', 'смотреть', 'to look'],
  ['مال', 'mol, boylik', 'имущество', 'wealth, property'],
  ['وَلِيّ', 'valiy, homiy, do‘st', 'покровитель', 'guardian, ally'],
  ['هُدًى', 'hidoyat', 'прямой путь', 'guidance'],
  ['ذَكَرَ', 'zikr qilmoq, eslamoq', 'поминать, помнить', 'to mention, to remember'],
  ['فَضْل', 'fazl, marhamat', 'милость, благодать', 'bounty, grace'],
  ['لَيْل', 'kecha, tun', 'ночь', 'night'],
  ['خافَ', 'qo‘rqmoq', 'бояться', 'to fear'],
  ['صَلاة', 'namoz', 'молитва', 'prayer'],
  ['قَتَلَ', 'o‘ldirmoq', 'убивать', 'to kill'],
  ['كَيْف', 'qanday', 'как', 'how'],
  ['أَوَّل', 'birinchi, avvalgi', 'первый', 'first'],
  ['أَكْثَر', 'ko‘pchilik, ko‘proq', 'большинство', 'most, more'],
  ['بُنَىّ', 'o‘g‘ilcham', 'сынок', 'my dear son'],
  ['رَجَعَ', 'qaytmoq', 'возвращаться', 'to return'],
  ['أَصْحاب', 'ahli, sohiblari', 'обитатели, спутники', 'companions, people of'],
  ['تَوَلَّى', 'yuz o‘girmoq', 'отвернуться', 'to turn away'],
  ['سَمِعَ', 'eshitmoq', 'слышать', 'to hear'],
  ['أَمَرَ', 'buyurmoq', 'приказывать', 'to command'],
  ['جَهَنَّم', 'jahannam', 'ад, геенна', 'Hell'],
  ['حَياة', 'hayot', 'жизнь', 'life'],
  ['دَخَلَ', 'kirmoq', 'входить', 'to enter'],
  ['ذِكْر', 'zikr, eslatma', 'напоминание', 'remembrance, reminder'],
  ['زَوْج', 'juft, er yoki xotin', 'супруг, пара', 'spouse, pair'],
  ['أَخ', 'aka-uka, birodar', 'брат', 'brother'],
  ['لَوْلا', 'agar ...bo‘lmasa edi', 'если бы не', 'if not for'],
  ['مِثْل', 'kabi, o‘xshash', 'подобный', 'like, similar'],
  ['نَبِيّ', 'nabiy, payg‘ambar', 'пророк', 'prophet'],
  ['أَحَد', 'bir kishi, hech kim', 'один, кто-либо', 'one, anyone'],
  ['خالِد', 'abadiy qoluvchi', 'вечно пребывающий', 'abiding forever'],
  ['صالِح', 'solih, yaxshi', 'праведный', 'righteous'],
  ['فِرْعَوْن', 'Fir’avn', 'Фараон', 'Pharaoh'],
  ['جَزَى', 'jazolamoq, mukofotlamoq', 'воздавать', 'to recompense'],
  ['عالَم', 'olam', 'мир, миры', 'world'],

  ['أَطاعَ', 'itoat qilmoq', 'повиноваться', 'to obey'],
  ['أَلِيم', 'alamli, og‘riqli', 'мучительный', 'painful'],
  ['أَوْحَى', 'vahiy qilmoq', 'внушать откровение', 'to reveal'],
  ['وَجْه', 'yuz, chehra', 'лицо', 'face'],
  ['أَشْرَكَ', 'shirk keltirmoq', 'придавать сотоварищей', 'to associate partners'],
  ['أَلْقَى', 'tashlamoq', 'бросать', 'to cast, to throw'],
  ['إِنسان', 'inson', 'человек', 'human being'],
  ['بَيِّنَة', 'aniq dalil', 'ясное знамение', 'clear proof'],
  ['عَمَل', 'amal, ish', 'дело, деяние', 'deed, work'],
  ['آخَر', 'boshqa', 'другой', 'another'],
  ['قُرْءان', 'Qur’on', 'Коран', 'Quran'],
  ['قَلِيل', 'oz, kam', 'малый', 'few, little'],
  ['قِيامَة', 'qiyomat', 'воскресение', 'resurrection'],
  ['وَعَدَ', 'va’da qilmoq', 'обещать', 'to promise'],
  ['إِبْراهِيم', 'Ibrohim', 'Ибрахим', 'Abraham'],
  ['أَنفَقَ', 'infoq qilmoq, sarflamoq', 'расходовать', 'to spend'],
  ['بَيْت', 'uy', 'дом', 'house'],
  ['غَفَرَ', 'kechirmoq', 'прощать', 'to forgive'],
  ['لٰكِن', 'lekin', 'но, однако', 'but'],
  ['لٰكِنّ', 'lekin, biroq', 'но, однако', 'but'],
  ['يَمِين', 'o‘ng; qasam', 'правая сторона; клятва', 'right hand; oath'],
  ['آباء', 'ota-bobolar', 'отцы, предки', 'forefathers'],
  ['أَحْبَبْ', 'sevmoq', 'любить', 'to love'],
  ['أَصابَ', 'yetmoq, duch kelmoq', 'постигать', 'to befall, to strike'],
  ['أَضَلَّ', 'adashtirmoq', 'вводить в заблуждение', 'to lead astray'],
  ['أُمَّة', 'ummat, jamoa', 'община', 'community, nation'],
  ['ابْن', 'o‘g‘il', 'сын', 'son'],
  ['تابَ', 'tavba qilmoq', 'каяться', 'to repent'],
  ['كَثِير', 'ko‘p', 'многий', 'many, much'],
  ['ماء', 'suv', 'вода', 'water'],
  ['صالِحَة', 'solih (ish), yaxshi', 'праведная', 'righteous (deed)'],
  ['كَسَبَ', 'kasb qilmoq, orttirmoq', 'приобретать', 'to earn'],
  ['نَزَّلَ', 'nozil qilmoq', 'ниспосылать', 'to send down'],
  ['تَلَى', 'tilovat qilmoq, o‘qimoq', 'читать, повествовать', 'to recite'],
  ['رَزَقَ', 'rizq bermoq', 'наделять уделом', 'to provide'],
  ['صادِق', 'sodiq, rostgo‘y', 'правдивый', 'truthful'],
  ['قَضَى', 'hukm qilmoq, bajarmoq', 'решать, завершать', 'to decree, to fulfil'],
  ['نِساء', 'ayollar', 'женщины', 'women'],
  ['نَصَرَ', 'yordam bermoq', 'помогать', 'to help, to support'],
  ['سَيِّئَة', 'yomonlik, gunoh', 'дурное деяние', 'evil deed'],
  ['صَبَرَ', 'sabr qilmoq', 'терпеть', 'to be patient'],
  ['نَذِير', 'ogohlantiruvchi', 'предостерегающий', 'warner'],
  ['جَرَيْ', 'oqmoq', 'течь', 'to flow'],
  ['رَحْمٰن', 'Rahmon', 'Милостивый', 'the Most Merciful'],
  ['عَيْن', 'ko‘z; buloq', 'глаз; источник', 'eye; spring'],
  ['قَرْيَة', 'qishloq, shahar', 'селение, город', 'town, village'],
  ['نَهار', 'kunduz', 'день (светлое время)', 'daytime'],
  ['شَدِيد', 'qattiq, shiddatli', 'суровый', 'severe, strong'],
  ['شَهِيد', 'shohid, guvoh', 'свидетель', 'witness'],
  ['مَسَّ', 'tegmoq', 'касаться', 'to touch'],

  ['وَلَد', 'bola, farzand', 'ребёнок', 'child'],
  ['أَمّا', 'ammo, ...ga kelsak', 'что же касается', 'as for'],
  ['رِزْق', 'rizq', 'удел, пропитание', 'provision'],
  ['ضَرَبَ', 'urmoq; keltirmoq (masal)', 'бить; приводить (пример)', 'to strike; to set forth'],
  ['أَقامَ', 'barpo qilmoq (namozni)', 'совершать, устанавливать', 'to establish'],
  ['قاتَلَ', 'jang qilmoq', 'сражаться', 'to fight'],
  ['نَهَر', 'daryo, ariq', 'река', 'river'],
  ['جَمِيع', 'hammasi, barchasi', 'все вместе', 'all together'],
  ['خَرَجَ', 'chiqmoq', 'выходить', 'to go out'],
  ['ضَلَّ', 'adashmoq', 'заблуждаться', 'to go astray'],
  ['أَجَل', 'ajal, muddat', 'срок', 'term, appointed time'],
  ['بَعَثَ', 'yubormoq; tiriltirmoq', 'посылать; воскрешать', 'to send; to resurrect'],
  ['خَلْق', 'yaratish, xilqat', 'творение', 'creation'],
  ['مُجْرِم', 'jinoyatchi, gunohkor', 'грешник', 'criminal, sinner'],
  ['أَحْيا', 'tiriltirmoq', 'оживлять', 'to give life'],
  ['أَهْلَكَ', 'halok qilmoq', 'губить', 'to destroy'],
  ['بَصِير', 'ko‘ruvchi', 'видящий', 'all-seeing'],
  ['تَحْت', 'ostida', 'под', 'under, beneath'],
  ['تَذَكَّرَ', 'eslamoq, ibrat olmoq', 'вспоминать', 'to take heed'],
  ['افْتَرَى', 'to‘qib chiqarmoq, bo‘hton qilmoq', 'измышлять', 'to fabricate'],
  ['سُوء', 'yomonlik', 'зло', 'evil'],
  ['عَدُوّ', 'dushman', 'враг', 'enemy'],
  ['مَوْت', 'o‘lim', 'смерть', 'death'],
  ['نِعْمَة', 'ne’mat', 'благо, милость', 'blessing, favour'],
  ['أَعْلَم', 'yaxshiroq biluvchi', 'лучше знающий', 'best knowing'],
  ['زادَ', 'ziyoda qilmoq, ko‘paytirmoq', 'увеличивать', 'to increase'],
  ['عَقَلُ', 'aql yuritmoq', 'разуметь', 'to reason, to understand'],
  ['غَيْب', 'g‘ayb, ko‘rinmas', 'сокровенное', 'the unseen'],
  ['كَتَبَ', 'yozmoq', 'писать', 'to write'],
  ['مُتَّقي', 'taqvodor', 'богобоязненный', 'God-fearing'],
  ['وَعْد', 'va’da', 'обещание', 'promise'],
  ['بَصَر', 'ko‘z, ko‘rish', 'зрение', 'sight'],
  ['دار', 'uy, maskan', 'обитель', 'abode, home'],
  ['ساعَة', 'soat; qiyomat soati', 'час', 'hour'],
  ['مُلْك', 'mulk, saltanat', 'власть, царство', 'dominion, kingdom'],
  ['سَمِيع', 'eshituvchi', 'слышащий', 'all-hearing'],
  ['ظَنَّ', 'gumon qilmoq, o‘ylamoq', 'полагать', 'to think, to assume'],
  ['أَب', 'ota', 'отец', 'father'],
  ['شَكَرَ', 'shukr qilmoq', 'благодарить', 'to be grateful'],
  ['نَبَّأَ', 'xabar bermoq', 'сообщать', 'to inform'],
  ['إِيمان', 'imon', 'вера', 'faith'],
  ['حَكَمَ', 'hukm qilmoq', 'судить', 'to judge'],
  ['خَبِير', 'xabardor', 'ведающий', 'all-aware'],
  ['صِراط', 'yo‘l, sirot', 'путь', 'path'],
  ['قَدِير', 'qodir, qudratli', 'всемогущий', 'all-powerful'],
  ['يَذَرَ', 'tark etmoq, qoldirmoq', 'оставлять', 'to leave'],
  ['أَنذَرَ', 'ogohlantirmoq', 'предостерегать', 'to warn'],
  ['حَسِبَ', 'hisoblamoq, o‘ylamoq', 'считать, полагать', 'to reckon, to think'],
  ['شَهِدَ', 'guvohlik bermoq', 'свидетельствовать', 'to bear witness'],
  ['صَدْر', 'ko‘krak, dil', 'грудь', 'breast, chest'],

  ['مُشْرِك', 'mushrik', 'многобожник', 'polytheist'],
  ['مَلَكَتْ', 'egalik qilmoq', 'владеть', 'to possess'],
  ['نادَى', 'nido qilmoq, chaqirmoq', 'взывать', 'to call out'],
  ['إِسْرائِيل', 'Isroil', 'Исраил', 'Israel'],
  ['حَمْد', 'hamd, maqtov', 'хвала', 'praise'],
  ['نُوح', 'Nuh', 'Нух', 'Noah'],
  ['نُور', 'nur, yorug‘lik', 'свет', 'light'],
  ['أُدْخِلَ', 'kiritilmoq', 'быть введённым', 'to be admitted'],
  ['اسْتَطاعَ', 'qodir bo‘lmoq', 'быть в состоянии', 'to be able'],
  ['جَزاء', 'jazo, mukofot', 'воздаяние', 'recompense'],
  ['سَبَّحَ', 'tasbih aytmoq', 'славословить', 'to glorify'],
  ['سَلام', 'salom, tinchlik', 'мир, приветствие', 'peace'],
  ['سَوْف', 'tez orada (kelasi zamon)', 'вскоре', 'will, shall'],
  ['كَلِمَة', 'so‘z, kalima', 'слово', 'word'],
  ['بَحْر', 'dengiz', 'море', 'sea'],
  ['حَمَلَ', 'ko‘tarmoq, yuklamoq', 'нести', 'to carry, to bear'],
  ['سُبْحان', 'poklik, tasbih', 'пречист', 'glory be to'],
  ['عَذَّبَ', 'azoblamoq', 'наказывать', 'to punish'],
  ['عَلَّمَ', 'o‘rgatmoq', 'обучать', 'to teach'],
  ['فَوْق', 'ustida, yuqorida', 'над', 'above'],
  ['أَرَيْ', 'ko‘rsatmoq', 'показывать', 'to show'],
  ['اسْتَغْفَرَ', 'mag‘firat so‘ramoq', 'просить прощения', 'to seek forgiveness'],
  ['اسْتَكْبَرَ', 'kibr qilmoq', 'превозноситься', 'to be arrogant'],
  ['اهْتَدَى', 'hidoyat topmoq', 'следовать прямым путём', 'to be guided'],
  ['بِئْسَ', 'naqadar yomon', 'как скверно', 'wretched is'],
  ['بَلَغَ', 'yetmoq, yetkazmoq', 'достигать', 'to reach'],
  ['تَرَكَ', 'tark etmoq', 'оставлять', 'to leave'],
  ['تَوَكَّلْ', 'tavakkul qilmoq', 'уповать', 'to rely, to trust'],
  ['خَشِيَ', 'qo‘rqmoq, hayiqmoq', 'страшиться', 'to fear'],
  ['شَرِيك', 'sherik', 'сотоварищ', 'partner, associate'],
  ['كَبِير', 'katta, ulug‘', 'большой, великий', 'great, large'],
  ['وَيْل', 'voy holiga, halokat', 'горе', 'woe'],
  ['أَلا', 'ogoh bo‘ling!', 'о да!, внемлите', 'behold, indeed'],
  ['إِذْن', 'izn, ruxsat', 'дозволение', 'permission'],
  ['اسْم', 'ism, nom', 'имя', 'name'],
  ['جَبَل', 'tog‘', 'гора', 'mountain'],
  ['حَرَّمَ', 'harom qilmoq, taqiqlamoq', 'запрещать', 'to forbid'],
  ['حِساب', 'hisob', 'расчёт', 'reckoning, account'],
  ['ماتَ', 'o‘lmoq', 'умирать', 'to die'],
  ['مُسْلِم', 'musulmon', 'мусульманин', 'Muslim'],
  ['بُشِّرَ', 'xushxabar berilmoq', 'быть обрадованным вестью', 'to be given glad tidings'],
  ['رَضِيَ', 'rozi bo‘lmoq', 'быть довольным', 'to be pleased'],
  ['ضَلال', 'zalolat, adashish', 'заблуждение', 'error, misguidance'],
  ['مُحْسِن', 'ehson qiluvchi', 'творящий добро', 'doer of good'],
  ['مَعْرُوف', 'ma’ruf, yaxshilik', 'одобряемое', 'what is right, kindness'],
  ['مَيِّت', 'o‘lik', 'мёртвый', 'dead'],
  ['بَشَر', 'bashar, inson', 'человек', 'human, mankind'],
  ['حَشَرَ', 'to‘plamoq (mahsharga)', 'собирать', 'to gather'],
  ['ذَنب', 'gunoh', 'грех', 'sin']
] as const

/**
 * Semantic field of the highest-frequency roots. A root is not a word — the
 * gloss names the idea the whole family shares, which is what makes the
 * derivation pattern learnable.
 */
const ROOT_GLOSSES_1: readonly Gloss[] = [
  ['أله', 'ilohiylik, ibodat', 'божественность', 'divinity, worship'],
  ['قول', 'aytish, so‘z', 'речь, слово', 'saying, speech'],
  ['كون', 'bo‘lish, mavjudlik', 'бытие', 'being, existence'],
  ['ربب', 'tarbiya, egalik', 'господство, воспитание', 'lordship, nurturing'],
  ['أمن', 'omonlik, ishonch', 'безопасность, вера', 'safety, trust, faith'],
  ['علم', 'bilish, ilm', 'знание', 'knowing'],
  ['قوم', 'turish, barpo qilish', 'вставание, стойкость', 'standing, establishing'],
  ['أيي', 'belgi, alomat', 'знамение', 'sign'],
  ['أتي', 'kelish, keltirish', 'приход', 'coming, bringing'],
  ['كفر', 'yopish, inkor qilish', 'сокрытие, неверие', 'covering, disbelief'],
  ['بين', 'oraliq, ravshanlik', 'между, ясность', 'between, clarity'],
  ['شيأ', 'xohlash, narsa', 'желание, вещь', 'willing, thing'],
  ['رسل', 'yuborish, elchilik', 'посланничество', 'sending, messengership'],
  ['يوم', 'kun', 'день', 'day'],
  ['أرض', 'yer', 'земля', 'earth'],
  ['نفس', 'jon, o‘zlik', 'душа, сам', 'soul, self'],
  ['عذب', 'azoblash', 'наказание', 'punishing'],
  ['سمو', 'balandlik, osmon, nom', 'высота, небо, имя', 'height, sky, name'],
  ['جعل', 'qilish, aylantirish', 'делание', 'making, rendering'],
  ['عمل', 'ish, amal', 'дело, труд', 'working, doing'],
  ['رأي', 'ko‘rish, fikr', 'видение, мнение', 'seeing, opinion'],
  ['كتب', 'yozish', 'писание', 'writing'],
  ['حقق', 'haqiqat, haqlilik', 'истина, право', 'truth, right'],
  ['قبل', 'oldinlik, qabul qilish', 'перед, принятие', 'before, accepting'],
  ['أنس', 'insonlik, unsiyat', 'человечность', 'humanity, familiarity'],
  ['خلق', 'yaratish', 'творение', 'creating'],
  ['نزل', 'tushish, nozil bo‘lish', 'нисхождение', 'descending'],
  ['خير', 'yaxshilik, afzallik', 'благо', 'good, better'],
  ['سبل', 'yo‘l', 'путь', 'way, path'],
  ['كذب', 'yolg‘on', 'ложь', 'lying'],
  ['دعو', 'chaqirish, duo', 'зов, мольба', 'calling, supplication'],
  ['أمر', 'ish, buyruq', 'дело, приказ', 'matter, command'],
  ['وقي', 'saqlanish, taqvo', 'оберегание, богобоязненность', 'guarding, piety'],
  ['بعض', 'qism', 'часть', 'part'],
  ['أخر', 'kechikish, oxirat', 'последующее', 'lateness, hereafter'],
  ['جنن', 'yashirish, bog‘, jin', 'сокрытие, сад', 'concealing, garden'],
  ['غير', 'boshqalik, o‘zgarish', 'иное, перемена', 'otherness, change'],
  ['نور', 'nur, olov', 'свет, огонь', 'light, fire'],
  ['هدي', 'yo‘l ko‘rsatish', 'наставление', 'guidance'],
  ['رود', 'istak, iroda', 'желание', 'wanting, seeking'],
  ['تبع', 'ergashish', 'следование', 'following'],
  ['قلب', 'qalb, aylanish', 'сердце, поворот', 'heart, turning'],
  ['عبد', 'qullik, ibodat', 'служение, поклонение', 'servitude, worship'],
  ['ظلم', 'zulm, qorong‘ulik', 'несправедливость, тьма', 'wrongdoing, darkness'],
  ['أخذ', 'olish, tutish', 'взятие', 'taking'],
  ['أهل', 'ahl, oila', 'семья, обитатели', 'family, people'],
  ['يدي', 'qo‘l', 'рука', 'hand'],
  ['رحم', 'rahm, mehr', 'милость', 'mercy, womb'],
  ['دنو', 'yaqinlik, pastlik', 'близость', 'nearness, lowness'],
  ['عظم', 'ulug‘lik, suyak', 'величие, кость', 'greatness, bone'],
  ['سأل', 'so‘rash', 'спрашивание', 'asking'],
  ['وجد', 'topish, mavjudlik', 'нахождение', 'finding'],
  ['أجر', 'ajr, mukofot', 'награда, плата', 'reward, wage'],
  ['عزز', 'izzat, qudrat', 'могущество, честь', 'might, honour'],
  ['خرج', 'chiqish', 'выход', 'going out'],
  ['حكم', 'hukm, hikmat', 'суд, мудрость', 'judgement, wisdom'],
  ['أكل', 'yeyish', 'еда', 'eating'],
  ['دين', 'din, qarz, hisob', 'религия, долг', 'religion, debt, judgement'],
  ['غفر', 'yopish, kechirish', 'прощение', 'covering, forgiving'],
  ['شطن', 'uzoqlashish, shayton', 'отдаление, сатана', 'distance, devil'],
  ['فعل', 'qilish', 'действие', 'doing'],
  ['مثل', 'o‘xshashlik, misol', 'подобие, пример', 'likeness, example'],
  ['ملك', 'egalik, saltanat', 'владение, царство', 'ownership, kingship'],
  ['نظر', 'qarash, kutish', 'взгляд, ожидание', 'looking, waiting'],
  ['مول', 'mol, boylik', 'имущество', 'wealth'],
  ['ولي', 'yaqinlik, homiylik', 'близость, покровительство', 'nearness, guardianship'],
  ['ذكر', 'eslash, zikr', 'поминание', 'remembering, mentioning'],
  ['فضل', 'ortiqchalik, marhamat', 'превосходство, милость', 'excess, bounty'],
  ['ليل', 'tun', 'ночь', 'night'],
  ['خوف', 'qo‘rquv', 'страх', 'fear'],
  ['صلو', 'namoz, duo', 'молитва', 'prayer'],
  ['قتل', 'o‘ldirish', 'убийство', 'killing'],
  ['كيف', 'holat, qanaqalik', 'образ, как', 'manner, how'],
  ['أول', 'birinchilik, qaytish', 'первый, возвращение', 'first, returning'],
  ['كثر', 'ko‘plik', 'множество', 'abundance'],
  ['بني', 'qurish, o‘g‘il', 'строительство, сын', 'building, son'],
  ['رجع', 'qaytish', 'возвращение', 'returning'],
  ['صحب', 'hamrohlik', 'сопутствие', 'companionship'],
  ['سمع', 'eshitish', 'слух', 'hearing'],
  ['حيي', 'hayot, hayo', 'жизнь, стыдливость', 'life, modesty'],
  ['دخل', 'kirish', 'вхождение', 'entering'],
  ['زوج', 'juftlik', 'пара, супружество', 'pairing, spouse'],
  ['أخو', 'birodarlik', 'братство', 'brotherhood'],
  ['نبأ', 'xabar, payg‘ambarlik', 'весть, пророчество', 'news, prophethood'],
  ['أحد', 'birlik', 'единственность', 'oneness'],
  ['خلد', 'abadiylik', 'вечность', 'eternity'],
  ['صلح', 'yaxshilik, tuzatish', 'праведность, исправление', 'righteousness, reform'],
  ['جزي', 'jazo, mukofot', 'воздаяние', 'recompense'],
  ['طوع', 'itoat, qodirlik', 'повиновение', 'obedience, ability'],
  ['ألم', 'og‘riq', 'боль', 'pain'],
  ['وحي', 'vahiy, ishora', 'откровение', 'revelation, inspiration'],
  ['وجه', 'yuz, yo‘nalish', 'лицо, направление', 'face, direction'],
  ['شرك', 'sheriklik, shirk', 'соучастие, многобожие', 'partnership, associating'],
  ['لقي', 'uchrashish, tashlash', 'встреча', 'meeting, casting'],
  ['قرأ', 'o‘qish', 'чтение', 'reading, reciting'],
  ['قلل', 'ozlik', 'малость', 'fewness'],
  ['وعد', 'va’da', 'обещание', 'promising'],
  ['نفق', 'sarflash, nifoq', 'расходование, лицемерие', 'spending, hypocrisy'],
  ['بيت', 'uy, tunash', 'дом', 'house, spending the night'],
  ['يمن', 'o‘ng, baraka, qasam', 'правая сторона, благо', 'right side, blessing, oath'],
  ['أبو', 'otalik', 'отцовство', 'fatherhood'],
  ['حبب', 'sevgi, don', 'любовь, зерно', 'love, seed'],
  ['صوب', 'to‘g‘rilik, yetishish', 'правильность, поражение', 'correctness, striking'],
  ['ضلل', 'adashish', 'заблуждение', 'straying'],
  ['أمم', 'ummat, ona, maqsad', 'община, мать', 'community, mother, aim'],
  ['توب', 'qaytish, tavba', 'покаяние', 'repentance, turning back'],
  ['موه', 'suv', 'вода', 'water'],
  ['كسب', 'orttirish, kasb', 'приобретение', 'earning'],
  ['تلو', 'ergashish, tilovat', 'следование, чтение', 'following, reciting'],
  ['رزق', 'rizq berish', 'наделение уделом', 'providing'],
  ['صدق', 'rostlik, sadaqa', 'правдивость, милостыня', 'truthfulness, charity'],
  ['قضي', 'hukm, tugallash', 'решение, завершение', 'decreeing, completing'],
  ['نسو', 'ayollar', 'женщины', 'women'],
  ['نصر', 'yordam, g‘alaba', 'помощь, победа', 'help, victory'],
  ['سوأ', 'yomonlik', 'зло, скверна', 'evil, badness'],
  ['صبر', 'sabr, chidam', 'терпение', 'patience'],
  ['نذر', 'ogohlantirish, nazr', 'предостережение, обет', 'warning, vow'],
  ['جري', 'oqish, yugurish', 'течение, бег', 'flowing, running'],
  ['عين', 'ko‘z, buloq, ayn', 'глаз, источник', 'eye, spring'],
  ['قري', 'qishloq, mehmon kutish', 'селение', 'town, hosting'],
  ['نهر', 'daryo, kunduz', 'река, день', 'river, daylight'],
  ['شدد', 'qattiqlik, kuch', 'суровость, сила', 'severity, strength'],
  ['شهد', 'guvohlik, hozirlik', 'свидетельство', 'witnessing, presence'],
  ['مسس', 'tegish', 'касание', 'touching'],
  ['ولد', 'tug‘ilish, farzand', 'рождение, ребёнок', 'birth, child'],
  ['ضرب', 'urish, misol keltirish', 'удар, приведение примера', 'striking, setting forth'],
  ['جمع', 'to‘plash', 'собирание', 'gathering'],
  ['أجل', 'muddat, sabab', 'срок, причина', 'term, reason'],
  ['بعث', 'yuborish, tiriltirish', 'посылание, воскрешение', 'sending, resurrecting'],
  ['جرم', 'jinoyat, gunoh', 'преступление', 'crime, sin'],
  ['هلك', 'halokat', 'гибель', 'destruction'],
  ['بصر', 'ko‘rish, idrok', 'зрение', 'sight, insight'],
  ['فري', 'to‘qish, bo‘hton', 'измышление', 'fabricating'],
  ['عدو', 'dushmanlik, tajovuz', 'вражда', 'enmity, transgression'],
  ['موت', 'o‘lim', 'смерть', 'death'],
  ['نعم', 'ne’mat, yumshoqlik', 'благо', 'blessing, comfort'],
  ['زيد', 'ziyoda, ortish', 'увеличение', 'increase'],
  ['عقل', 'aql', 'разум', 'reason, intellect'],
  ['غيب', 'g‘oyib, yashirin', 'сокровенное', 'the unseen'],
  ['دور', 'aylanish, uy', 'круговорот, дом', 'turning, abode'],
  ['سوع', 'soat, vaqt', 'час', 'hour'],
  ['ظنن', 'gumon', 'предположение', 'assumption'],
  ['شكر', 'shukr', 'благодарность', 'gratitude'],
  ['خبر', 'xabar, sinash', 'весть, ведение', 'news, being aware'],
  ['صرط', 'yo‘l', 'путь', 'path'],
  ['قدر', 'qudrat, o‘lchov, taqdir', 'мощь, мера, предопределение', 'power, measure, decree'],
  ['وذر', 'tark etish', 'оставление', 'leaving'],
  ['حسب', 'hisob, o‘ylash', 'счёт, полагание', 'reckoning, thinking'],
  ['صدر', 'ko‘krak, chiqish', 'грудь, исход', 'chest, proceeding'],
  ['حمد', 'hamd, maqtov', 'хвала', 'praise'],
  ['سبح', 'suzish, tasbih', 'плавание, прославление', 'swimming, glorifying'],
  ['سلم', 'salomatlik, taslim', 'мир, покорность', 'peace, submission'],
  ['كلم', 'so‘z, gapirish', 'слово, речь', 'word, speaking'],
  ['بحر', 'dengiz', 'море', 'sea'],
  ['حمل', 'ko‘tarish, homiladorlik', 'ношение', 'carrying, bearing'],
  ['فوق', 'ustunlik, yuqorilik', 'над, превосходство', 'above, superiority'],
  ['كبر', 'kattalik, kibr', 'величие, гордыня', 'greatness, arrogance'],
  ['بأس', 'zarar, kuch, yomonlik', 'бедствие, мощь', 'harm, might, misery'],
  ['بلغ', 'yetish, yetkazish', 'достижение', 'reaching, conveying'],
  ['ترك', 'qoldirish', 'оставление', 'leaving'],
  ['وكل', 'topshirish, tavakkul', 'поручение, упование', 'entrusting, reliance'],
  ['خشي', 'qo‘rqish, hayiqish', 'страх', 'fearing, awe'],
  ['أذن', 'quloq, izn, azon', 'ухо, дозволение', 'ear, permission'],
  ['جبل', 'tog‘', 'гора', 'mountain'],
  ['حرم', 'taqiq, hurmat', 'запрет, святость', 'prohibition, sanctity'],
  ['حسن', 'yaxshilik, go‘zallik', 'красота, благо', 'goodness, beauty'],
  ['عرف', 'tanish, bilish', 'знание, признание', 'knowing, recognising'],
  ['بشر', 'insonlik, xushxabar', 'человек, благая весть', 'humanity, glad tidings'],
  ['حشر', 'to‘plash, mahshar', 'собирание', 'gathering'],
  ['ذنب', 'gunoh, dum', 'грех', 'sin, tail'],
  ['رضو', 'rozilik', 'довольство', 'pleasure, contentment']
] as const

/** Every authored word gloss, in frequency order. */
export const WORD_GLOSSES: readonly Gloss[] = [
  ...WORD_GLOSSES_1,
  ...WORD_GLOSSES_300,
  ...WORD_GLOSSES_550,
  ...WORD_GLOSSES_800,
  ...WORD_GLOSSES_1050,
  ...WORD_GLOSSES_1300,
  ...WORD_GLOSSES_1800
]

/** Every authored root gloss. */
export const ROOT_GLOSSES: readonly Gloss[] = [...ROOT_GLOSSES_1, ...ROOT_GLOSSES_2]
