import type { Gloss } from './glossary-types'

/**
 * Semantic field of roots ranked ~172–470 by Quranic frequency.
 *
 * A root gloss names the idea the whole family shares, not any one word: كتب is
 * "writing", which is why كِتاب (book), كاتِب (scribe) and مَكْتُوب (written) all
 * belong together. Keep these short — the specific meaning lives on the word.
 */
export const ROOT_GLOSSES_2: readonly Gloss[] = [
  ['كلل', 'butunlik, hammasi', 'целостность, всё', 'totality, all'],
  ['جيأ', 'kelish', 'приход', 'coming'],
  ['بعد', 'uzoqlik, keyinlik', 'отдалённость, после', 'distance, afterness'],
  ['عند', 'yonida bo‘lish', 'нахождение при', 'being at, presence'],
  ['دون', 'pastlik, o‘zgalik', 'ниже, помимо', 'below, other than'],
  ['خلف', 'ortda qolish, o‘rin bosish', 'позади, преемство', 'behind, succession'],
  ['قرب', 'yaqinlik', 'близость', 'nearness'],
  ['بغي', 'intilish, haddan oshish', 'стремление, преступание', 'seeking, transgressing'],
  ['سجد', 'sajda, egilish', 'земной поклон', 'prostration'],
  ['ليس', 'inkor, yo‘qlik', 'отрицание', 'negation'],
  ['نجو', 'qutulish, najot', 'спасение', 'deliverance'],
  ['سوي', 'tenglik, tekislik', 'равенство, ровность', 'evenness, equality'],
  ['عقب', 'iz, oqibat, ta’qib', 'след, последствие', 'heel, consequence'],
  ['عرض', 'ko‘rsatish, yon berish', 'представление, уклонение', 'presenting, turning aside'],
  ['ضرر', 'zarar', 'вред', 'harm'],
  ['رجل', 'oyoq, erkak', 'нога, мужчина', 'foot, man'],
  ['غني', 'boylik, behojatlik', 'богатство, независимость', 'wealth, sufficiency'],
  ['فرق', 'ajratish, bo‘linish', 'разделение', 'separating, dividing'],
  ['متع', 'bahra, foydalanish', 'наслаждение, пользование', 'enjoyment, provision'],
  ['علو', 'balandlik, ulug‘lik', 'высота, возвышенность', 'height, exaltation'],
  ['سكن', 'sokinlik, yashash', 'покой, обитание', 'stillness, dwelling'],
  ['وحد', 'yakkalik, birlik', 'единственность', 'oneness'],
  ['وفي', 'to‘lalik, vafo', 'полнота, верность', 'fullness, fulfilment'],
  ['خسر', 'ziyon, yo‘qotish', 'убыток', 'loss'],
  ['سحر', 'sehr; tong', 'колдовство; предрассветье', 'magic; dawn'],
  ['عود', 'qaytish, takrorlanish', 'возвращение', 'returning'],
  ['ذوق', 'tatib ko‘rish', 'вкушение', 'tasting'],
  ['فتن', 'sinov, fitna', 'испытание, смута', 'trial, temptation'],
  ['زكو', 'poklik, o‘sish', 'чистота, рост', 'purity, growth'],
  ['ظهر', 'orqa, zohir bo‘lish', 'спина, явность', 'back, becoming apparent'],
  ['ردد', 'qaytarish', 'возвращение, отвержение', 'returning, repelling'],
  ['عدد', 'sanoq, tayyorlash', 'счёт, подготовка', 'counting, preparing'],
  ['روح', 'ruh, shamol, orom', 'дух, ветер', 'spirit, wind, rest'],
  ['ذهب', 'ketish; oltin', 'уход; золото', 'going; gold'],
  ['نهي', 'to‘xtatish, chegara', 'запрет, предел', 'forbidding, limit'],
  ['فسق', 'itoatdan chiqish', 'нечестие', 'defiant disobedience'],
  ['ندي', 'chaqirish, nido', 'зов', 'calling out'],
  ['ضعف', 'zaiflik; ikkilanish', 'слабость; удвоение', 'weakness; doubling'],
  ['تحت', 'ostida bo‘lish', 'нахождение под', 'being beneath'],
  ['حلل', 'ruxsat, yechish, tushish', 'дозволенность, развязывание', 'lawfulness, untying, alighting'],
  ['فسد', 'buzilish, fasod', 'порча, нечестие', 'corruption'],
  ['طيب', 'poklik, yoqimlilik', 'благость, чистота', 'goodness, wholesomeness'],
  ['نفع', 'foyda', 'польза', 'benefit'],
  ['طعم', 'taom, yeyish', 'пища, вкушение', 'food, eating'],
  ['أثم', 'gunoh', 'грех', 'sin'],
  ['قدم', 'oldinlik, oyoq', 'предшествование, стопа', 'precedence, foot'],
  ['عجل', 'shoshilish', 'спешка', 'haste'],
  ['كرم', 'karam, ulug‘lik', 'благородство, щедрость', 'nobility, generosity'],
  ['عهد', 'ahd, va’dalashuv', 'завет, договор', 'covenant'],
  ['زين', 'bezash, ziynat', 'украшение', 'adornment'],
  ['نسي', 'unutish', 'забвение', 'forgetting'],
  ['صبح', 'tong, ertalab', 'утро, рассвет', 'morning'],
  ['بدل', 'almashtirish', 'замена', 'exchanging'],
  ['سرر', 'sir, quvonch, taxt', 'тайна, радость, ложе', 'secret, joy, couch'],
  ['يسر', 'osonlik; chap tomon', 'лёгкость; левая сторона', 'ease; left side'],
  ['حفظ', 'saqlash, muhofaza', 'хранение', 'preserving, guarding'],
  ['دبر', 'orqa, tadbir, oqibat', 'тыл, управление', 'back, managing, outcome'],
  ['جوب', 'javob berish', 'ответ', 'answering'],
  ['فصل', 'ajratish, batafsil bayon', 'разделение, разъяснение', 'separating, detailing'],
  ['مكر', 'makr, yashirin reja', 'козни', 'scheming'],
  ['حزن', 'g‘am, qayg‘u', 'печаль', 'grief'],
  ['قوي', 'kuch, quvvat', 'сила', 'strength'],
  ['سخر', 'bo‘ysundirish; masxara', 'подчинение; насмешка', 'subjecting; mocking'],
  ['صدد', 'to‘sish, yuz o‘girish', 'препятствование', 'hindering, turning away'],
  ['لعن', 'la’nat, rahmatdan uzoqlashtirish', 'проклятие', 'cursing'],
  ['طوف', 'aylanish, tavof', 'обход, кружение', 'circling, going around'],
  ['كره', 'yoqtirmaslik, majburlash', 'отвращение, принуждение', 'aversion, compulsion'],
  ['جهد', 'kuch sarflash, jihod', 'усердие, борьба', 'exertion, striving'],
  ['فلح', 'najot, muvaffaqiyat', 'преуспеяние', 'success, prosperity'],
  ['شعر', 'sezish, his; she’r', 'ощущение; поэзия', 'perceiving; poetry'],
  ['ملأ', 'to‘ldirish; kattalar', 'наполнение; знать', 'filling; chiefs'],
  ['طغي', 'haddan oshish, tug‘yon', 'бесчинство', 'transgressing bounds'],
  ['شرب', 'ichish', 'питьё', 'drinking'],
  ['سلط', 'hokimiyat, dalil', 'власть, довод', 'authority, proof'],
  ['قرر', 'qaror topish, sokinlik', 'утверждение, покой', 'settling, being fixed'],
  ['بلو', 'sinash', 'испытание', 'testing'],
  ['فتح', 'ochish, g‘alaba', 'открытие, победа', 'opening, victory'],
  ['هوي', 'tushish, havoyi nafs', 'падение, страсть', 'falling, desire'],
  ['مرأ', 'kishi, ayol', 'человек, женщина', 'person, woman'],
  ['ذرر', 'sochish, zurriyot, zarra', 'рассеивание, потомство', 'scattering, offspring, atom'],
  ['سبق', 'o‘zish, oldinlash', 'опережение', 'preceding, outstripping'],
  ['ألو', 'kamchilik qilish; ne’matlar', 'нерадение; блага', 'falling short; favours'],
  ['نكر', 'inkor, notanishlik, munkar', 'отрицание, порицаемое', 'denial, being unknown'],
  ['ريب', 'shubha', 'сомнение', 'doubt'],
  ['قطع', 'kesish, uzish', 'отсечение', 'cutting, severing'],
  ['بطل', 'botillik, behudalik', 'ложность, тщета', 'falsehood, futility'],
  ['حدث', 'yangilik, so‘zlash', 'новость, повествование', 'newness, narrating'],
  ['أوي', 'panoh topish, joylashish', 'приют', 'taking refuge'],
  ['قرن', 'avlod, qo‘shilish, shox', 'поколение, соединение', 'generation, joining, horn'],
  ['حين', 'vaqt, muddat', 'время', 'time, period'],
  ['عفو', 'afv, kechirim', 'прощение', 'pardon'],
  ['غفل', 'g‘aflat, beparvolik', 'беспечность', 'heedlessness'],
  ['مرر', 'o‘tish; achchiqlik', 'прохождение; горечь', 'passing; bitterness'],
  ['ورث', 'meros', 'наследство', 'inheritance'],
  ['كيد', 'hiyla, tuzoq', 'козни, хитрость', 'plotting, stratagem'],
  ['هزأ', 'masxara', 'насмешка', 'mockery'],
  ['وثق', 'mustahkamlik, ishonch', 'прочность, доверие', 'firmness, trust'],
  ['جنح', 'moyillik; qanot; gunoh', 'склонность; крыло', 'inclining; wing; blame'],
  ['خفي', 'yashirinlik', 'сокрытость', 'hiddenness'],
  ['عمي', 'ko‘rlik', 'слепота', 'blindness'],
  ['ظلل', 'soya', 'тень', 'shade'],
  ['حجج', 'dalil, hajj', 'довод, паломничество', 'argument, pilgrimage'],
  ['كفي', 'yetarlilik', 'достаточность', 'sufficiency'],
  ['شمس', 'quyosh', 'солнце', 'sun'],
  ['عرش', 'taxt, arsh', 'трон', 'throne'],
  ['جنب', 'yon, chetlash', 'бок, сторонение', 'side, avoiding'],
  ['قسم', 'bo‘lish; qasam', 'разделение; клятва', 'dividing; oath'],
  ['مدد', 'cho‘zish, madad', 'протяжение, помощь', 'extending, aid'],
  ['برر', 'yaxshilik, taqvo; quruqlik', 'благочестие; суша', 'righteousness; land'],
  ['عصي', 'itoatsizlik', 'непокорность', 'disobedience'],
  ['وري', 'yashirish; orqa', 'сокрытие; позади', 'concealing; behind'],
  ['وسع', 'kenglik, qamrash', 'широта, вместимость', 'breadth, encompassing'],
  ['وصي', 'vasiyat, tayinlash', 'завещание, наставление', 'enjoining, bequeathing'],
  ['ثلث', 'uch', 'три', 'three'],
  ['نصب', 'tikish, mashaqqat, ulush', 'установка, труд, доля', 'setting up, toil, share'],
  ['برك', 'baraka, doimiylik', 'благословение', 'blessing'],
  ['طهر', 'poklik', 'чистота', 'purity'],
  ['بدو', 'zohir bo‘lish; sahro', 'проявление; пустыня', 'appearing; desert'],
  ['حيث', 'joy, tomon', 'место, где', 'place, whereness'],
  ['شفع', 'juftlash, shafoat', 'заступничество, парность', 'intercession, pairing'],
  ['برأ', 'yaratish; xoli bo‘lish', 'сотворение; непричастность', 'creating; being free of'],
  ['خلص', 'soflik, ixlos', 'чистота, искренность', 'purity, sincerity'],
  ['قعد', 'o‘tirish', 'сидение', 'sitting'],
  ['شرر', 'yomonlik, sharr', 'зло', 'evil'],
  ['هجر', 'tark etish, hijrat', 'оставление, переселение', 'forsaking, emigrating'],
  ['غلب', 'g‘alaba, ustunlik', 'победа, превосходство', 'victory, prevailing'],
  ['لبث', 'qolish, turish', 'пребывание', 'remaining, tarrying'],
  ['هود', 'yahudiylik; qaytish', 'иудейство; возвращение', 'Jewishness; returning'],
  ['سعي', 'harakat, yugurish', 'усердие, устремление', 'striving, hastening'],
  ['صرف', 'burish, o‘zgartirish', 'отвращение, изменение', 'turning away, diverting'],
  ['قصص', 'hikoya, iz kuzatish', 'повествование, следование по следу', 'narrating, tracking'],
  ['أنث', 'urg‘ochilik, ayollik', 'женскость', 'femaleness'],
  ['عسي', 'ehtimol, umid', 'возможность, надежда', 'perhaps, hoping'],
  ['أفك', 'burish, uydirma', 'извращение, ложь', 'turning away, falsehood'],
  ['غشو', 'qoplash, o‘rash', 'покрытие', 'covering, overwhelming'],
  ['ثني', 'ikkilash, burish', 'удвоение, сгибание', 'doubling, folding'],
  ['رفع', 'ko‘tarish', 'поднятие', 'raising'],
  ['ودد', 'sevgi, istak', 'любовь, желание', 'love, wishing'],
  ['صير', 'aylanish, qaytar joy', 'становление, исход', 'becoming, destination'],
  ['جدل', 'bahs, tortishuv', 'спор', 'disputing'],
  ['جند', 'lashkar', 'войско', 'army'],
  ['طير', 'uchish, qush; qismat', 'полёт, птица', 'flying, bird; omen'],
  ['فوز', 'yutuq, najot', 'успех', 'triumph, success'],
  ['دري', 'bilish, sezish', 'знание', 'knowing'],
  ['يقن', 'yaqin, aniq ishonch', 'убеждённость', 'certainty'],
  ['خلو', 'bo‘shlik, o‘tish, xilvat', 'пустота, уединение', 'emptiness, passing, seclusion'],
  ['حوط', 'qamrab olish', 'охват', 'encompassing'],
  ['سبع', 'yetti; yirtqich', 'семь; хищник', 'seven; beast of prey'],
  ['عدل', 'adolat, muvozanat', 'справедливость', 'justice, balance'],
  ['شقق', 'yorilish, mashaqqat, qarshilik', 'раскол, тягота', 'splitting, hardship, dissent'],
  ['أبد', 'abadiylik', 'вечность', 'eternity'],
  ['ثوب', 'qaytish, mukofot; kiyim', 'возвращение, награда; одежда', 'returning, reward; garment'],
  ['رجو', 'umid', 'надежда', 'hope'],
  ['ثقل', 'og‘irlik', 'тяжесть', 'heaviness'],
  ['نشأ', 'paydo bo‘lish, o‘sish', 'возникновение, рост', 'coming into being, growing'],
  ['شجر', 'daraxt; nizolashish', 'дерево; распря', 'tree; dispute'],
  ['منن', 'ne’mat berish; minnat', 'милость; попрёк', 'bestowing favour; reproach'],
  ['بوب', 'eshik', 'дверь', 'door'],
  ['عشر', 'o‘n; muomala', 'десять; общение', 'ten; consorting'],
  ['عجب', 'hayrat', 'удивление', 'wonder, amazement'],
  ['مسك', 'ushlash, tutish', 'удержание', 'holding, grasping'],
  ['غرر', 'aldanish, mag‘rurlik', 'обольщение', 'delusion, deception'],
  ['سير', 'yurish, safar', 'путешествие', 'travelling'],
  ['وزر', 'yuk, gunoh; vazir', 'бремя, грех', 'burden, sin; minister'],
  ['قمر', 'oy', 'луна', 'moon'],
  ['مدن', 'shahar', 'город', 'city'],
  ['نبت', 'o‘simlik, unish', 'растение, произрастание', 'plant, growing'],
  ['خزي', 'xorlik, sharmandalik', 'позор', 'disgrace'],
  ['هون', 'xorlik, yengillik', 'унижение, лёгкость', 'humiliation, ease'],
  ['جحم', 'olovning gurillashi', 'пылание', 'blazing fire'],
  ['وضع', 'qo‘yish, tushirish', 'положение, снятие', 'placing, laying down'],
  ['عجز', 'ojizlik', 'бессилие', 'incapacity'],
  ['شري', 'sotib olish, sotish', 'покупка, продажа', 'buying, selling'],
  ['حول', 'aylanish, o‘zgarish; yil', 'превращение; год', 'turning, changing; year'],
  ['أدم', 'Odam, insonlik', 'Адам, человечество', 'Adam, humankind'],
  ['سقي', 'suv berish', 'поение', 'giving to drink'],
  ['وعظ', 'nasihat', 'наставление', 'admonition'],
  ['حضر', 'hozir bo‘lish', 'присутствие', 'being present'],
  ['فلك', 'kema; falak', 'корабль; небосвод', 'ship; orbit'],
  ['بطن', 'ich, qorin, botin', 'внутренность, живот', 'inside, belly'],
  ['حدد', 'chegara, temir', 'предел, железо', 'limit, iron'],
  ['بسط', 'yoyish, kengaytirish', 'простирание', 'spreading out'],
  ['قسط', 'adolat, o‘lchov', 'справедливость', 'equity, justice'],
  ['وهب', 'hadya, in’om', 'дарование', 'granting, bestowing'],
  ['لسن', 'til', 'язык', 'tongue, language'],
  ['صلي', 'olovga kirish, kuyish', 'горение', 'burning, roasting'],
  ['غضب', 'g‘azab', 'гнев', 'anger'],
  ['مرض', 'kasallik', 'болезнь', 'illness'],
  ['كود', 'yaqinlik, oz qolish', 'близость к действию', 'being about to'],
  ['ثمر', 'meva, hosil', 'плод', 'fruit'],
  ['فجر', 'yorilish, tong; fisq', 'рассвет, разлом; распутство', 'breaking forth, dawn; wickedness'],
  ['ذلل', 'xorlik, bo‘ysunish', 'унижение, покорность', 'lowliness, submission'],
  ['جهل', 'johillik, bilimsizlik', 'невежество', 'ignorance'],
  ['عمر', 'obod qilish, umr', 'обустройство, жизнь', 'inhabiting, lifespan'],
  ['فحش', 'fahsh, haddan oshgan yomonlik', 'мерзость', 'indecency'],
  ['رقب', 'kuzatish, bo‘yin', 'наблюдение, шея', 'watching, neck'],
  ['أذي', 'aziyat, ozor', 'вред, обида', 'harm, hurt'],
  ['وقع', 'tushish, sodir bo‘lish', 'падение, свершение', 'falling, occurring'],
  ['مشي', 'yurish', 'ходьба', 'walking'],
  ['لبس', 'kiyish; chalkashtirish', 'одевание; смешение', 'clothing; confusing'],
  ['غرق', 'g‘arq bo‘lish', 'потопление', 'drowning'],
  ['يتم', 'yetimlik', 'сиротство', 'orphanhood'],
  ['سرع', 'tezlik', 'быстрота', 'swiftness'],
  ['نكح', 'nikoh', 'брак', 'marriage'],
  ['طلق', 'ozod qilish, taloq', 'освобождение, развод', 'releasing, divorce'],
  ['سرف', 'isrof, haddan oshish', 'расточительство', 'excess, extravagance'],
  ['وزن', 'tortish, o‘lchov', 'взвешивание', 'weighing'],
  ['ربع', 'to‘rt', 'четыре', 'four'],
  ['خطأ', 'xato, gunoh', 'ошибка, грех', 'error, sin'],
  ['مني', 'orzu; taqdir; nutfa', 'желание; семя', 'wishing; fate; seed'],
  ['ألف', 'ming; ulfat, birlashish', 'тысяча; сближение', 'thousand; joining, affinity'],
  ['تمم', 'to‘lalik, kamolot', 'завершённость', 'completeness'],
  ['غوي', 'adashish, gumrohlik', 'заблуждение', 'error, deviation'],
  ['ترب', 'tuproq; tengdosh', 'земля, прах', 'dust, earth; peer'],
  ['فرح', 'quvonch', 'радость', 'joy'],
  ['عرب', 'arablik, arabcha', 'арабский', 'Arabness, Arabic'],
  ['حذر', 'ehtiyot, saqlanish', 'осторожность', 'caution, wariness'],
  ['حجر', 'tosh; to‘siq, man qilish', 'камень; преграда', 'stone; barrier, forbidding'],
  ['كتم', 'yashirish', 'сокрытие', 'concealing'],
  ['شهر', 'oy (kalendar); mashhurlik', 'месяц; известность', 'month; fame'],
  ['حلم', 'halimlik; tush', 'кротость; сон', 'forbearance; dream'],
  ['بقي', 'qolish, boqiylik', 'пребывание, остаток', 'remaining, lasting'],
  ['سنن', 'yo‘l, odat; tish', 'обычай, установление', 'way, practice'],
  ['فتي', 'yigitlik; fatvo', 'юность; разъяснение', 'youth; giving a ruling'],
  ['أثر', 'iz, ta’sir', 'след, влияние', 'trace, effect'],
  ['حمم', 'qaynoqlik; yaqinlik', 'жар, кипяток', 'heat, boiling; closeness'],
  ['نشر', 'yoyish, tiriltirish', 'распространение, воскрешение', 'spreading, resurrecting'],
  ['سنو', 'yil', 'год', 'year'],
  ['مري', 'shubha, bahs', 'сомнение, спор', 'doubt, disputing'],
  ['درج', 'daraja, bosqich', 'ступень', 'degree, step'],
  ['ربو', 'o‘sish, ko‘payish; ribo', 'рост; ростовщичество', 'growth, increase; usury'],
  ['نخل', 'xurmo daraxti', 'финиковая пальма', 'date palm'],
  ['نزع', 'tortib olish, yulish', 'вырывание', 'pulling out, snatching'],
  ['نفخ', 'puflash', 'дуновение', 'blowing'],
  ['فقه', 'chuqur tushunish', 'глубокое понимание', 'deep understanding'],
  ['صنع', 'yasash, hunar', 'изготовление, ремесло', 'making, craft'],
  ['حزب', 'guruh, jamoa', 'группа, партия', 'party, group'],
  ['لعب', 'o‘yin', 'игра', 'play'],
  ['فطر', 'yaratish, yorish, tabiat', 'сотворение, естество', 'originating, natural disposition'],
  ['كشف', 'ochish, ko‘tarish', 'раскрытие, устранение', 'uncovering, removing'],
  ['ثمن', 'baho; sakkiz', 'цена; восемь', 'price; eight'],
  ['غرب', 'g‘arb, uzoqlik, g‘ariblik', 'запад, чуждость', 'west, strangeness'],
  ['بلد', 'shahar, yurt', 'город, страна', 'town, land'],
  ['رشد', 'to‘g‘ri yo‘l, kamolot', 'праведность, зрелость', 'right guidance, maturity'],
  ['صور', 'shakl, surat; sur', 'форма, образ; рог', 'form, image; trumpet'],
  ['طلع', 'chiqish, ko‘rinish', 'восход, появление', 'rising, appearing'],
  ['سعر', 'alanga, olovni yoqish', 'разжигание, пламя', 'kindling, blaze'],
  ['فكه', 'meva; hazil', 'фрукты; веселье', 'fruit; jesting'],
  ['فرض', 'farz, belgilash, ulush', 'предписание, доля', 'ordaining, obligation, share'],
  ['ملل', 'din yo‘li, millat', 'вероучение', 'creed, religious way'],
  ['دبب', 'yerda yurish, jonivor', 'ползание, тварь', 'crawling, creature'],
  ['رأس', 'bosh', 'голова', 'head'],
  ['خصم', 'nizo, raqib', 'спор, противник', 'dispute, adversary'],
  ['فكر', 'fikr, tafakkur', 'размышление', 'thinking, reflecting'],
  ['ثبت', 'sobitlik, mustahkamlik', 'стойкость', 'firmness, steadfastness'],
  ['لدن', 'huzur, tomon', 'от, со стороны', 'from the presence of'],
  ['حصن', 'himoya, qal’a, iffat', 'защита, крепость, целомудрие', 'fortification, chastity'],
  ['نفر', 'guruh; qochish', 'группа; бегство', 'group; fleeing, going forth'],
  ['مكن', 'imkon, mustahkam o‘rin', 'возможность, укрепление', 'enabling, establishing'],
  ['نوب', 'qaytish, tavba', 'обращение, покаяние', 'turning back, repenting'],
  ['سور', 'sura; devor', 'сура; стена', 'sura; wall'],
  ['خشع', 'xushu’, tavoze’', 'смирение', 'humility, submissiveness'],
  ['بوأ', 'joylashtirish, maskan', 'поселение, обитель', 'settling, abode'],
  ['عوذ', 'panoh so‘rash', 'прибежище', 'seeking refuge'],
  ['خفف', 'yengillashtirish', 'облегчение', 'lightening'],
  ['منع', 'man qilish, to‘sish', 'воспрепятствование', 'preventing, withholding'],
  ['شرق', 'sharq, chiqish', 'восток', 'east, sunrise'],
  ['صفو', 'soflik, tanlanganlik', 'чистота, избранность', 'purity, being chosen'],
  ['ربص', 'kutish, poylash', 'выжидание', 'waiting, lying in wait'],
  ['نقم', 'intiqom, qoralash', 'возмездие', 'retribution, condemning'],
  ['أوب', 'qaytish', 'возвращение', 'returning'],
  ['زعم', 'da’vo, gumon', 'утверждение, домысел', 'claiming, alleging'],
  ['سوق', 'haydash; bozor; soq', 'гон; рынок; голень', 'driving; market; shin'],
  ['جهر', 'oshkoralik, baland ovoz', 'громкость, явность', 'loudness, openness'],
  ['علن', 'oshkora qilish', 'объявление', 'making public'],
  ['لبب', 'aql, mag‘iz', 'разум, суть', 'intellect, core'],
  ['خون', 'xiyonat', 'предательство', 'betrayal'],
  ['مهد', 'tekislash, beshik, maskan', 'выравнивание, колыбель', 'smoothing, cradle, preparing'],
  ['حبط', 'behuda ketish', 'тщетность', 'coming to nothing'],
  ['خبث', 'nopoklik, yomonlik', 'скверна', 'foulness, wickedness'],
  ['غدو', 'erta tong, borish', 'утро, отправление', 'early morning, setting out'],
  ['غلل', 'kishan, xiyonat, kek', 'оковы, злоба', 'shackles, rancour'],
  ['عتد', 'tayyorlash', 'приготовление', 'preparing'],
  ['سطر', 'chiziq, yozuv', 'строка, письмо', 'line, writing'],
  ['لهو', 'ermak, chalg‘ish', 'забава, отвлечение', 'amusement, distraction'],
  ['فأد', 'yurak, dil', 'сердце', 'heart'],
  ['كيل', 'o‘lchov, o‘lchash', 'мера', 'measure'],
  ['صمم', 'karlik', 'глухота', 'deafness'],
  ['سوم', 'belgi qo‘yish; boqish; azob berish', 'мечение; выпас; насылание', 'marking; pasturing; inflicting'],
  ['حرر', 'ozod qilish; issiqlik', 'освобождение; жар', 'freeing; heat'],
  ['كفف', 'to‘xtatish; kaft', 'удержание; ладонь', 'restraining; palm'],
  ['ركب', 'minish, ustma-ust qo‘yish', 'езда, соединение', 'riding, assembling'],
  ['بيع', 'savdo, sotish', 'торговля', 'trade, selling'],
  ['مسح', 'silash, artish; masih', 'обтирание; мессия', 'wiping; Messiah'],
  ['حرج', 'tanglik, qiyinchilik', 'стеснение', 'constraint, hardship'],
  ['مطر', 'yomg‘ir', 'дождь', 'rain'],
  ['شكك', 'shubha', 'сомнение', 'doubt'],
  ['بدأ', 'boshlash', 'начало', 'beginning'],
  ['حرث', 'ekin, dehqonchilik', 'посев, пашня', 'tilling, crops'],
  ['صوم', 'ro‘za', 'пост', 'fasting']
] as const
